### ISSUE TITLE
README的图片全部炸了

### ISSUE THREAD

**Issue by BlueSkyXN** [Xhofe/alist#1]

**Comment by Xhofe** [comment]
#### 没有挂啊，你挂代理试试看？

**Comment by BlueSkyXN** [comment]
> #### 没有挂啊，你挂代理试试看？

https://camo.githubusercontent.com/cc944a564d12e16eb2aa5b34831cab158d3c855b7e4b2f1a01a50aa9f76c2846/68747470733a2f2f696d672e6f657a2e63632f323032302f31322f32342f316662313662633235613466362e706e67

现在又好了，昨晚打不开emmm
