### ISSUE TITLE
希望前端可以适配微信内宽度

### ISSUE THREAD

**Issue by vbskycn** [Xhofe/alist#10]
1.04版的很赞
不过在微信内宽度还有有点问题
左边的内容看不到，而且不能移到左边
在浏览器内正常

**Comment by vbskycn** [comment]
对了，关于那个在线打开文档
目前用作者自已的服务器接口，用户多了肯定抗不住
不知道能不能调用阿里网盘自带的（那个速度真快呀）
kkFileView想在自已的服务器搭建，怎么都起不来，后来docker成功了，转换速度也是巨慢

**Comment by Xhofe** [comment]
> 1.04版的很赞
> 不过在微信内宽度还有有点问题
> 左边的内容看不到，而且不能移到左边
> 在浏览器内正常

是安卓端的微信吗 目前手上没有安卓的手机。。iOS微信测试没有发现问题。

**Comment by Xhofe** [comment]
> 对了，关于那个在线打开文档
> 目前用作者自已的服务器接口，用户多了肯定抗不住
> 不知道能不能调用阿里网盘自带的（那个速度真快呀）
> kkFileView想在自已的服务器搭建，怎么都起不来，后来docker成功了，转换速度也是巨慢

之前没有发现阿里网盘自带的，刚刚看了一下 确实很快，看起来应该可以调用。等我研究一下

**Comment by vbskycn** [comment]
> > 1.04版的很赞
> > 不过在微信内宽度还有有点问题
> > 左边的内容看不到，而且不能移到左边
> > 在浏览器内正常
> 
> 是安卓端的微信吗 目前手上没有安卓的手机。。iOS微信测试没有发现问题。

是的，ios很正常，就是安卓的手机看不到左边的内容，而且不能移动位置

**Comment by vbskycn** [comment]
> > 对了，关于那个在线打开文档
> > 目前用作者自已的服务器接口，用户多了肯定抗不住
> > 不知道能不能调用阿里网盘自带的（那个速度真快呀）
> > kkFileView想在自已的服务器搭建，怎么都起不来，后来docker成功了，转换速度也是巨慢
> 
> 之前没有发现阿里网盘自带的，刚刚看了一下 确实很快，看起来应该可以调用。等我研究一下

谢谢大佬，尽候下一版本

**Comment by sottboy** [comment]
**视频格式MKV无声，这也是能解决的吗？**

**Comment by Xhofe** [comment]
> **视频格式MKV无声，这也是能解决的吗？**
> 还有多种格式无法预览，我放了一个PDF和一个EXCEL都无法看。

PDF和EXCEL是可以预览的啊，设置了5M的限制，现在的接口会很慢。目前正在研究如何调用啊里云盘那边的office接口。mkv视频播放没有声音可能没有办法了，是直接使用的`dplayer`，可能是浏览器或`dplayer`不支持某种视频编码，建议可以直接复制直链到`potplayer`中播放。

**Comment by sottboy** [comment]
> 

> 

> > **视频格式MKV无声，这也是能解决的吗？**
> > 还有多种格式无法预览，我放了一个PDF和一个EXCEL都无法看。
> 
> PDF和EXCEL是可以预览的啊，设置了5M的限制，现在的接口会很慢。目前正在研究如何调用啊里云盘那边的office接口。mkv视频播放没有声音可能没有办法了，是直接使用的`dplayer`，可能是浏览器或`dplayer`不支持某种视频编码，建议可以直接复制直链到`potplayer`中播放。

那个安卓的面画适配样式可以修一下吗，的确不是很美观

**Comment by Xhofe** [comment]
手上没有安卓的设备。。。安卓的页面有什么问题吗❓

**Comment by GH6324** [comment]
> 手上没有安卓的设备。。。安卓的页面有什么问题吗

就像这样
[https://gejiba.com/view.php/f8f7b998380a6ad2d48ccf59e3f0e21a.jpg](url)

**Comment by GH6324** [comment]
就像这样
![ 安卓微信] （https://gejiba.com/view.php/f8f7b998380a6ad2d48ccf59e3f0e21a.jpg）

**Comment by GH6324** [comment]
> 手上没有安卓的设备。。。安卓的页面有什么问题吗

<img src="https://gejiba.com/view.php/f8f7b998380a6ad2d48ccf59e3f0e21a.jpg"/>

**Comment by GH6324** [comment]
安卓微信内置浏览器就会出现下面这个情况
![IMG_20210112_142646](https://gejiba.com/view.php/2f33d34bcfd2f9344a2b08837960d12f.jpg)

**Comment by Xhofe** [comment]
> 安卓微信内置浏览器就会出现下面这个情况
> ![IMG_20210112_142646](https://camo.githubusercontent.com/f3b43f8870e604b915ce8196b036bac00f0052ea7e8244fee6efa66a76f2cc78/68747470733a2f2f67656a6962612e636f6d2f766965772e7068702f32663333643334626366643266393334346132623038383337393630643132662e6a7067)

刚刚借了部安卓手机 排查一下

**Comment by Xhofe** [comment]
改了一下安卓微信端的样式 虽然还是达不到非安卓微信端那样的样式 但是不会出现左侧被裁切的情况了
