### ISSUE TITLE
建议直链内不使用中文

### ISSUE THREAD

**Issue by zsbai** [Xhofe/alist#100]
直链内带中文确实不太方便，用做图床在其他地方会有些奇奇怪怪的问题，可以网页路径不用变，希望 复制直链 能直接复制已经编码的链接

**Comment by Xhofe** [comment]
已经是编码过的了啊。。。

**Comment by zsbai** [comment]
> 已经是编码过的了啊。。。

最新版复制直链还是带中文的（委屈
https://api.baiblog.ren/d/C/图片🌃/01/IMG_0933.JPG?pw=68fc8f84b0ce5046

**Comment by Xhofe** [comment]
哦哦 忘记改里面的复制了 只改了外面目录的复制

**Comment by Xhofe** [comment]
https://github.com/Xhofe/alist-web/commit/7a32df29fd01f3c49386c9237f3401f8bdefb83d

**Comment by zsbai** [comment]
感谢

> Xhofe/alist-web@7a32df2
