### ISSUE TITLE
请求添加对MinIO存储的支持

### ISSUE THREAD

**Issue by xueJLcat** [Xhofe/alist#1001]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我在使用S3添加minio存储时，因为minio的请求并不是S3的通用兼容请求，而且默认没有地域设置。无法使用。
所以请求加入对minio存储的支持

### Additional context / 附件

http://www.minio.org.cn/

**Comment by Xhofe** [comment]
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/36558727/165441338-1b954536-25ca-43ac-842f-a19087fbd71a.png">
我没有发现哪里有不兼容的地方。参考配置：

```json
{
  "name": "minio",
  "index": 0,
  "type": "S3",
  "username": "",
  "password": "",
  "refresh_token": "",
  "access_token": "",
  "root_folder": "",
  "status": "work",
  "CronId": 0,
  "DriveId": "",
  "limit": 4,
  "order_by": "",
  "order_direction": "",
  "updated_at": "2022-04-27T12:32:04.536974+08:00",
  "search": false,
  "client_id": "",
  "client_secret": "",
  "zone": ".placeholder",
  "redirect_uri": "",
  "site_url": "",
  "site_id": "",
  "internal_type": "v1",
  "webdav_proxy": false,
  "proxy": false,
  "webdav_direct": false,
  "down_proxy_url": "",
  "api_proxy_url": "",
  "bucket": "test-alist",
  "endpoint": "http://127.0.0.1:9000",
  "region": "any",
  "access_key": "user",
  "access_secret": "password",
  "custom_host": "",
  "extract_folder": "",
  "bool_1": true
}
```

**Comment by xueJLcat** [comment]
感谢回答，问题结束，谢谢大佬
