### ISSUE TITLE
Content-Type 问题

### ISSUE THREAD

**Issue by WntFlm** [Xhofe/alist#1007]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在 `server/controllers/file/upload.go UploadFiles()` 中，由于直接使用接收到的 Content-Type 作为文件的 MIMIType，并且在 Upload 时直接发出去，这可能引发一系列的问题。如：

### 上传错误
如果使用 quark + webdav 上传，在 `UpPre()` 过程中需要使用 `format_type` 参数，而这一参数来自于上述的 `model.FileStream.MIMEType`，如果 webdav PUT 报文未携带 Content-Type 信息（如 python 的 webdav3 库），则会报错
```
[GIN] 2022/04/28 - 12:29:17 | 302 |     66.6303ms |       127.0.0.1 | HEAD     "/dav/quark/test/"
[GIN] 2022/04/28 - 12:29:17 | 200 |       294.8µs |       127.0.0.1 | HEAD     "/p/quark/test?sign=8db09a326853fe4f"
ERRO[2022-04-28 12:29:17] upload error: Bad Parameter: [format_type is null!] 
ERRO[2022-04-28 12:29:17] Bad Parameter: [format_type is null!]        
[GIN] 2022/04/28 - 12:29:17 | 405 |     50.0236ms |       127.0.0.1 | PUT      "/dav/quark/test/cloud.py"
[GIN] 2022/04/28 - 12:29:17 | 207 |    318.0504ms |       127.0.0.1 | PROPFIND  "/dav/quark/test/"
[GIN] 2022/04/28 - 12:29:17 | 207 |       342.4µs |       127.0.0.1 | PROPFIND  "/dav/quark/"
[GIN] 2022/04/28 - 12:29:17 | 207 |       286.5µs |       127.0.0.1 | PROPFIND  "/dav/"
```
### 类型错误
另一种情况是，RaiDrive 在进行文件传输时，不论什么文件，都将 Content-Type 设置为 application/octet-stream，这将导致 quark 无法正确识别文件类型，从而使网页端视频文件无法在线播放，zip文件无法在线解压

![image](https://user-images.githubusercontent.com/34620278/165682125-0dae3b60-ba49-47bd-8705-4ad349a34a17.png)
![image](https://user-images.githubusercontent.com/34620278/165682438-5c6c7d7c-65c9-4888-93a8-f96ed6edebaa.png)

### Suggested solution / 实现思路

希望可以在接受或者发送文件时重新生成/识别一次 MIMEType

**Comment by xinjiajuan** [comment]
直链都无法用在其他网站上面，都是stream的type，不能做资源站，只能做下载站

**Comment by Extrwave** [comment]
I really hope to realize the function of setting content-type according to the file type, which can be used for both uploading and downloading.

**Comment by Extrwave** [comment]
@Xhofe Replace the preview route with a new preview method, which sets the response.content-type based on the file type, instead of the original down method. 
It is not appropriate to return application/octet-stream for preview files.
