### ISSUE TITLE
启动正常，重建目录出错

### ISSUE THREAD

**Issue by jing5460** [Xhofe/alist#101]
四个盘都成功刷新所有token，但是重建目录时就无法运行，出现报错！
![image](https://user-images.githubusercontent.com/38358681/116236282-7336cd80-a791-11eb-83ca-f97e93922868.png)

![image](https://user-images.githubusercontent.com/38358681/116236218-5ef2d080-a791-11eb-9049-39d0259074a5.png)

![image](https://user-images.githubusercontent.com/38358681/116236513-bb55f000-a791-11eb-9851-389a928df689.png)

![image](https://user-images.githubusercontent.com/38358681/116236632-e3ddea00-a791-11eb-9822-b6c35f605315.png)

![image](https://user-images.githubusercontent.com/38358681/116236911-30c1c080-a792-11eb-8a90-09043dd564bb.png)

**Comment by Xhofe** [comment]
可能是有一个目录下文件过多，阿里云好像不允许一次性请求很多很多的文件，之后可能要改成分页请求。

**Comment by jing5460** [comment]
按你的方法已经成功的解决，感谢
