### ISSUE TITLE
在已允许访客上传的情况下，使用guest账户无上传权限

### ISSUE THREAD

**Issue by ujmyvq1582** [Xhofe/alist#1014]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

6c0d543

### Describe the bug / 问题描述

在配置员已经配置好要给访客用户显示的文件夹，并且选中了允许访客上传，可是不管webdav还是网页，都没有上传权限。

### Reproduction / 复现链接

由于是在内网搭建的，无法提供地址。

**Comment by Xhofe** [comment]
本来就无法上传。
