### ISSUE TITLE
希望增加移动端 「菜单支持」

### ISSUE THREAD

**Issue by YJLAugus** [Xhofe/alist#1018]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

在PC端可以右键出现菜单，但是这一点好像在移动端无法使用，比如，想在移动端新建一个文件夹，这个就没办法做到。希望增加此功能支持。

**Comment by mymine** [comment]
+1。好像手机360浏览器可以但是不适应屏幕有些菜单被遮挡了，
