### ISSUE TITLE
您好，请问一下怎么对root目录下的文件进行加密

### ISSUE THREAD

**Issue by LuckyMango** [Xhofe/alist#102]
作者您好，请问一下当我设置了Path路径为root后，我想对root下的有些目录进行加密，但是我不知道怎么进行配置。

**Comment by Xhofe** [comment]
> 如何给文件夹设置密码？
在要加密的目录名称后面加上.password-密码，列表中会自动消除后面的密码部分。

**Comment by LuckyMango** [comment]
> > 如何给文件夹设置密码？
> > 在要加密的目录名称后面加上.password-密码，列表中会自动消除后面的密码部分。

您好，我还是不太明白。在配置文件中设置了root目录，但是我不知道在哪里添加.password-密码。

**Comment by Xhofe** [comment]
> > > 如何给文件夹设置密码？
> > > 在要加密的目录名称后面加上.password-密码，列表中会自动消除后面的密码部分。
> 
> 您好，我还是不太明白。在配置文件中设置了root目录，但是我不知道在哪里添加.password-密码。

就是在阿里云盘里直接改目录名称，目录名后面加

**Comment by LuckyMango** [comment]
> > > > 如何给文件夹设置密码？
> > > > 在要加密的目录名称后面加上.password-密码，列表中会自动消除后面的密码部分。
> > 
> > 
> > 您好，我还是不太明白。在配置文件中设置了root目录，但是我不知道在哪里添加.password-密码。
> 
> 就是在阿里云盘里直接改目录名称，目录名后面加

万分感谢 ~
