### ISSUE TITLE
pikpak速度缓慢，与App端速度不符

### ISSUE THREAD

**Issue by xiahecode** [Xhofe/alist#1028]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2

### Describe the bug / 问题描述

在pikpak中，无代理情况下，能够流畅播放4K电影，并以12m/s平均速度下载，但在alist或取得直链中，速度仅1m/s不到，这应当是不正常的

### Reproduction / 复现链接

https://cnfiles.xhwork.top:45244/pikpak/My%20Pack/The.Battle.At.Lake.Changjin.2021.2160p.WEB-DL.H265.DDP-ARiC.mkv

**Comment by Xhofe** [comment]
<img width="1555" alt="image" src="https://user-images.githubusercontent.com/36558727/166152981-2c0765fb-8669-4b9b-87b6-70edeff3e9b5.png">
