### ISSUE TITLE
无法下载文件

### ISSUE THREAD

**Issue by hyzaw** [Xhofe/alist#104]
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>InvalidArgument</Code>
<Message>At least one of AdditionalHeaders is not in request headers.</Message>
<RequestId>608E502CC83E673737ACC749</RequestId>
<HostId>bj29.cn-beijing.data.alicloudccp.com</HostId>
</Error>

**Comment by hyzaw** [comment]
`<Error>
<Code>InvalidArgument</Code>
<Message>At least one of AdditionalHeaders is not in request headers.</Message>
<RequestId>608E502CC83E673737ACC749</RequestId>
<HostId>bj29.cn-beijing.data.alicloudccp.com</HostId>
</Error>`

**Comment by Xhofe** [comment]
#88 
https://www.nn.ci/archives/alist.html#toc_9

**Comment by hyzaw** [comment]
> #88
> https://www.nn.ci/archives/alist.html#toc_9

web.exe貌似有问题

ERROR:pywebio.session.base:Error
Traceback (most recent call last):
  File "pywebio\session\threadbased.py", line 86, in main_task
  File "web.py", line 96, in password
  File "web.py", line 37, in login_by_password
  File "web.py", line 25, in login_session
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 449, in send
  File "urllib3\connectionpool.py", line 696, in urlopen
  File "urllib3\connectionpool.py", line 964, in _prepare_proxy
  File "urllib3\connection.py", line 359, in connect
  File "urllib3\connection.py", line 506, in _connect_tls_proxy
  File "urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 827, in _create
ValueError: check_hostname requires server_hostname

**Comment by Xhofe** [comment]
> > #88
> > https://www.nn.ci/archives/alist.html#toc_9
> 
> web.exe貌似有问题
> 
> ERROR:pywebio.session.base:Error
> Traceback (most recent call last):
> File "pywebio\session\threadbased.py", line 86, in main_task
> File "web.py", line 96, in password
> File "web.py", line 37, in login_by_password
> File "web.py", line 25, in login_session
> File "requests\sessions.py", line 542, in request
> File "requests\sessions.py", line 655, in send
> File "requests\adapters.py", line 449, in send
> File "urllib3\connectionpool.py", line 696, in urlopen
> File "urllib3\connectionpool.py", line 964, in _prepare_proxy File "urllib3\connection.py", line 359, in connect File "urllib3\connection.py", line 506, in _connect_tls_proxy File "urllib3\util\ssl_.py", line 432, in ssl_wrap_socket File "urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
> File "ssl.py", line 423, in wrap_socket
> File "ssl.py", line 827, in _create
> ValueError: check_hostname requires server_hostname

挂了代理吗，可能是代理的问题

**Comment by hyzaw** [comment]
> > > #88
> > > https://www.nn.ci/archives/alist.html#toc_9
> > 
> > 
> > web.exe貌似有问题
> > ERROR:pywebio.session.base:Error
> > Traceback (most recent call last):
> > File "pywebio\session\threadbased.py", line 86, in main_task
> > File "web.py", line 96, in password
> > File "web.py", line 37, in login_by_password
> > File "web.py", line 25, in login_session
> > File "requests\sessions.py", line 542, in request
> > File "requests\sessions.py", line 655, in send
> > File "requests\adapters.py", line 449, in send
> > File "urllib3\connectionpool.py", line 696, in urlopen
> > File "urllib3\connectionpool.py", line 964, in _prepare_proxy File "urllib3\connection.py", line 359, in connect File "urllib3\connection.py", line 506, in _connect_tls_proxy File "urllib3\util\ssl_.py", line 432, in ssl_wrap_socket File "urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
> > File "ssl.py", line 423, in wrap_socket
> > File "ssl.py", line 827, in _create
> > ValueError: check_hostname requires server_hostname
> 
> 挂了代理吗，可能是代理的问题

关闭代理后报错
ERROR:pywebio.session.base:Error
Traceback (most recent call last):
  File "pywebio\session\threadbased.py", line 86, in main_task
  File "web.py", line 125, in sms
KeyError: 'titleMsg'

**Comment by Xhofe** [comment]
那可能是触发二次验证了。换用其他的方法吧。。。
