### ISSUE TITLE
希望下方备案信息支持自定义

### ISSUE THREAD

**Issue by LeoWatchDogs** [Xhofe/alist#1040]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

想使用萌国的备案时发现无法自定义超链接，希望可以改成直接填写html的形式或可以自定义超链接路径

**Comment by Xhofe** [comment]
你可以选择不填后台的备案而是直接在自定义body里写html。
