### ISSUE TITLE
对接蓝奏云使用一段时间后，未修改任何东西，原本可用的显示报错

### ISSUE THREAD

**Issue by moshuixins** [Xhofe/alist#1042]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.4.3-0-g6c0d543-dirty

### Describe the bug / 问题描述

对接蓝奏云使用一段时间后，未修改任何东西，原本可用的显示报错，（‎json： 不能将marshal编号解体到Go结构字段中 LanzouLinkResp.url 的字符串类型‎）

### Reproduction / 复现链接

http://121.4.249.153:5244/lanzou2/music.txt

### Logs / 日志

```shell
错误
‎json： 不能将marshal编号解体到Go结构字段中 LanzouLinkResp.url 的字符串类型‎
```

**Comment by Xhofe** [comment]
没发现问题。

**Comment by moshuixins** [comment]
> 没发现问题。

这个链接：http://121.4.249.153:5244/lanzou/music.txt，感觉可能是我账号的问题，用其他账号就没事

**Comment by Xhofe** [comment]
需要账号信息

**Comment by moshuixins** [comment]
> 需要账号信息

我修改一下路径名字，让他重新刷新一下，他又不报错了，看看再用一段时间会不会有问题
