### ISSUE TITLE
希望增加Kindle邮件推送

### ISSUE THREAD

**Issue by xiaoman1221** [Xhofe/alist#1043]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

希望增加Kindle邮件推送

### Suggested solution / 实现思路

后台设置smtp的邮箱，然后把文件推送到用户指定的邮箱（注：必须吧smtp发信的邮箱加入亚马逊白名单）

**Comment by zzy-ac** [comment]
@xiaoman1221 额，你为什么不用kindle浏览器直接访问直链下载到本地？？？

**Comment by zzy-ac** [comment]
@xiaoman1221 或者kindle越狱装上koreader，用koreader的云储存功能挂载alist的webdav进行下载
