### ISSUE TITLE
error:Bad Request:Key: 'RebuildReq.Path' Error:Field validation for 'Path' failed on the 'required' tag

### ISSUE THREAD

**Issue by tidymoon** [Xhofe/alist#105]
如题，rebuild时报错
`Bad Request:Key: 'RebuildReq.Path' Error:Field validation for 'Path' failed on the 'required' tag`

**Comment by Xhofe** [comment]
发/私下地址。

**Comment by tidymoon** [comment]
err，我内网部署的。以下是内网穿透出来的链接（腾讯系对其报毒，用的是别人的二级域名
file.um5.net

**Comment by Xhofe** [comment]
drive名不能为空

**Comment by tidymoon** [comment]
可以了，谢谢！
那我关闭issue喽！

**Comment by tidymoon** [comment]
然后发现控制台输出 css的传输方式不对 导致我这边渲染不了
不过好像就只有我一个人有这个bug
![image](https://user-images.githubusercontent.com/73995927/116811640-ee76f580-ab7c-11eb-9bb7-ae20ed85f4a6.png)
住：环境为windows

**Comment by Xhofe** [comment]
参考 https://blog.csdn.net/celadonbird12/article/details/105937099

**Comment by tidymoon** [comment]
可以了。建议写入文档中
再次感谢！
