### ISSUE TITLE
迅雷云盘报错

### ISSUE THREAD

**Issue by viqbgrg** [Xhofe/alist#1053]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.5.0

### Describe the bug / 问题描述

提示: ErrorCode: 0 ,Error: invalid_argument ,ErrorDescription: x-client-id required
我看到迅雷云盘有更新,是不是有的方式有问题,还是设置除账号密码以外的东西

### Reproduction / 复现链接

https://github.com/Xhofe/alist/commit/11830bb51c0cd4b9fb36aa7283bc0120b2ed794c

**Comment by foxxorcat** [comment]
重新创建一下账号，数据库结构调整了

**Comment by viqbgrg** [comment]
@foxxorcat 我重新添加,保存的时候还是会报ErrorCode: 0 ,Error: invalid_argument ,ErrorDescription: x-client-id required

**Comment by foxxorcat** [comment]
请求逻辑中没把 client-id传好，暂时用旧版本把

**Comment by viqbgrg** [comment]
@foxxorcat 大佬你怎么获取client secret这个值的,我当时为了获取玩客云的这个值,用了frida这个东西,折腾好久才获取,玩客云加固了,我反编译不出来,但是因为曾经反编译过迅雷水晶的代码,知道大概逻辑就hook了一个方法获取到了client secret(好久之前折腾的了,应该就是这个东西,我看长度像,迅雷的东西都是这个逻辑)

**Comment by foxxorcat** [comment]
@viqbgrg 直接用frida抓登录的包，传的参数里面就有

**Comment by viqbgrg** [comment]
@foxxorcat 现在还是不行报
```json
ErrorCode: 4002 ,Error: captcha_invalid ,ErrorDescription: client_id:"我的密码" meta:{key:"result" value:"review"} meta:{key:"username" value:"我的用户名"} result:review
```

**Comment by foxxorcat** [comment]
@viqbgrg 你确定没填错？client_id又不是密码
![IMG_20220509_095912](https://user-images.githubusercontent.com/95907542/167329210-d89bcae1-e7bc-4917-b152-ff317f30f3a1.jpg)
你可以参考一下这个图片

**Comment by viqbgrg** [comment]
@foxxorcat 我搞错了,那个cliend id 不是密码,这个是错误需要验证码吗?

**Comment by viqbgrg** [comment]
已经找到问题了,我不是使用的手机号码登陆的,我使用手机号码登陆就可以了
