### ISSUE TITLE
使用rclone同步和彩云与OneDrive出现OOM的情况

### ISSUE THREAD

**Issue by Soramik** [Xhofe/alist#1072]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.5.1

## 环境与配置说明
ubuntu20.04，amd64
2核2g
rclone版本v1.58.0
alist版本2.5.1

***

## 前言
本人为了将OneDrive的一些文件同步到和彩云上，使用了rclone+alist的方法。（因为rclone的sync命令真的很香）

首先使用rclone配置OneDrive和alist的webdav，然后输入命令：
```bash
rclone sync "od:/XXXXX" "alist:/cloud139/XXXXXX" -P --cache-chunk-total-size=100M --cache-chunk-size=30M --transfers=3
```

需要同步的文件夹大小为19.8g，其中绝大多数为图片（7000多张），以下是od在win10下的同步文件夹属性截图

![image](https://user-images.githubusercontent.com/56548141/167465675-7c1f8769-ba3c-4a54-91ca-6071c89831d1.png)

（由于该文件夹带有一定私密性，请原谅我不予展示）

## 问题描述

前言所述的操作刚开始是正常同步的，大概同步了1个半小时，我发现ssh不上去服务器了，vnc后发现OOM了

![image](https://user-images.githubusercontent.com/56548141/167466758-e38e97e1-6988-4d12-86de-15b2f0fad87b.png)

在OOM之前，rclone的同步命令也是一直提示同步失败，错误代码409
![image](https://user-images.githubusercontent.com/56548141/167468154-7c06f1d1-4860-4a0c-9811-237aee428920.png)

当时我初步诊断为rclone的同步命令参数设置的太高了，于是我重启了alist的服务，并设置`--cache-chunk-total-size=10M`和`--cache-chunk-size=3M`重新跑同步命令

此时的alist内存占用在htop面板下是这样的
![image](https://user-images.githubusercontent.com/56548141/167469776-fe5656bc-7803-4863-bd94-a75c70b2e810.png)

大概过了10几分钟我再去看，发现alist的内存占用极高。
![image](https://user-images.githubusercontent.com/56548141/167472131-fc8d59ec-e67e-415b-abcb-f65803def9f1.png)
我尝试进入网页端手动清理缓存，发现内存并没有降下来，无奈只有重启alist服务，很显然，rclone的同步命令也不得不中止掉。

## 后续补充

再之后，我尝试在我另一台的服务器（ubuntu20.04，1核1g）上跑，这次同步的是一些较大的文件（大部分是日漫视频），rclone的同步命令内存参数也设置的很小，同样出现了类似的情况。
![image](https://user-images.githubusercontent.com/56548141/167472688-02194476-f8e1-4ef6-9139-6c47fa3d6d1b.png)

## 其他补充

我之前也试过rclone只配置alist，然后仅通过alist来进行同步，但是大多数情况下会出现405错误，或者直接找不到文件了。
![image](https://user-images.githubusercontent.com/56548141/167473486-c0ccb101-5460-4870-9089-d766a3039e69.png)
如果rclone配置OneDrive和alist的话这种情况就会大大缓解（不是完全解决，仍然有少数文件会出现这类情况，这时只需要在同步命令执行完成后再执行一次同步命令即可）

### Reproduction / 复现链接

无

**Comment by Soramik** [comment]
补充：在内存快炸了之前，除了409错误外，也有405错误
![image](https://user-images.githubusercontent.com/56548141/167475528-14993758-f9a5-44b6-9304-1c41b216eef4.png)

（上图的界面是byobu）

**Comment by Soramik** [comment]
补充：在内存快炸了之前，除了409错误外，也有405错误
![](https://user-images.githubusercontent.com/56548141/167475528-14993758-f9a5-44b6-9304-1c41b216eef4.png)
（上图的界面是byobu）
且Ctrl+C后经过一段时间内存也没降下来，持续保持着内存高占用。
![image](https://user-images.githubusercontent.com/56548141/167476312-9b390cd4-1653-4f86-8609-d4621fb7841c.png)

**Comment by Soramik** [comment]
[alist-srk.log](https://github.com/Xhofe/alist/files/8654518/alist-srk.log)
补个log文件

**Comment by Soramik** [comment]
[alist-srk.log](https://github.com/Xhofe/alist/files/8654518/alist-srk.log)
补个log文件（nsfw预警）

**Comment by Xhofe** [comment]
需要oom堆栈log

**Comment by Soramik** [comment]
> oom堆栈log

请问要如何获取呢？
网上搜了几种方法都不成功，我也找了log目录下的文件，除了kill的日志，没找到其他相关的日志...
![image](https://user-images.githubusercontent.com/56548141/167652448-ed290d8b-f1c6-47eb-b545-4d579ff40a26.png)
也可能是我这的系统没有输出当时的堆栈日志。
（学艺不精Orz）
