### ISSUE TITLE
迅雷云盘账号出现错误

### ISSUE THREAD

**Issue by 12189108** [Xhofe/alist#1077]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.5.1-0-g0237e78-dirty

### Describe the bug / 问题描述

迅雷账号配置完后出现
ErrorCode: 0 ,Error: invalid_argument ,ErrorDescription: x-client-id required
错误

### Reproduction / 复现链接

https://pan.hamsterrider.top/%E8%BF%85%E9%9B%B7%E7%BD%91%E7%9B%98

**Comment by viqbgrg** [comment]
你试试删除重新添加
