### ISSUE TITLE
挂载阿里云盘，安卓上 下载文件失败

### ISSUE THREAD

**Issue by xoyi** [Xhofe/alist#1099]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

V2.5.1

### Describe the bug / 问题描述

挂载阿里云盘，安卓上 下载文件失败，
ios、电脑都ok，就安卓上下载就失败

### Reproduction / 复现链接

https://alist.nn.ci/China/%E9%98%BF%E9%87%8C%E4%BA%91%E7%9B%98/%E5%85%B6%E4%BB%96/emby_tv_03122020.apk

**Comment by Xhofe** [comment]
浏览器问题，官网也下不了，换浏览器。
