### ISSUE TITLE
能更新下dplayer版本吗

### ISSUE THREAD

**Issue by hyzaw** [Xhofe/alist#11]
2018版本好多bug。。。

**Comment by Xhofe** [comment]
可以的 因为直接使用了封装好的Vue-DPlayer，没有考虑版本。。之后直接使用官方dplayer吧。。

**Comment by 2595133804** [comment]
> 可以的 因为直接使用了封装好的Vue-DPlayer，没有考虑版本。。之后直接使用官方dplayer吧。。

就是说以后会更新是吗

**Comment by Xhofe** [comment]
> > 可以的 因为直接使用了封装好的Vue-DPlayer，没有考虑版本。。之后直接使用官方dplayer吧。。
> 
> 就是说以后会更新是吗

会的 这个比较简单 会尽快。

**Comment by 2595133804** [comment]
> > > 可以的 因为直接使用了封装好的Vue-DPlayer，没有考虑版本。。之后直接使用官方dplayer吧。。
> > 
> > 
> > 就是说以后会更新是吗
> 
> 会的 这个比较简单 会尽快。

我这里看了下，dplayer最新版应该是支持flv在线播放的，可以尝试兼容下吗

**Comment by Xhofe** [comment]
> > > > 可以的 因为直接使用了封装好的Vue-DPlayer，没有考虑版本。。之后直接使用官方dplayer吧。。
> > > 
> > > 
> > > 就是说以后会更新是吗
> > 
> > 
> > 会的 这个比较简单 会尽快。
> 
> 我这里看了下，dplayer最新版应该是支持flv在线播放的，可以尝试兼容下吗

好的 我会看一下

**Comment by Xhofe** [comment]
已添加flv支持
