### ISSUE TITLE
建议在图片、视频文件下方添加一个下载按钮

### ISSUE THREAD

**Issue by Seeger0216** [Xhofe/alist#1102]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

有些视频因为浏览器原因无法在线播放。建议在所有视频下面多加一个下载按钮，现在没有下载按钮，被识别为视频的文件就没法下载了。下载按钮和在播放器中播放平行就可以吧。

### Suggested solution / 实现思路

下载按钮和在播放器中播放的按钮平行，指向当前文件的直链，点击即可下载

**Comment by Seeger0216** [comment]
诶？加个按钮为啥是无效的？？？

**Comment by Liuxiao677** [comment]
右上角有下载按钮

**Comment by Seeger0216** [comment]
> 右上角有下载按钮
感谢，背景颜色太深了，右上角啥也看不见……现在解决了！谢谢

**Comment by anwen-anyi** [comment]
> > 右上角有下载按钮
> 
> 感谢，背景颜色太深了，右上角啥也看不见……现在解决了！谢谢

呃呃呃…你自己改的背景不适配…自己解决吧 又不是没有下载按钮?😒
