### ISSUE TITLE
您好 assets​设置本地后PDF预览所需的js css来自 https://cdn.jsdelivr.net/ 导致无法正常显示

### ISSUE THREAD

**Issue by HCARX** [Xhofe/alist#1109]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.5.2

### Describe the bug / 问题描述

您好 我根据文档设置了assets为本地
但是发现pdf.js viewer.css viewer.js三个文件还是来自其它来源
由于https://cdn.jsdelivr.net/无法正常访问会导致PDF无法预览 请问能否设置本地化

### Reproduction / 复现链接

https://alist.nn.ci/China/%E5%A4%A9%E7%BF%BC%E4%BA%91%E7%9B%98/%E6%B5%8B%E8%AF%95/2010_GuanQF_IJGIS_pRPL.pdf

### Logs / 日志

```shell
https://s1.ax1x.com/2022/05/16/OhPBQA.png
```

**Comment by anwen-anyi** [comment]
昨天  JSD被墙了现在还没恢复貌似`2022年5月17日 10:27:07` 所以没加载出来也正常...

**Comment by HCARX** [comment]
> 

哎 不只是现在 也经常有地区无法加载JSD

**Comment by HCARX** [comment]
> 昨天 JSD被墙了现在还没恢复貌似`2022年5月17日 10:27:07` 所以没加载出来也正常...


哎 不只是现在 也经常有地区无法加载JSD

**Comment by NealScx** [comment]
jsdelivr被墙了 现在logo也加载不出来0.0

**Comment by mmdjiji** [comment]
![QQ截图20220521162844.png](https://s2.loli.net/2022/05/21/M8kQ3ZJXbxIpawq.png)

![QQ截图20220521162914.png](https://s2.loli.net/2022/05/21/AIEsZTt6g8V1ekB.png)
