### ISSUE TITLE
网页中播放多声道视频时，会没有声音

### ISSUE THREAD

**Issue by donething** [Xhofe/alist#1112]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.5.2

### Describe the bug / 问题描述

播放阿里云盘中的视频时，如果视频有多个配音声道，就会没有声音。

网页播放器版本为：ArtPlayer 4.3.1

### Reproduction / 复现链接

如上

**Comment by NealScx** [comment]
同样的问题 
 没有声音 http://alist.nealsky.top/%E9%98%BF%E9%87%8C%E4%BA%91%E7%9B%98/Gone.Girl.2014.1080p.BluRay.Remux.AVC.DTS-HD.MA.7.1-ADE/Gone.Girl.2014.1080p.BluRay.Remux.AVC.DTS-HD.MA.7.1-ADE.mkv
