### ISSUE TITLE
挂载FTP使用的一些奇怪问题

### ISSUE THREAD

**Issue by nitsort** [Xhofe/alist#1117]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.5.2

### Describe the bug / 问题描述

1、WEB在线播放视频时拖动进度条会重头开始播放；
2、在线播放视频时点击下载会一直转圈，无法下载，关掉正在播放的视频就可以下载了；
3、用PotPlayer播放视频会跳跃播放，进度条直接走完了；
演示站貌似没有FTP，不确定是不是FTP程序的问题，用的是FileZilla Server，像是不能多线程？

### Reproduction / 复现链接

内网环境，不好提供

### Logs / 日志

```shell
Alist日志：
[GIN] 2022/05/17 - 23:57:29 | 500 |     45.3822ms |    192.168.50.1 | GET      "/d/Test/Downloads/*****.mp4"
[GIN] 2022/05/17 - 23:57:33 | 500 |    2.2835421s |    192.168.50.1 | GET      "/d/Test/Downloads/*****.mp4"

FTP程序有很多如下日志：
2022-05-17T15:54:27.440Z == [FTP Session 16 192.168.50.100 ***] A command is already being processed. Queuing the new one until the current one is finished.
2022-05-17T15:54:37.020Z << [FTP Session 16 192.168.50.100 ***] 425 Error while transfering data: ECONNABORTED - Connection aborted
```

**Comment by Xhofe** [comment]
不支持多线程 也不支持range。
