### ISSUE TITLE
针对打包下载单独配置中转

### ISSUE THREAD

**Issue by nitsort** [Xhofe/alist#1119]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

目前在用天翼云盘，在下载文件夹或多文件批量下载时必须开启 `web proxy`，不然会因为 `CORS` 而下载失败。
所以针对这类下载能不能配置成走中转，单文件下载不走中转。或者右键下载加个中转的选项。

**Comment by anwen-anyi** [comment]
你是用的Https么?  打包下载不行你可以使用那个推送到Ar2下载啊不用打包了也很方便

**Comment by nitsort** [comment]
> 你是用的Https么? 打包下载不行你可以使用那个推送到Ar2下载啊不用打包了也很方便

Aria2确实可行，不过我不仅仅只是个人使用，所以能直接WEB下载最好了👀

**Comment by anwen-anyi** [comment]
> > 你是用的Https么? 打包下载不行你可以使用那个推送到Ar2下载啊不用打包了也很方便
> 
> 
> 
> Aria2确实可行，不过我不仅仅只是个人使用，所以能直接WEB下载最好了👀

对啊Ar2能下载到你本地吖…跟你个人使用不冲突诶
