### ISSUE TITLE
希望支持vivo云盘和UC网盘

### ISSUE THREAD

**Issue by whws** [Xhofe/alist#1126]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

vivo云盘：https://yun.vivo.com.cn/
UC网盘：https://www.yun.cn/
vivo云盘也是我目前在用的网盘，毕竟是vivo手机。
UC网盘觉得和夸克网盘差不多，也希望大佬能支持该网盘挂载。

**Comment by Xhofe** [comment]
多个feature request 请分开。
