### ISSUE TITLE
转码问题

### ISSUE THREAD

**Issue by 2523955396** [Xhofe/alist#113]
那什么我就是想问问alist的转码是用的哪里的，我想借鉴借鉴

**Comment by Xhofe** [comment]
用的阿里云盘的接口

**Comment by 2523955396** [comment]
有没有教程啊亲




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Xhofe/alist"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月3日(星期四) 晚上6:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Xhofe/alist] 转码问题 (#113)





 
用的阿里云盘的接口

**Comment by Xhofe** [comment]
> 有没有教程啊亲
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "Xhofe/alist"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2021年6月3日(星期四) 晚上6:02
> ***@***.***&gt;;
> ***@***.******@***.***&gt;;
> 主题:&nbsp;Re: [Xhofe/alist] 转码问题 (#113)
> 
> 
> 
> 
> 
>  
> 用的阿里云盘的接口
>  
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

额 这个没有 就抓包看请求
