### ISSUE TITLE
Webdav使用Sharepoint模式挂载的sharePoint站点无法使用proxy功能

### ISSUE THREAD

**Issue by ruanrrn** [Xhofe/alist#1130]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.4-v2.5.2

### Describe the bug / 问题描述

使用cf的worker作为中转代理，无法代理webdav挂载的SharePoint；
如果不使用代理，虽然能挂载上SharePoint（国内大学网盘，没有管理员），不能在线看视频。

### Reproduction / 复现链接

[https://alist.azurewebsites.net/Hubu/%E5%A4%87%E4%BB%BD/PC%E8%BD%AF%E4%BB%B6/rclone-v1.52.3-windows-amd64.zip](url)

### Logs / 日志

```shell
Error 1101 Ray ID: 70ddc1529eeaa132 • 2022-05-19 15:09:42 UTC
Worker threw exception
```

**Comment by Xhofe** [comment]
webdav只能通过本机中转。
