### ISSUE TITLE
预览没有扩展名的文件

### ISSUE THREAD

**Issue by sukanka** [Xhofe/alist#1153]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我的仓库里面有一种文件没有扩展名，但是它们都叫 `PKGBUILD` 本质上是一种 shell 脚本。但是由于没有拓展名，它只能被下载而不能被预览。

### Suggested solution / 实现思路

有两种实现思路，
1. 加一个 特定的文件名也可以被预览。这种思路简单粗暴，但是应该大多数时候都管用。
2. 使用 `file` 指令（我不确定win上是否有类似的指令），如果得到的结果是  `text` 就允许预览（当然，`svg` 也应该允许预览）。下面是一些例子。
```bash
➜  ~ file PKGBUILD 
PKGBUILD: ASCII text
➜  ~ file .gitignore 
.gitignore: ASCII text
➜  ~ file svstudio.svg 
svstudio.svg: SVG Scalable Vector Graphics image
➜  ~ file new.nav new.tex new.toc 
new.nav: LaTeX document, Unicode text, UTF-8 text
new.tex: PostScript document text
new.toc: Unicode text, UTF-8 text
```

### Additional context / 附件

一个示例文件
https://dl.sukanka.com/ms/Linux/ArchLinux/yade/PKGBUILD

**Comment by Xhofe** [comment]
无法实现。

**Comment by Febtw** [comment]
@sukanka 其实已经实现对无扩展名文件的预览。“预览"中各类文件扩展名列表下每一项是用逗号`,`隔开的，因此可用`,a,b`或`a,,b`或`a,b,`格式添加无扩展名的预览。但这种方法并不能识别真实文件类型
