### ISSUE TITLE
当网址带端口时,播放视频存在问题

### ISSUE THREAD

**Issue by piaohong1978** [Xhofe/alist#1159]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

aliyun JS-SDK V1.1.5

### Describe the bug / 问题描述

当网址带端口时,播放视频存在问题:
Docker中运行的,[xhofe/alist](https://hub.docker.com/r/xhofe/alist)

### Reproduction / 复现链接

比如我的站点网址:https://alist.abc.com:4443,我要播放https://alist.abc.com:4443/Share/videoplayback_2.mp4,
结果视频加载不出来,分析网页内容后发现:
<video class="art-video" preload="metadata" playsinline="" src="//alist.abc.com/p/Share/videoplayback_2.mp4?sign=a29834fec34023c3"></video>
其中的src没有带端口号

### Logs / 日志

```shell
比如我的站点网址:https://alist.abc.com:4443,我要播放https://alist.abc.com:4443/Share/videoplayback_2.mp4,
结果视频加载不出来,分析网页内容后发现:
<video class="art-video" preload="metadata" playsinline="" src="//alist.abc.com/p/Share/videoplayback_2.mp4?sign=a29834fec34023c3"></video>
其中的src没有带端口号
```

**Comment by Xhofe** [comment]
反代了？

**Comment by piaohong1978** [comment]
> 反代了？

的确，反代了

**Comment by Xhofe** [comment]
> > 反代了？
> 
> 的确，反代了

反代需要传递正确的host。

**Comment by ferocknew** [comment]
SITE_URL

docker compose 下，这个环境变量有效果
