### ISSUE TITLE
阿里云盘，苹果手机无法在线播放

### ISSUE THREAD

**Issue by yuehun** [Xhofe/alist#1163]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.5.2

### Describe the bug / 问题描述

是因为阿里云盘的问题嘛，同样视频，天翼云正常播放，阿里云盘一直重新连接，安卓手机和电脑也可以正常播放

### Reproduction / 复现链接

如上

**Comment by qinjinman** [comment]
你好，你这个问题解决了吗
