### ISSUE TITLE
新增秒传列表模式

### ISSUE THREAD

**Issue by kedyao** [Xhofe/alist#117]
新增关闭下载跳转和播放页面的开关

按照经验任何网盘分享直链下载 轻则限速 重则封号 
如果直接列表只显示文件名+秒传 就非常适合避免被撸爆

点击列表中的文件就不在跳转文件内容页面 而是点击名称直接复制此文件的秒传链接
同时禁止访问文件内容页面 播放地址 下载地址的链接  避免拼接链接访问
下载按钮隐藏 右键按钮去除下载和直链  保留多选和秒传链接和秒传文件
右键的多选功能在手机端无法实现 求解决

阿里网盘秒传列表展示出现了

**Comment by Xhofe** [comment]
现已无法实现
