### ISSUE TITLE
ERRO Post "https://api.aliyundrive.com/v2/file/get_down

### ISSUE THREAD

**Issue by GJG666** [Xhofe/alist#1171]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.0-0-gc35d54d-dirty

### Describe the bug / 问题描述

图一：
![图一](https://user-images.githubusercontent.com/36781028/170852863-37c6a18a-6bc0-474d-ba32-5879772660f9.png)
后台具体的错误如图一所示。
图二：
![图二](https://user-images.githubusercontent.com/36781028/170853336-075f1da0-2df7-417d-8eb0-0b429c4bae69.jpg)
图三：
![图三](https://user-images.githubusercontent.com/36781028/170853318-3083cfe2-863d-4e0d-abaf-b20220b99503.jpg)

个人使用环境：我是用alist搭了阿里云盘的列表，然后批量提取阿里云盘中文件的直链，推到Aria2进行下载。
下载大概一两个小时(数据量的话大概下载七八十G到一百多G的样子，但猜测应该跟下载的数据量没有太大关系，我开通了阿里的超级会员，也不会受到什么每天下载量限制之类的)，后台就基本会出现这个api错误，然后alist一直处于转圈状态如图二所示，无法刷新目录也无法操作任何东西。无响应一段时间后就提示图三的错误。

后台重启Alist后，该错误会短暂时间内解决，然后继续下载一段时间(因为主要时间都是处于下载状态，所以我不清楚不做任何操作时，会不会也出现这个问题)，就又会出现。

PS：
     1、目前这种错误仅出现在阿里云盘的alist列表中，其他网盘未碰到。而且这个错误在我这儿出现的很频繁，但好像又没怎么从其他人哪里听到过。
     2、我是用的官方指南上的一键搭建命令搭的alist，用了域名，添加了证书，加了反向代理，这些应该跟上面的错误都无关紧要。
     3、下面的那个复现链接我是随便贴的，因为根具体哪个链接无关。

### Reproduction / 复现链接

https://alist.gjg123.xyz/%E7%88%B7%E9%9D%92%E5%9B%9E%E5%8A%A8%E7%94%BB/1%E3%80%81%E8%B6%85%E6%97%B6%E7%A9%BA%E8%A6%81%E5%A1%9E

### Logs / 日志

```shell
May 28 21:38:00 vps50053270 alist[2616]: ERRO[2022-05-28 21:38:00] Post "https://api.aliyundrive.com/v2/file/get_down
May 28 21:38:00 vps50053270 alist[2616]: [GIN] 2022/05/28 - 21:38:00 | 200 |         1m21s |     5.255.97.77 | GET   
May 28 21:38:01 vps50053270 alist[2616]: 2022/05/28 21:38:01.579488 ERROR RESTY Post "https://api.aliyundrive.com/v2/
May 28 21:38:02 vps50053270 alist[2616]: 2022/05/28 21:38:02.109243 ERROR RESTY Post "https://api.aliyundrive.com/v2/
May 28 21:38:03 vps50053270 alist[2616]: 2022/05/28 21:38:03.315911 ERROR RESTY Post "https://api.aliyundrive.com/v2/
May 28 21:38:05 vps50053270 alist[2616]: 2022/05/28 21:38:05.082978 ERROR RESTY Post "https://api.aliyundrive.com/v2/
May 28 21:38:06 vps50053270 alist[2616]: 2022/05/28 21:38:06.351252 ERROR RESTY Post "https://api.aliyundrive.com/v2/
May 28 21:38:06 vps50053270 alist[2616]: ERRO[2022-05-28 21:38:06] Post "https://api.aliyundrive.com/v2/file/list": c
May 28 21:38:06 vps50053270 alist[2616]: [GIN] 2022/05/28 - 21:38:06 | 200 |         1m20s |  101.229.163.82 | POST  
May 28 21:38:10 vps50053270 alist[2616]: 2022/05/28 21:38:10.928104 ERROR RESTY Post "https://api.aliyundrive.com/v2/
```

**Comment by Xhofe** [comment]
https://alist-doc.nn.ci/docs/common-question#tls-handshake-timeout--read-connection-reset-by-peer--dns-lookup-failed--connect-connection-refused

国外vps超时很正常。
