### ISSUE TITLE
123云盘显示文件code500

### ISSUE THREAD

**Issue by aoaoemoji** [Xhofe/alist#1190]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.6.0-0-gc35d54d-dirty

### Describe the bug / 问题描述

{"code":500,"message":"123pan rate limit type min","data":null}
文件已经确保存在

### Reproduction / 复现链接

https://dl.fiime.cn/d/FiimeROM/FiimeROM/%E5%B0%8F%E7%B1%B310%E7%B1%BB%E5%8E%9F%E7%94%9F-%E5%AE%89%E5%8D%9311/PixelExperience_umi-12.0-20211217-1949-UNOFFICIAL.zip

### Logs / 日志

```shell
{"code":500,"message":"123pan rate limit type min","data":null}
```

**Comment by Xhofe** [comment]
超限了
