### ISSUE TITLE
无法获取正确的直链

### ISSUE THREAD

**Issue by L1cardo** [Xhofe/alist#123]
目前我的目录为 /licardo
如果获取直链会变成/d/licardo
然后要求我重构
重构提示无法找到driver[d]

这是我的配置文件
![F9AA8224-D79B-416F-9C28-8F30E413780D](https://user-images.githubusercontent.com/33802186/127728802-7219477f-a899-4377-b56d-5ec20e778eec.jpeg)

**Comment by L1cardo** [comment]
是用的是这个docker镜像
https://hub.docker.com/r/sbwml/alist   知道是不是这个镜像的问题

**Comment by L1cardo** [comment]
已确认为是docker的问题，麻烦老哥你看下 @sbwml

**Comment by sbwml** [comment]
> 已确认为是docker的问题，麻烦老哥你看下 @sbwml

你的问题与是否使用 docker无关，/d/ 意为文件下载操作，至于无法正常下载个人建议你看一下作者博客配置示例或项目内 conf.yml.example

**Comment by L1cardo** [comment]
同一个配置文件，使用原作者的就不会有这个问题，而使用Docker就会出现。

**Comment by sbwml** [comment]
> 同一个配置文件，使用原作者的就不会有这个问题，而使用Docker就会出现。

alist 只有当前项目一个版本，不管用什么方式运行它并不会改变原本的性质。你的问题我只能建议你检查配置文件是否给予了下载权限。
