### ISSUE TITLE
挂载阿里盘，视频只能转码播放，原画质提示加载失败，f12调试，貌似是跨域403错误

### ISSUE THREAD

**Issue by hostemail** [Xhofe/alist#126]
挂载阿里盘，视频只能转码播放，取消转码选项原画质播放，提示加载失败。f12调试，貌似是跨域403错误

Request URL: https://bj29.cn-beijing.data.alicloudccp.com/ypG1ILR4%2F8620624%2F6071763dcb1915368ae24491bf54a6c20693e47e%2F6071763d299672f047b6428bbf735e5aace219d3?di=bj29&dr=77932731&f=610fbee7dec436e168454c2eb7ec1123a683f709&response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%2713.mp4&u=b34813e6dc7149cb815bfafaeea7a24f&x-oss-access-key-id=LTAIsE5mAn2F493Q&x-oss-additional-headers=referer&x-oss-expires=1628861738&x-oss-signature=TmEpUMtyTGIUCc6coZlTyaLPr3r5AC6K7dzYoUkbKJ8%3D&x-oss-signature-version=OSS2
Request Method: GET
Status Code: 403 Forbidden
Remote Address: 111.13.119.5:443

访问其他文件，如文档这些，均报错。
Referrer Policy: no-referrer

**Comment by hostemail** [comment]
除了视频，采用转码可播放，其他任何文件，文档，图片，都均不能访问，都是报403 Forbidden，请问有什么办法可以解决吗？ 尝试过各种关于web服务器的跨域的配置，均也不行。如：
        header_up Host {http.reverse_proxy.upstream.hostport}
        header_down Access-Control-Allow-Headers *
        header_down Access-Control-Allow-Origin *

**Comment by Xhofe** [comment]
参考 #88

**Comment by Xhofe** [comment]
以及
https://www.nn.ci/archives/alist.html#toc_10

**Comment by hostemail** [comment]
多谢大佬，换toker后，原画质视频有的能播放了，有的是黑屏，只有声音，不知道这视频格式问题，还是其他问题？都是mp4格式

**Comment by hostemail** [comment]
还发现一个小问题，预览txt文本文件时，如果内容里有{{"DirList..} 大括号等特殊字符的话，预览报错：“[object Object]”

**Comment by Xhofe** [comment]
> 多谢大佬，换toker后，原画质视频有的能播放了，有的是黑屏，只有声音，不知道这视频格式问题，还是其他问题？都是mp4格式

视频编码的原因

**Comment by zbzzh** [comment]
同问题，没有解决
