### ISSUE TITLE
关于密码和搜索

### ISSUE THREAD

**Issue by lisuqi1** [Xhofe/alist#128]
在有了密码之后不能搜索，按照博客里说的方法更改后所以文件都能不需要密码被搜索出来，就失去了密码的意义。能否加上能够实现搜索，但是打开文件需要当前文件夹的密码，或者单纯的搜索只需要一个全局的密码之类的。

**Comment by Xhofe** [comment]
按照博客改完之后就是

> 能够实现搜索，但是打开文件需要当前文件夹的密码

这种效果的，输入密码之后会存储在localStorage，你可以开个无痕试试。

**Comment by hugo-on** [comment]
@Xhofe 刚发现密码明文存储在localStorage，且注销登录后不会自动清除，这样会留下安全隐患吧。个人觉得密码明文存储在cookie中不是一个明智之举，比如在另一台电脑上临时登录，即使不勾选记住登录，密码也会在注销后留在该计算机上，这时如果服务器以root身份运行的alist，密码泄露后后果可想而知。个人建议取消密码存储在本地或加密后存储，或至少在注销登录时将其清除掉。
