### ISSUE TITLE
部署在Heroku上频繁需要重构目录。

### ISSUE THREAD

**Issue by CryZJ** [Xhofe/alist#129]
重构目录后正常使用一段时间后即再次提示需要重构。

**Comment by xiaokaixuan** [comment]
Heroku 半小时不活跃就销毁了。。。

**Comment by CryZJ** [comment]
> Heroku 半小时不活跃就销毁了。。。
原来如此。

**Comment by CryZJ** [comment]
> Heroku 半小时不活跃就销毁了。。。

其他的网盘列表部署在heroku上不存在这种情况，是因为重构目录是在本地创建缓存文件吗？

**Comment by xiaokaixuan** [comment]
> > Heroku 半小时不活跃就销毁了。。。
> 
> 其他的网盘列表部署在heroku上不存在这种情况，是因为重构目录是在本地创建缓存文件吗？

是的
