### ISSUE TITLE
rebuild半天都在转圈

### ISSUE THREAD

**Issue by gimgoo** [Xhofe/alist#132]
如标题，rebuild半天都在转圈，然后刷新再rebuild就说数据库锁了，按照以往issue删了db文件，再rebuild也是转半天，没一点反应，刷新页面就会出来文件夹，但是里面什么都没有，无论层级是默认的3还是-1。

作者是不是要考虑下这个rebuild的过程哪里有问题？要rebuild那么久

**Comment by Xhofe** [comment]
尝试一下新的版本～
