### ISSUE TITLE
网页中的超链接无法使用直链下载

### ISSUE THREAD

**Issue by 404gods** [Xhofe/alist#138]
部署了正式版和开发版都发现一个问题，alist面板里下载正常，复制直链地址到浏览器地址栏下载也正常。
就是把直链做成超链接放在网页里点击就会出现错误提示如下图：
网页使用反向代理，排除了CDN和本地缓存的问题。如果超链接不使用反向代理域名的直链而使用IP+端口的直链，则能够在网页中点击正常下载。
![photo](https://user-images.githubusercontent.com/50573302/131492037-c5c3c6d9-495f-4924-b45e-0eedf0a9307a.jpg)

**Comment by Xhofe** [comment]
参考：https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy
示例：
<a href="https://api.xhofe.top/alist/d/my/logo.jpg" referrerpolicy="no-referrer">1</a>
<a href="https://api.xhofe.top/alist/d/my/logo.jpg" rel="noreferrer">2</a>
```html
<a href="https://api.xhofe.top/alist/d/my/logo.jpg" referrerpolicy="no-referrer">1</a>
<a href="https://api.xhofe.top/alist/d/my/logo.jpg" rel="noreferrer">2</a>
```

**Comment by 404gods** [comment]
按方法果然解决了，谢谢~

**Comment by cancundeyingzi** [comment]
> 按方法果然解决了，谢谢~

这是啥原理啊，是啥问题导致的，想了解一下

**Comment by duskNNNN** [comment]
因为解密后的直链其实是在变化的，但如果通过alist的url解密，相当于动态不变

**Comment by sfdzkj** [comment]
WordPress使用erphpdown插件  也是这个问题， 不知道怎么解决，希望哪位大佬能指导下

**Comment by 404gods** [comment]
> WordPress使用erphpdown插件 也是这个问题， 不知道怎么解决，希望哪位大佬能指导下

已经解决了啊，上面不是作者已经答复了嘛
像下面这样添加链接就行了：
<a href="https://api.xhofe.top/alist/d/my/logo.jpg" referrerpolicy="no-referrer">1</a>
<a href="https://api.xhofe.top/alist/d/my/logo.jpg" rel="noreferrer">2</a>

**Comment by sfdzkj** [comment]
> ```
>  rel="noreferrer"
> ```
erphpdown插件  点击下载 连接
/wp-content/plugins/erphpdown/downloadfile.php?id=714&filename=3&index=&md5key=1111111&times=1659721091&session_name=222222
隐藏了真实的下载地址。


	if($arrlength >= 2){
							$downMsg.="<p><span class='tit'>".$filearr[0]."</span><a href='download.php?postid=".$postid."&key=".($k+1)."&index=".$index."' target='_blank' class='link erphpdown-down-btn' data-clipboard-text='".trim($filearr3[1])."' rel='noreferrer'>点击下载</a>".$filearr3[0].": <span class='erphpdown-code'>".trim($filearr3[1])."</span><a class='erphpdown-copy' data-clipboard-text='".trim($filearr3[1])."' href='javascript:;'>复制</a></p>";
						}

添加后也无效
