### ISSUE TITLE
老大你好，配置文件可以加统计代码吗？

### ISSUE THREAD

**Issue by vbskycn** [Xhofe/alist#14]
老大你好，配置文件可以加统计代码吗？比如51.la的代码
我加在  script: ""  里面会报错，运行不起来

**Comment by Xhofe** [comment]
应该是可以的啊 注意不需要script标签，而且注意yaml文件的格式 建议放在文件里 然后填文件的链接

**Comment by vbskycn** [comment]
<script type="text/javascript" src="https://js.users.51.la/21037108.js"&gt;</script&gt;
有点不太懂，能详细指点下吗？
是不是把上面的代码存为一个js文件
然后在&nbsp; 配置文件里这样写吗？&nbsp; script: "https://***/tj.js"
但是好像没有作用
能否给个范例
谢谢啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "微凉"<notifications@github.com&gt;; 
发送时间: 2021年1月12日(星期二) 晚上9:15
收件人: "Xhofe/alist"<alist@noreply.github.com&gt;; 
抄送: "开心每一天"<88164962@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Xhofe/alist] 老大你好，配置文件可以加统计代码吗？ (#14)





 
应该是可以的啊 注意不需要script标签，而且注意yaml文件的格式 建议放在文件里 然后填文件的链接

**Comment by Xhofe** [comment]
> <script type="text/javascript" src="[https://js.users.51.la/21037108.js"&gt;</script&gt](https://js.users.51.la/21037108.js%22&gt;</script&gt); 有点不太懂，能详细指点下吗？ 是不是把上面的代码存为一个js文件 然后在&nbsp; 配置文件里这样写吗？&nbsp; script: "https://***/tj.js" 但是好像没有作用 能否给个范例 谢谢啦
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "微凉"<notifications@github.com&gt;; 发送时间: 2021年1月12日(星期二) 晚上9:15 收件人: "Xhofe/alist"<alist@noreply.github.com&gt;; 抄送: "开心每一天"<88164962@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [Xhofe/alist] 老大你好，配置文件可以加统计代码吗？ (#14) 应该是可以的啊 注意不需要script标签，而且注意yaml文件的格式 建议放在文件里 然后填文件的链接 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

直接填你src后面的那个地址就可以了

**Comment by vbskycn** [comment]
好的，非常感谢，之前这样写过没有作用，原来是被我的浏览器给拦截了
