### ISSUE TITLE
偶然发现的无法下载问题！！

### ISSUE THREAD

**Issue by 2217092594** [Xhofe/alist#143]
偶然间发现的，
经过多方面验证发现小米手机自带的下载器不可以下载东西，看视频可以（目前只在多方面测试了看视频，其他的没有试，下载方面只测试了apk和jpg这两个），同样不能下载的还有手机版的edge，以及微信。
可以下载的经过测试的有华为手机自带的浏览器，夸克浏览器，qq，其他的没有测试

**Comment by ys0722** [comment]
自用小米手机 浏览器下载apk文件没有问题

**Comment by zsbai** [comment]
我也有遇到，小米手机自带浏览器回显示下载失败

**Comment by Xhofe** [comment]
所有都是302到直链。
