### ISSUE TITLE
重建目录报错

### ISSUE THREAD

**Issue by 12123ads** [Xhofe/alist#146]
Releases，docker，一键脚本部署都试过了，报错都一样
ERRO[2021-09-25 16:05:55] 解析json[]出错:unexpected end of JSON input

**Comment by w311ang** [comment]
+1

**Comment by 7yan** [comment]
+1

**Comment by 2523955396** [comment]
+1

**Comment by w311ang** [comment]
暂时办法就是将深度改成1，需要什么文件夹去文件夹里重建目录

**Comment by 2523955396** [comment]
这样的话文件多了那不是挨着挨着重建

**Comment by 2523955396** [comment]
治标不治本啊

**Comment by w311ang** [comment]
你一下也不会用到那么多文件夹吧，反正用什么重建什么也可以

limingbaizhou ***@***.***> 于 2021年9月27日周一 下午12:53写道：

**Comment by 2523955396** [comment]
以后就多了噻

**Comment by Xhofe** [comment]
已更新v2
