### ISSUE TITLE
0.15配置文件报错

### ISSUE THREAD

**Issue by zsbai** [Xhofe/alist#15]
配置文件preview那一段加上就会报错 
加载配置文件时发生错误:yaml: line 9: did not find expected key 
ERRO[2021-01-12 21:19:45] 读取配置文件时出现错误,启动失败.
必须手动删掉
前端后端均已更新至0.15

**Comment by Xhofe** [comment]
> 配置文件preview那一段加上就会报错
> 加载配置文件时发生错误:yaml: line 9: did not find expected key
> ERRO[2021-01-12 21:19:45] 读取配置文件时出现错误,启动失败.
> 必须手动删掉
> 前端后端均已更新至0.15

注意格式问题，yaml文件的格式要求挺严格的，或者私我配置文件帮忙看

**Comment by zsbai** [comment]
😅不好意思，可能是因为我复制粘贴的问题，我是直接复制example到旧版粘贴的，启动后手动在配置文件里补上这几行就没问题了
