### ISSUE TITLE
新版本IINA调用无法播放

### ISSUE THREAD

**Issue by AttempBLT** [Xhofe/alist#150]
试用了V2.0新版本，发现以下三个问题：
1、部分视频因为无法转码，导致无法播放画面，只有声音
2、调用IINA提示无法打开文件或流
3、IP访问alist时，无法使用有上交复制按钮

**Comment by Xhofe** [comment]
https://github.com/Xhofe/alist-web/commit/d2f17c8251d3d357706a2f5e7df37d34fd2a9174
