### ISSUE TITLE
Bug和建议

### ISSUE THREAD

**Issue by suyin-long** [Xhofe/alist#153]
## Bug
alist会同步出来一些我阿里云盘不存在的文件，如图：
![bug](https://user-images.githubusercontent.com/49554285/140716531-52929c1d-700e-4a95-aaa4-59932c79ea2f.png)
## 建议
1. 目录链接可以采用短链接，不然给别人分享的时候链接太长了，如：
```
https://suyin.shop/%E5%AD%A6%E4%B9%A0%E8%B5%84%E6%96%99/%E5%8D%83%E5%B3%B0%E5%9F%B9%E8%AE%AD%E8%B5%84%E6%96%99/Python%E8%AF%BE%E4%BB%B6/step1/day08
```
采用短链接后分享就感觉好很多，如：
```
https://suyin-blog.club/2020/12XB957/
```
具体做法可以使用类似的：用base32和crc32算术，按文件名自动生成，然后前边跟上文件的创建年份如：https://domain/year/12XB957
2. 添加搜索功能，文件多的时候查找起来不方便，比如：我的网盘里有上千的文件，还在不同的目录，自己用还知道大概在那个目录，如果是别人用，根本找不到在哪。

**Comment by Xhofe** [comment]
手机备份不是bug，可以自行隐藏
1.不考虑 可以自己创建短链接
2.阿里的搜索API拿不到路径，只能递归获取。本地只有部分缓存也无法实现搜索
