### ISSUE TITLE
mysql setting_items查询语句key没有转义导致报错

### ISSUE THREAD

**Issue by teble** [Xhofe/alist#154]
```
Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key = ? ORDER BY `x_setting_items`.`key` LIMIT 1' at line 1
```
在生成的sql中主键key在查询时`key = ?`这一步没有进行转义，导致manager页面所有api请求全部500
![image](https://user-images.githubusercontent.com/33313113/140898680-653a8efa-3d99-4555-8c54-ba22f622402a.png)

**Comment by Xhofe** [comment]
db7bff2d6115e96c73c92322c4c0f1edb905c24c

**Comment by teble** [comment]
> [db7bff2](https://github.com/Xhofe/alist/commit/db7bff2d6115e96c73c92322c4c0f1edb905c24c)

刚刚翻了一下，源码，看到了
