### ISSUE TITLE
播放视频可否自动开始

### ISSUE THREAD

**Issue by vbskycn** [Xhofe/alist#156]
功能建议：
播放视频可否自动开始，而不用自己再点下
每个人的需求不同，在后台设置个开关也好

**Comment by Xhofe** [comment]
e902c2ded7bc46f240c4c86e107164810cfca23a

**Comment by vbskycn** [comment]
这个是用docker部署的能改吗？改哪里呀，
还有用 docker部署，要映射哪个目录，才能把设置的数据库保留下来呢？

**Comment by Xhofe** [comment]
v2.0.0-beta5之后在后台设置，且与之前的数据不兼容需要重新部署。
docker映射目录：`docker run -d --restart=always -v /etc/alist:/opt/alist/data -p 5244:5244 --name="alist" xhofe/alist:v2`

**Comment by vbskycn** [comment]
感谢回复，已经在首页找到了最新的说明文档
