### ISSUE TITLE
父级文件夹设置密码，子文件夹不单独设置密码，可以不受限制直接访问子文件夹（存在暴力扫描泄漏风险）

### ISSUE THREAD

**Issue by teble** [Xhofe/alist#157]
如果按照目前方式进行加密，如果文件夹数量比较多，需要对每个文件夹单独配置，否则就存在暴力扫描到子路径，从而泄漏文件的风险。
建议文件夹加密钥是包括子路径的，如果子路径单独设置密码应当优先级更高。
或者采用通配符方式进行是否需要密钥的匹配，但是这样就不太合适配置隐藏文件。

**Comment by Xhofe** [comment]
959ef620fbb7b715d15439179a8986c825f4eafc
