### ISSUE TITLE
定时清除缓存的方法

### ISSUE THREAD

**Issue by hugoyue** [Xhofe/alist#158]
如果不想手动清空缓存可以使用api来创建定时任务进行清除，方法如下：

1、获取 Authorization 授权码

登录alist管理页面，F12 点击 login 在 Request Header 可以找到 Authorization 

![QQ截图20211115165119.jpg](https://i.loli.net/2021/11/15/kE6K1lQ8LyP3Bfo.jpg)

2、建立定时任务通过 curl 来定时请求 api，格式如下：

curl -H 'Content-Type: application/json' -H "Authorization:17da0c4ed123456783d5ba50ab217a61" http://yourdomain/api/admin/clear_cache

**Comment by Xhofe** [comment]
额，缓存本来就是会定时清除的啊。。。😵

**Comment by hugoyue** [comment]
> 额，缓存本来就是会定时清除的啊。。。😵

啊～原来是这样。。。。有时打开是一片空白以为还要手动。
那我关闭了。
