### ISSUE TITLE
删除目录报错，docker版反代不成功，手动部署的没有天翼网盘

### ISSUE THREAD

**Issue by vbskycn** [Xhofe/alist#159]
1.删除目录报错，报错如下
WHERE conditions required
![](https://mapp.alicdn.com/1636985801870K3F62pkGQKgvI1T.png)

2.docker版https反代不成功，一片白，一直显示  loading

3.直接手动部署的没有天翼网盘,docker版有，https反代OK

**Comment by Xhofe** [comment]
1. beta5之后与之前不兼容
2. 程序无关问题
3. 天翼网盘没有release

**Comment by xingkong0113** [comment]
各位大大，docker部署浏览器打开后空白页怎么解决呢？
