### ISSUE TITLE
视频加载失败

### ISSUE THREAD

**Issue by GH6324** [Xhofe/alist#16]
更新至v0.1.5后视频加载失败了，包括您的demo网站也是加载失败
![视频加载失败](https://gejiba.com/view.php/16ae2cc74e3a39d0e1a7b43a89b68c7d.png)

**Comment by Xhofe** [comment]
很抱歉 ，由于阿里云盘加入了防盗链机制，目前所有不走服务器的预览均已失效，暂时还没有好的解决办法，只能下载。

**Comment by GH6324** [comment]
> 很抱歉 ，由于阿里云盘加入了防盗链机制，目前所有不走服务器的预览均已失效，暂时还没有好的解决办法，只能下载。

好的，谢谢您

**Comment by YujiaCheng1996** [comment]
Referer验证了，凉了啊，怎么搞？
有没有可能：
1.只列不预览
2.后端反代/下载缓存

**Comment by Xhofe** [comment]
> Referer验证了，凉了啊，怎么搞？
> 有没有可能：
> 1.只列不预览
> 2.后端反代/下载缓存

如果后续官方不支持设置Referer白名单/解决不了Referer验证的话，我的设想是像图片/文本/代码这种小文件走服务器代理预览，视频这种大文件只能下载观看了。

**Comment by Xhofe** [comment]
或者有更好的方式的话 欢迎提出。

**Comment by vbskycn** [comment]
下载也报错呀
[https://p.pstatp.com/origin/137bc000309a664264e0e](url)

**Comment by vbskycn** [comment]
![https://p.pstatp.com/origin/137bc000309a664264e0e]

**Comment by Xhofe** [comment]
先使用复制直链下载吧 

> 下载也报错呀
> 图片： https://p.pstatp.com/origin/137bc000309a664264e0e

先使用复制直链下载吧，直接点击下载因为是从列表页面跳转也会携带Referer头，所以会被防盗链机制拒绝。所以只能复制链接到新窗口手动打开。

**Comment by Xhofe** [comment]
额，官方好像又将防盗链去掉了 。。不知道想干什么

**Comment by JsonSong89** [comment]
```
server {
    listen 7091;
	#server_name wt.jsonsong.com wt.jsonsong.win;
	location /proxyimg/
	{
		set $schemex "";
		set $hostx "";
		set $addrs "";
		if ( $uri ~ "^/proxyimg/(http|https)./+([^/]+)/(.+)$") {
			set $schemex $1;
			set $hostx $2;
			set $addrs $3;
		}

		resolver 8.8.8.8 valid=3600s;
		proxy_pass $schemex://$hostx/$addrs;
		proxy_set_header referer "$schemex://$hostx";
	}
}
```

如果用nginx转一遍估计可以,但绝对是下策,本来就是指望着阿里的大带宽.
阿里还是没有微软厚道啊.

**Comment by yanquan2020** [comment]
3.6.0最新版本的，也还是出现了视频加载失败，有什么解决办法吗？还是有设置注意细节？
![image](https://user-images.githubusercontent.com/82320797/208113202-c8eabf6f-4d65-44ac-b489-b4d21dbc8532.png)

PS：无论是阿里云盘挂载还是阿里云盘链接挂载。
