### ISSUE TITLE
/d /p直链，不会受到password的影响，依旧存在文件泄漏可能

### ISSUE THREAD

**Issue by teble** [Xhofe/alist#160]
同#157 
目前仅对web页面的api进行了限制，但是对于直链/代理链接，依旧可以越权访问
可以考虑增加query参数的方式传递密钥，如果请求不存在密钥或者密钥错误重定向至输入密钥页面
如果是http其实还是相当于裸奔（有条件的最好还是上个https），但是至少免除了暴力扫描泄漏文件的可能

**Comment by Tiny-Wei** [comment]
任存在未授权访问。

**Comment by Tiny-Wei** [comment]
似乎任存在未授权访问。
