### ISSUE TITLE
怎么从源码构建Win二进制版本

### ISSUE THREAD

**Issue by Nanhumly** [Xhofe/alist#164]
大佬你好
我想修改首页代码增加些东西
请问如何从源码构建Win二进制版本
非常感谢

**Comment by Xhofe** [comment]
只提供Linux构建脚本，你可以参照[build.sh](https://github.com/Xhofe/alist/blob/5db1ad4adf66cfc9f2e012d9ec6fc154cd8aaa49/build.sh)使用交叉编译，或参照[.github/workflows/build.yml](https://github.com/Xhofe/alist/blob/5db1ad4adf66cfc9f2e012d9ec6fc154cd8aaa49/.github/workflows/build.yml)使用GitHub actions进行自动构建。

**Comment by Nanhumly** [comment]
好的感谢大佬百忙中抽空回复
