### ISSUE TITLE
希望增加在线上传文件和在线编辑README文件的功能

### ISSUE THREAD

**Issue by suyin-long** [Xhofe/alist#166]
## 建议
希望增加在线上传文件和在线编辑README文件的功能！
![2021-11-21_002250](https://user-images.githubusercontent.com/49554285/142733608-1e3355a7-43b1-4669-ace3-da9c18dd7321.png)

**Comment by Xhofe** [comment]
不考虑

**Comment by Xhofe** [comment]
不考虑
