### ISSUE TITLE
OneDrive网盘根目录路径

### ISSUE THREAD

**Issue by AttempBLT** [Xhofe/alist#167]
在OneDrive网盘时，最后一项根目录路径如何指定到网盘中某一文件夹？
文件夹地址为：
https://onedrive.live.com/?id=4D8xxx176xxx5EF%2x5x21&cid=4D8xxx176xxx5EF
请问应该填写哪一部分？

**Comment by Xhofe** [comment]
就填路径就行，从根路径开始，和本地路径一样，比如`/test`

**Comment by AttempBLT** [comment]
填写/test路径后，仍然显示onedrive根目录下全部文件夹。

**Comment by Xhofe** [comment]
默认有一小时缓存，后台右上角可以清除缓存

**Comment by AttempBLT** [comment]
问题解决，谢谢！
