### ISSUE TITLE
189云盘 长时间未打开再重新打开时出现ltTextArr = 0错误

### ISSUE THREAD

**Issue by a330209159** [Xhofe/alist#169]
如题
看程序是错误是在189.go中触发的
```
	ltText := regexp.MustCompile(`lt = "(.+?)"`)
	ltTextArr := ltText.FindStringSubmatch(b)
	if len(ltTextArr) > 0 {
		lt = ltTextArr[1]
	} else {
		return fmt.Errorf("ltTextArr = 0")
	}
```

**Comment by a330209159** [comment]
出现错误返回后，第二次再次打开错误消失。

**Comment by Xhofe** [comment]
并不是bug 只是有时候服务器请与天翼云盘的通讯有问题（也可能是天翼云盘抽风）导致请求到的数据为空，刷新一下就好。

**Comment by a330209159** [comment]
> 并不是bug 只是有时候服务器请与天翼云盘的通讯有问题（也可能是天翼云盘抽风）导致获取到的登录页面内容为空，刷新一下就好。

谢谢回复，是否可以添加一种轮询机制？若出现网络波动自动重复请求一次，三次都失败再返回此错误

**Comment by Xhofe** [comment]
可以 之后加一下

**Comment by a330209159** [comment]
错误
get empty login page
更新之后 今天又遇到了两次，也是刷新一下就好，似乎导致问题的关键不在这

**Comment by a330209159** [comment]
> 可以 之后加一下

今天又出现了。刚更新的时候，进度条转几秒可以进去，现在是转圈完就直接报错了。
              错误
get empty login page
           |返回首页|
所以我感觉问题的关键还是不在之前修改的那一段代码。 @ @Xhofe

**Comment by Xhofe** [comment]
> 错误 get empty login page 更新之后 今天又遇到了两次，也是刷新一下就好，似乎导致问题的关键不在这 问一下作者自己有没有遇到过这个问题？我是部署在本地家里的虚拟机上，移动宽带，应该不是网络问题导致的，是否跟ipv6有关呢

我自己并没有遇到过这个问题，而且也不太好复现这个问题。
