### ISSUE TITLE
直接点下载按钮提示  You are denied by bucket referer policy.

### ISSUE THREAD

**Issue by yushangcl** [Xhofe/alist#17]
下载提示
```
<Error>
<Code>AccessDenied</Code>
<Message>You are denied by bucket referer policy.</Message>
<RequestId>5FFED4996921CF333453F5EC</RequestId>
<HostId>bj29.cn-beijing.data.alicloudccp.com</HostId>
<BucketName>ccp-bj29-bj-1592982087</BucketName>
</Error>
```

但是 可以复制直连下载

**Comment by Xhofe** [comment]
因为下午的时候官方引入了防盗链，会检测`Referer`头。复制直链新窗口打开则不会携带Referer

**Comment by Xhofe** [comment]
测试在html文件头中加入<meta name="referrer" content="never">，好像可以去掉referer头避开防盗链检测，后续未知。可以尝试一下

**Comment by yushangcl** [comment]
好的，先试试

**Comment by zsbai** [comment]
实测有效，视频也可以正常播放了

**Comment by zhujitop** [comment]
`<meta name="referrer" content="never">`

加到网盘程序头部还是会出现这种被拒绝的情况。
如果打开web proxy之后，能正常一段时间，一段时间又不行了，得切换成默认方式下载。
就是两种方式来回切换，是操作方式不对吗？
