### ISSUE TITLE
后台密码进不去

### ISSUE THREAD

**Issue by rongzhijie7** [Xhofe/alist#172]
默认密码alist，极少数情况能进去，后面再进就不行了
改了密码之后，无论输入alist还是自己的密码也都登不进去，反复提示密码错误。

**Comment by Xhofe** [comment]
没碰到过。。。

**Comment by Xhofe** [comment]
命令行加-password可以查看当前的密码。

**Comment by rongzhijie7** [comment]
> 



> 命令行加-password可以查看当前的密码。

我用的一键部署，命令行怎么用呢

**Comment by Xhofe** [comment]
/opt/alist 下

**Comment by rongzhijie7** [comment]
我好像知道是怎么回事了。
我是用Oracle的免费实例建的alist，他家默认不给root权限，需要把alist目录和下面文件的权限都改成777，然后再把用户改成www，然后就搞定了。
我是用宝塔面板进去修改的权限，是可以的。
