### ISSUE TITLE
功能建议：望加入账户系统，以实现其他用户使用需求

### ISSUE THREAD

**Issue by WeiyangSO** [Xhofe/alist#173]
问题描述：在v1.0版本中，加密隐藏方式为文件夹加密，加入好友（家人、朋友、同学等）网盘后可通过好友自行设置相关目录权限（隐藏、加密）。更新v2.0版本后通过后台进行控制目录权限，如其他用户需要修改相关权限，需网站搭建者完成相关需求，无法自主实现。故望添加账户系统（由管理员控制），给予普通用户增加网盘、目录控制等相关权限，以提升其他用户自主管理能力。

**Comment by Xhofe** [comment]
暂不考虑做多用户。

**Comment by WeiyangSO** [comment]
好的，感谢回复！
