### ISSUE TITLE
小米云盘

### ISSUE THREAD

**Issue by zhangzc0223** [Xhofe/alist#174]
您好，请问能否添加小米云盘的支持。

**Comment by Xhofe** [comment]
看了一下 小米云盘的下载是`post application/x-www-form-urlencoded`请求，无法直链，所以暂不考虑。

**Comment by Qoo-330ml** [comment]
同问，希望支持小米云盘

**Comment by xiaocaiye5201314** [comment]
同问，希望可以支持
