### ISSUE TITLE
某些视频无法播放

### ISSUE THREAD

**Issue by MisakaF0406** [Xhofe/alist#175]
在播放某些视频时左上角提示重新连接，随后变为加载失败，换用其它浏览器或更改为手机客户端token都无法解决
![image](https://user-images.githubusercontent.com/76677904/143531332-9cc74fec-d3a7-4332-89d2-763669960604.png)
![image](https://user-images.githubusercontent.com/76677904/143531224-86a0e1c0-3947-42ac-a008-e266ac49cafc.png)
使用potplayer可正常播放。

**Comment by Xhofe** [comment]
https://alist-doc.nn.ci/docs/common%20question#%E8%A7%86%E9%A2%91%E6%92%AD%E6%94%BE%E4%B8%8D%E4%BA%86
