### ISSUE TITLE
360极速浏览器访问白屏

### ISSUE THREAD

**Issue by yoval** [Xhofe/alist#176]
搭建完成后，360极速浏览器X 不论是兼容模式还是极速模式均白屏，后来发现访问demo也是白屏。切换浏览器后一切正常……

![360](https://cdn.jsdelivr.net/gh/yoval/TuChuang@main/16381833655851638183365543.png)

**Comment by Xhofe** [comment]
组件库使用的是[chakra-ui](https://github.com/chakra-ui/chakra-ui)，他不支持我也没办法

**Comment by yoval** [comment]
> 组件库使用的是[chakra-ui](https://github.com/chakra-ui/chakra-ui)，他不支持我也没办法
应该是支持的吧，间歇性能打开……其它浏览器就一直很正常。

希望能够给几个自定义js/css demo，以方便照猫画虎。搜索半天凑出了
```
document.getElementsByClassName("chakra-link")[1].innerHTML = "Hello World";
```
控制台有效贴入设置就无效了。

**Comment by Xhofe** [comment]
css：https://alist-doc.nn.ci/docs/style
js由于前端是通过react渲染，所以无法立即获取到dom，可通过setInterval进行判断是否渲染完成，如：
```js
let interval = setInterval(() =>{
    if (document.querySelector('.overlay')) {
        document.querySelector('.overlay').hidden = true;
        clearInterval(interval);
    }
},
500)
```
