### ISSUE TITLE
用的宝塔+Supervisor管理器 2.2，IP：端口 访问好用，但是如何加入域名访问呢？

### ISSUE THREAD

**Issue by hyy34** [Xhofe/alist#18]
想设置http://域名：端口，反代后，为什么不好使呢？请问如何设置域名访问呢？谢谢。

**Comment by Xhofe** [comment]
> 想设置http://域名：端口，反代后，为什么不好使呢？请问如何设置域名访问呢？谢谢。

IP：PORT可以用说明程序是没有问题的。检查一下反代的配置文件，使用宝塔的反代功能的话就不用添加教程中的配置了。

**Comment by hyy34** [comment]
> > 想设置[http://域名：端口，反代后，为什么不好使呢？请问如何设置域名访问呢？谢谢。](http://%E5%9F%9F%E5%90%8D%EF%BC%9A%E7%AB%AF%E5%8F%A3%EF%BC%8C%E5%8F%8D%E4%BB%A3%E5%90%8E%EF%BC%8C%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E5%A5%BD%E4%BD%BF%E5%91%A2%EF%BC%9F%E8%AF%B7%E9%97%AE%E5%A6%82%E4%BD%95%E8%AE%BE%E7%BD%AE%E5%9F%9F%E5%90%8D%E8%AE%BF%E9%97%AE%E5%91%A2%EF%BC%9F%E8%B0%A2%E8%B0%A2%E3%80%82)
> 
> IP：PORT可以用说明程序是没有问题的。检查一下反代的配置文件，使用宝塔的反代功能的话就不用添加教程中的配置了。

宝塔站点域名已经加入 http://域名:端口，反代如下：
![jgv56DAQMb](https://user-images.githubusercontent.com/26433019/104843892-f382a280-5907-11eb-8074-6b6ed602deba.jpg)
http://域名:端口 无法访问。教程的配置没加。
