### ISSUE TITLE
直接访问文件直链，文件夹设置的密码不起作用

### ISSUE THREAD

**Issue by acgbox233** [Xhofe/alist#19]
输入密码之后，获取到文件直链，如果以后直接访问这个链接，就能直接开始下载，相当于绕过了密码，不知道大佬能否解决这个问题。

**Comment by Xhofe** [comment]
> 输入密码之后，获取到文件直链，如果以后直接访问这个链接，就能直接开始下载，相当于绕过了密码，不知道大佬能否解决这个问题。

这个问题的话可能需要自建目录树，需要增加内存占用或者引入数据库了。之后可能会使用sqlite3吧。我先想想🤔️

**Comment by Xhofe** [comment]
已经更新。
