### ISSUE TITLE
打开时速度极慢

### ISSUE THREAD

**Issue by LimeZky** [Xhofe/alist#20]
在首次打开时，往往需要数次尝试，且等待网页加载1分钟以上才能正常显示内容

**Comment by Xhofe** [comment]
初次响应速度主要是看服务器与阿里云盘服务器之间的通信速度，之后会有缓存，觉得太慢的话可以把缓存时间设置长一点。

**Comment by imldy** [comment]
还有需求的话可以试试这个https://github.com/imldy/alist-web-dist，
使用cdn加速静态资源，对于初次访问小带宽服务器来说有奇效，我用着能缩减时间到原来的十分之一。
