### ISSUE TITLE
mp4视频播放黑屏，是不是需要更新ArtPlayer

### ISSUE THREAD

**Issue by coppea** [Xhofe/alist#208]
### Alist Version / Alist 版本

511efce

### Describe the bug / 问题描述

mp4播放黑屏，只有声音没有画面

### Reproduction / 复现链接

https://user-images.githubusercontent.com/86509331/145745005-fd506ae7-f88f-43b1-a53f-6be35672cd71.mp4

**Comment by coppea** [comment]
是onedrive的问题

**Comment by STEVENTAN100** [comment]
> 是onedrive的问题

我也遇到了这个问题，但阿里云是可以正常播放的
