### ISSUE TITLE
网格布局下点击浏览图片的问题

### ISSUE THREAD

**Issue by Joket-abc** [Xhofe/alist#212]
### Alist Version / Alist 版本

v2.0.1-0-ga295e70-dirty

### Describe the bug / 问题描述

1、网格布局下点击浏览图片会同时请求同目录下的所有图片，在图片数量庞大的情况下会导致加载缓慢以及不必要的流量流失。
![后台请求](https://user-images.githubusercontent.com/61594596/145779920-cc9a4a8c-ff95-4be7-b99c-7edcd8640ccb.png)

2、预览图拉伸异常
![前台](https://user-images.githubusercontent.com/61594596/145779951-e29a7ded-804e-4349-b3eb-b7022b5081e3.png)

3、点击浏览图片后直接返回上一层，出现异常的请求 (path not found)
![异常请求](https://user-images.githubusercontent.com/61594596/145780477-b3b2cb00-9225-4db3-b6cf-a192c683ee1b.png)

### Reproduction / 复现链接

http://alist.kiocg.com:30302/%E2%91%A1%E3%80%96%E5%B1%95%E7%A4%BA%E5%9B%BE%E3%80%97/%E3%80%90%E5%9C%B0%E5%BD%A2%E9%A3%8E%E5%85%89%E3%80%91world1

**Comment by Xhofe** [comment]
1. 你觉得应该如何设计浏览图片的方式，react-viewer提供的组件下方的预览图就是原图，所以会一次性请求所有图片
2. 已修复，如果要完全无拉伸的话，自定义中添加：
```css
.react-viewer-navbar img{
  object-fit: cover;
}
```
3. 已修复

**Comment by Joket-abc** [comment]
> 1. 你觉得应该如何设计浏览图片的方式，react-viewer提供的组件下方的预览图就是原图，所以会一次性请求所有图片


react-viewer组件下方的图如果没法改成预览图的话，直接去除也可以，毕竟没点开react-viewer之前已经有网格预览图了。
网格预览图默认可以改得大点，比如我上面提供的网址里那样的效果看图会比较舒服
