### ISSUE TITLE
部分视频在后台打开代理模式就能正常在线播放，关闭代理模式就不行

### ISSUE THREAD

**Issue by moesnow** [Xhofe/alist#216]
### Alist Version / Alist 版本

v2.0.1-0-ga295e70

### Describe the bug / 问题描述

浏览器：Safari 15.1 （Chrome没问题）

阿里云盘部分视频在后台打开代理模式就能正常在线播放，关闭代理模式就不行，提示重新连接XX。

还试过先打开代理功能，然后打开视频后关闭代理功能，拖动进度条又能播放了，显示是302跳转到了阿里的链接，这应该不是视频编码问题吧，可能是什么原因呢

出问题的视频：https://www.aliyundrive.com/s/5RLS1BEaRH1  不知道能不能复现这个问题

![未命名.png](https://s2.loli.net/2021/12/14/DsE1xOvb2Rl4wXp.png)
![未命名2.png](https://s2.loli.net/2021/12/14/us2QAINvamn8h3B.png)

**Comment by Xhofe** [comment]
阿里云盘后期上传的文件好像全部响应头全部是`Content-Type: application/octet-stream`，Safari比较严格无法播放响应头类型为`application/octet-stream`的视频，对于代理中转为什么可以播放可能是同域比较宽松吧，这个我也不太清楚。

**Comment by Xhofe** [comment]
References:
- [why-wont-safari-play-file-without-extension-in-video](https://stackoverflow.com/questions/30199261/why-wont-safari-play-file-without-extension-in-video)
- [how-to-play-a-video-from-url-with-no-file-extension-in-ios](https://stackoverflow.com/questions/32954091/how-to-play-a-video-from-url-with-no-file-extension-in-ios/32967365#32967365)

**Comment by zzwk** [comment]
> 阿里云盘后期上传的文件好像全部响应头全部是`Content-Type: application/octet-stream`，Safari比较严格无法播放响应头类型为`application/octet-stream`的视频，对于代理中转为什么可以播放可能是同域比较宽松吧，这个我也不太清楚。


请问.mp4的视频响应头video/mp4，.mkv的视频则是application/octet-stream，导致safari无法播放后者但能播放前者是什么情况呀？都是OneDrive，教育账号，开启了proxy。如图所示：
![image](https://user-images.githubusercontent.com/51788980/161416876-a0ad9b6b-e065-422a-80dd-8093780c704b.png)
![image](https://user-images.githubusercontent.com/51788980/161416885-577266a3-5d37-48af-8ab6-87e2bf4d1bc0.png)
