### ISSUE TITLE
windows下出现错误

### ISSUE THREAD

**Issue by 2563411574** [Xhofe/alist#22]
如图
![1](https://user-images.githubusercontent.com/42865393/106726324-37ceac00-6645-11eb-86c5-8c41f20aeb77.png)

**Comment by 2563411574** [comment]
：后的确有加空格 代码高亮也有提示了 但是就是不知道怎么回事

**Comment by Xhofe** [comment]
> ：后的确有加空格 代码高亮也有提示了 但是就是不知道怎么回事

这一行和上面以行冒号与内容距离可以看出来不一样 是不是29行冒号后面没加空格

**Comment by 2563411574** [comment]
是的 现在已经好了
不过新的问题来了 打开网页后显示404
并没有报错 是啥原因呢

**Comment by Xhofe** [comment]
> 是的 现在已经好了
> 
> 不过新的问题来了 打开网页后显示404
> 
> 并没有报错 是啥原因呢

可以描述具体一点吗？比如是如何访问 本地电脑还是win服务器 有没有反向代理这些

**Comment by 2563411574** [comment]
> > 是的 现在已经好了
> > 不过新的问题来了 打开网页后显示404
> > 并没有报错 是啥原因呢
> 
> 可以描述具体一点吗？比如是如何访问 本地电脑还是win服务器 有没有反向代理这些

在Windows服务器上的浏览器打开的 无反代 有宝塔和nginx基础环境

**Comment by Xhofe** [comment]
> > > 是的 现在已经好了
> > > 不过新的问题来了 打开网页后显示404
> > > 并没有报错 是啥原因呢
> > 
> > 
> > 可以描述具体一点吗？比如是如何访问 本地电脑还是win服务器 有没有反向代理这些
> 
> 在Windows服务器上的浏览器打开的 无反代 有宝塔和nginx基础环境

先检查是否能够访问到后端 可以看日志是否有请求信息 如果是后端返回的404 page not found的话，检查前端dist文件夹是否和alist.exe在同级目录，如果是浏览器直接404的话，请检查访问地址是否正确，默认本地为http://localhost:5244 远程为http://ip:5244

**Comment by 2563411574** [comment]
> > > > 是的 现在已经好了
> > > > 不过新的问题来了 打开网页后显示404
> > > > 并没有报错 是啥原因呢
> > > 
> > > 
> > > 可以描述具体一点吗？比如是如何访问 本地电脑还是win服务器 有没有反向代理这些
> > 
> > 
> > 在Windows服务器上的浏览器打开的 无反代 有宝塔和nginx基础环境
> 
> 先检查是否能够访问到后端 可以看日志是否有请求信息 如果是后端返回的404 page not found的话，检查前端dist文件夹是否和alist.exe在同级目录，如果是浏览器直接404的话，请检查访问地址是否正确，默认本地为http://localhost:5244 远程为http://ip:5244

alist.exe +exec conf.yml
我是这样启动的 没有日志 地址是正确的 也的确在同一个文件夹内

**Comment by Xhofe** [comment]
> > > > > 是的 现在已经好了
> > > > > 不过新的问题来了 打开网页后显示404
> > > > > 并没有报错 是啥原因呢
> > > > 
> > > > 
> > > > 可以描述具体一点吗？比如是如何访问 本地电脑还是win服务器 有没有反向代理这些
> > > 
> > > 
> > > 在Windows服务器上的浏览器打开的 无反代 有宝塔和nginx基础环境
> > 
> > 
> > 先检查是否能够访问到后端 可以看日志是否有请求信息 如果是后端返回的404 page not found的话，检查前端dist文件夹是否和alist.exe在同级目录，如果是浏览器直接404的话，请检查访问地址是否正确，默认本地为http://localhost:5244 远程为http://ip:5244
> 
> alist.exe +exec conf.yml
> 我是这样启动的 没有日志 地址是正确的 也的确在同一个文件夹内

那是`404 page not found`还是`该网页无法正常运作xxx 未发送任何数据。ERR_EMPTY_RESPONSE 重新加载`这种

**Comment by 2563411574** [comment]
> > > > > > 是的 现在已经好了
> > > > > > 不过新的问题来了 打开网页后显示404
> > > > > > 并没有报错 是啥原因呢
> > > > > 
> > > > > 
> > > > > 可以描述具体一点吗？比如是如何访问 本地电脑还是win服务器 有没有反向代理这些
> > > > 
> > > > 
> > > > 在Windows服务器上的浏览器打开的 无反代 有宝塔和nginx基础环境
> > > 
> > > 
> > > 先检查是否能够访问到后端 可以看日志是否有请求信息 如果是后端返回的404 page not found的话，检查前端dist文件夹是否和alist.exe在同级目录，如果是浏览器直接404的话，请检查访问地址是否正确，默认本地为http://localhost:5244 远程为http://ip:5244
> > 
> > 
> > alist.exe +exec conf.yml
> > 我是这样启动的 没有日志 地址是正确的 也的确在同一个文件夹内
> 
> 那是`404 page not found`还是`该网页无法正常运作xxx 未发送任何数据。ERR_EMPTY_RESPONSE 重新加载`这种

404  page not found

**Comment by 2563411574** [comment]
可以了 多谢

**Comment by Xhofe** [comment]
> 可以了 多谢

不客气。
...404 page not found 就是找不到dist文件夹出现的错误
