### ISSUE TITLE
挂载的OneDrive网盘突然报错：CompactToken parsing failed with error code: 80049217

### ISSUE THREAD

**Issue by ChirmyRam** [Xhofe/alist#221]
### Alist Version / Alist 版本

v2.0.1

### Describe the bug / 问题描述

挂载的OneDrive网盘突然报错：CompactToken parsing failed with error code: 80049217，挂载的其他OneDrive网盘无异常。
![image](https://user-images.githubusercontent.com/34760505/146400950-aad63f7e-a51d-4c14-b703-3a6d88fef7e2.png)

### Reproduction / 复现链接

https://al.chirmyram.com/rep

### 日志 / Logs

```shell
CompactToken parsing failed with error code: 80049217
```

**Comment by Xhofe** [comment]
需要重新获取一下refresh_token在后台添加一下。
onedrive的API不知道为什么最近有时候获取到的refresh_token是空的，已经在v2.0.2中增加了处理，先看看有没有效果吧。

**Comment by ChirmyRam** [comment]
> 需要重新获取一下refresh_token在后台添加一下。 onedrive的API不知道为什么最近有时候获取到的refresh_token是空的，已经在v2.0.2中增加了处理，先看看有没有效果吧。

感谢，目前已恢复正常。
