### ISSUE TITLE
设置根目录失败

### ISSUE THREAD

**Issue by huoshenlaile** [Xhofe/alist#23]
修改配置文件中的`ali_drive.root_folder`为想要设置的文件夹的`file_id`即可。
我在根目录下新建了一个文件夹 名字为 `share`
然后修改那个参数为`share`
结果无法访问, 网页打开就提示 `The resource file cannot be found. file not exist`

**Comment by Xhofe** [comment]
file_id不是指文件夹，是指在阿里云盘打开那个文件夹时的url folder后面那串字符串

**Comment by huoshenlaile** [comment]
哦哦十分感谢!
