### ISSUE TITLE
pikpak网盘在挂载大约一天之后无法加载文件列表

### ISSUE THREAD

**Issue by karma-sun** [Xhofe/alist#247]
### Alist Version / Alist 版本

v2.0.2

### Describe the bug / 问题描述

pikpak网盘在挂载大约一天之后无法加载文件列表，期间无任何操作，必须重启服务
确定不是pikpak的问题，重启alist服务可恢复正常

**Comment by Xhofe** [comment]
此问题已在[v2.0.3](https://github.com/Xhofe/alist/releases/tag/v2.0.3)中修复，commit: 337bf08cd375e628a89f3493746c226c05297cc8
