### ISSUE TITLE
路径带#直接404，路径带空格vlc唤起无法播放

### ISSUE THREAD

**Issue by xiaokaixuan** [Xhofe/alist#248]
### Alist Version / Alist 版本

v2.0.2-0-gc64c003

### Describe the bug / 问题描述

路径带#直接404，路径带空格vlc唤起无法播放

**Comment by Xhofe** [comment]
#### 路径带#直接404
?: Parameters
#: Anchor
所以请不要在文件(夹)名中包含`?`或`#`
> https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL

#### 路径带空格vlc唤起无法播放
测试无问题，无法复现。

**Comment by xiaokaixuan** [comment]
> #### 路径带#直接404
> ?: Parameters #: Anchor 所以请不要在文件(夹)名中包含`?`或`#`
> 
> > https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL
> 
> #### 路径带空格vlc唤起无法播放
> 测试无问题，无法复现。

带#的文件是转存的别人分享的

`https://alist.xhofe.top/阿里云盘/视频/马保国 TOP10十大鬼畜改编(故事篇) 第一名永远无法超越 究竟发生甚么事了？ - YouTube.mkv`

这个视频vlc唤起就无法播放，我用的安卓vlc

**Comment by Xhofe** [comment]
安卓 VLC v3.3.4 无问题

**Comment by xiaokaixuan** [comment]
那就不知道原因了  我的也是3.3.4 google play 版  其他视频好着  就这个不行

**Comment by xiaokaixuan** [comment]
> 那就不知道原因了 我的也是3.3.4 google play 版 其他视频好着 就这个不行

最新Beta版VLC播放没问题了
关于文件名中井号的问题，貌似只有井号是个例外，官方重命名时就已经限制了问号。

**Comment by hcwhan** [comment]
https://github.com/alist-org/web-v2/pull/51
