### ISSUE TITLE
onedrive获取刷新令牌无法得出结果

### ISSUE THREAD

**Issue by foxmi** [Xhofe/alist#250]
### Alist Version / Alist 版本

v2.0.3

### Describe the bug / 问题描述

得出的client_id和client_secret填入https://tool.nn.ci/onedrive/request 后
显示的状态一直是 refresh_token: 获取中
![问题截图](https://user-images.githubusercontent.com/40156272/147539180-1fdbb21a-ea6d-41ec-a2be-5ee72053df69.png)

**Comment by Xhofe** [comment]
F12 控制台给一下 https://tool.nn.ci/api/onedrive/get_refresh_token.ts 这个请求的payload和response

**Comment by foxmi** [comment]
说来也奇怪，这个问题留言完后，截止2021年12月28日15:41:36。Ctrl+R后回退了一步，就获取了refresh_token
![获取结果](https://user-images.githubusercontent.com/40156272/147541343-483671f7-5044-41a8-9eab-2fdcabce3202.png)

**Comment by foxmi** [comment]
感谢您的支持
