### ISSUE TITLE
【12-31】文件路径中含有 “#”号时会无法解析

### ISSUE THREAD

**Issue by tzf1003** [Xhofe/alist#258]
### Alist Version / Alist 版本

v2.0.3-0-gd6d2f52-dirty

### Describe the bug / 问题描述

![image](https://user-images.githubusercontent.com/46259700/147804390-83916b52-d012-44b7-9a42-b454330ee2f6.png)
诸如此类

### Reproduction / 复现链接

[复现地址](http://129.211.163.19:5244/%E5%B0%8F%E5%A7%90%E5%A7%90/QQ%E7%90%A6/6825041936567520526-%E8%BF%99%E5%8F%8C%E8%85%BF%E5%81%9A%E4%BD%A0%E5%A5%B3%E6%9C%8B%E5%8F%8B%E5%90%88%E6%A0%BC%E5%90%97%EF%BC%9F#%E8%85%BF.mp4)

**Comment by Xhofe** [comment]
Duplicated with #248

**Comment by tzf1003** [comment]
> Duplicated with #248

是否可以将这些内容在URL进行转义，后端重新转义过来，比如
空格                                %20
/                                      %2F    
?                                      %3F    
%                                     %25    
#                                      %23    
&                                     %26    
=                                     %3D
等等
实现应该是比较简单的，
因为%也存在于转义中，所以也解决了源文件内含有%误转义的问题

**Comment by Xhofe** [comment]
前端还有其他的Anchor，容易造成混乱 所以暂不考虑。之后会将请求中的pathname改成decodeURI(window.location.href.substr(window.location.origin.length)) 以支持#等特殊符号。

**Comment by Xhofe** [comment]
> 前端还有其他的Anchor，容易造成混乱 所以暂不考虑。之后会将请求中的pathname改成decodeURI(window.location.href.substr(window.location.origin.length)) 以支持#等特殊符号。

浏览器会直接忽略anchor，所以暂不考虑这个问题。
