### ISSUE TITLE
windows版本无法运行

### ISSUE THREAD

**Issue by uniboy747** [Xhofe/alist#26]
你好，在windows运行环境中，打开程序显示“检查更新”后立即闪退

**Comment by 122cygf** [comment]
请先在[https://github.com/Xhofe/alist-web/releases](url)下载前端代码，具体可以参考[https://www.nn.ci/archives/alist.html](url)

**Comment by Xhofe** [comment]
> 你好，在windows运行环境中，打开程序显示“检查更新”后立即闪退

可以描述具体一点吗，比如日志输出到哪里闪退

**Comment by misaka123456** [comment]
[root@iZ2zee5n9tn8kvoy8l9mscZ alist]# ./alist 
INFO[2021-02-27 11:57:01] 
 ________  ___       ___  ________  _________   
|\   __  \|\  \     |\  \|\   ____\|\___   ___\ 
\ \  \|\  \ \  \    \ \  \ \  \___|\|___ \  \_| 
 \ \   __  \ \  \    \ \  \ \_____  \   \ \  \  
  \ \  \ \  \ \  \____\ \  \|____|\  \   \ \  \ 
   \ \__\ \__\ \_______\ \__\____\_\  \   \ \__\
    \|__|\|__|\|_______|\|__|\_________\   \|__|
                            \|_________| 
INFO[2021-02-27 11:57:01] 检查更新...                                      
panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
github.com/Xhofe/alist/bootstrap.CheckUpdate()
        /home/runner/work/alist/alist/bootstrap/update.go:37 +0x479
github.com/Xhofe/alist/bootstrap.start()
        /home/runner/work/alist/alist/bootstrap/cmd.go:48 +0x76
github.com/Xhofe/alist/bootstrap.Run()
        /home/runner/work/alist/alist/bootstrap/cmd.go:29 +0xd3
main.main()
        /home/runner/work/alist/alist/alist.go:6 +0x17

**Comment by Xhofe** [comment]
> ```
> [root@iZ2zee5n9tn8kvoy8l9mscZ alist]# ./alist 
> INFO[2021-02-27 11:57:01] 
>  ________  ___       ___  ________  _________   
> |\   __  \|\  \     |\  \|\   ____\|\___   ___\ 
> \ \  \|\  \ \  \    \ \  \ \  \___|\|___ \  \_| 
>  \ \   __  \ \  \    \ \  \ \_____  \   \ \  \  
>   \ \  \ \  \ \  \____\ \  \|____|\  \   \ \  \ 
>    \ \__\ \__\ \_______\ \__\____\_\  \   \ \__\
>     \|__|\|__|\|_______|\|__|\_________\   \|__|
>                             \|_________| 
> INFO[2021-02-27 11:57:01] 检查更新...                                      
> panic: runtime error: slice bounds out of range [1:0]
> 
> goroutine 1 [running]:
> github.com/Xhofe/alist/bootstrap.CheckUpdate()
>         /home/runner/work/alist/alist/bootstrap/update.go:37 +0x479
> github.com/Xhofe/alist/bootstrap.start()
>         /home/runner/work/alist/alist/bootstrap/cmd.go:48 +0x76
> github.com/Xhofe/alist/bootstrap.Run()
>         /home/runner/work/alist/alist/bootstrap/cmd.go:29 +0xd3
> main.main()
>         /home/runner/work/alist/alist/alist.go:6 +0x17
> ```

可能是无法访问https://api.github.com/repos/Xhofe/alist/releases/latest 的原因。

**Comment by Ghd-0802** [comment]
[WIN10 无法运行](https://ae01.alicdn.com/kf/H6b1feed4bc954e2196cfdaff695d915aX.png) 显示检查更新 没有看到其他提示就闪退了,https://api.github.com/repos/Xhofe/alist/releases/latest 可以正常访问

**Comment by Xhofe** [comment]
现在可以在命令行中添加-skip-update跳过检查更新
