### ISSUE TITLE
【2022-1-1】Webkit内核打开前端页面白屏

### ISSUE THREAD

**Issue by tzf1003** [Xhofe/alist#266]
### Alist Version / Alist 版本

v2.0.3-0-gd6d2f52-dirty

### Describe the bug / 问题描述

谷歌内核打开正常，但使用Webkit内核出现白屏情况，多机器测试同样复现问题，请排查。

![image](https://user-images.githubusercontent.com/46259700/147845008-feac8313-9af9-4b3c-a8f8-f9c2f1ab8781.png)

### Reproduction / 复现链接

所有网站统一有此问题，包括官方测试网站

**Comment by Xhofe** [comment]
iOS和macOS Safari都可以打得开，不支持远古内核。具体请自己查看：
- [vite browser support](https://vitejs.dev/guide/#browser-support)
- [react browser support](https://reactjs.org/docs/react-dom.html#browser-support)
- [chakra-ui browser support](https://github.com/chakra-ui/chakra-ui/issues/57)

**Comment by tzf1003** [comment]
> iOS和macOS Safari都可以打得开，不支持远古内核。具体请自己查看：
> 
> * [vite browser support](https://vitejs.dev/guide/#browser-support)
> * [react browser support](https://reactjs.org/docs/react-dom.html#browser-support)
> * [chakra-ui browser support](https://github.com/chakra-ui/chakra-ui/issues/57)

是否可以增加一个友好界面，提示用户内核版本过低，直接白屏对用户体验影响太大，而且内核版本太低的现象普遍存在
