### ISSUE TITLE
求助：执行命令报错，请问还需要修改哪里呀！

### ISSUE THREAD

**Issue by back11** [Xhofe/alist#28]
执行命令报错 ：![image.png](https://pic.rmb.bdstatic.com/bjh/943dde43d40bbad55f42032c326af8ee.png)
文件路径：![image.png](https://pic.rmb.bdstatic.com/bjh/7b9b88c1f7ca660cc38b50d0ced5a284.png)
配置文件就改了路径和 token：![image.png](https://pic.rmb.bdstatic.com/bjh/daba659215f9ee5c6bc7d77463660f12.png)

**Comment by Xhofe** [comment]
根目录指的是阿里云盘的根目录的file_id，第一层为root。然后就是你这个截图中并没有报错，nohup执行输出了进程的pid，具体日志可以在log.log中查看。还有你的配置文件第一行缩进好像也有问题，info前面应该是没有空格的。

**Comment by back11** [comment]
我把 根目录 和 info格式 改回来了，在执行一遍命令，用 ip:5244 还是没有反应，5244端口 也放行了
![image.png](https://pic.rmb.bdstatic.com/bjh/13ef300aef2009ace6231267e5357720.png)

**Comment by Xhofe** [comment]
可以看一下日志吗，同目录下的log.log文件。

**Comment by back11** [comment]
![image.png](https://pic.rmb.bdstatic.com/bjh/c85db4f8b13fee21d56ff5fdcc0ef079.png)

**Comment by Xhofe** [comment]
> ![image.png](https://pic.rmb.bdstatic.com/bjh/c85db4f8b13fee21d56ff5fdcc0ef079.png)

下载的版本不对，需要下载对应的系统的。

**Comment by back11** [comment]
终于好了，感谢大佬！就是 下载的版本的 问题
给后面小伙伴提个醒： linux64 位 要下载  linux_amd64

**Comment by Xhofe** [comment]
> 终于好了，感谢大佬！就是 下载的版本的 问题
> 
> 给后面小伙伴提个醒： linux64 位 要下载  linux_amd64

不客气
