### ISSUE TITLE
v2.0.4-fix2版本闪退

### ISSUE THREAD

**Issue by Joket-abc** [Xhofe/alist#281]
### Alist Version / Alist 版本

v2.0.4-fix2

### Describe the bug / 问题描述

windows环境，使用v2.0.4-fix1可以正常启用alist，切换到v2.0.4-fix2之后打开软件闪退

**Comment by Xhofe** [comment]
请提供错误日志

**Comment by Joket-abc** [comment]
> 请提供错误日志

如何获得错误日志，有没有存在什么文件里之类的。因为是闪退没法直接从软件界面获得

**Comment by Xhofe** [comment]
> > 请提供错误日志
> 
> 如何获得错误日志，有没有存在什么文件里之类的。因为是闪退没法直接从软件界面获得

使用命令行运行，./alist-xxxx -debug

**Comment by Joket-abc** [comment]
> > > 请提供错误日志
> > 
> > 
> > 如何获得错误日志，有没有存在什么文件里之类的。因为是闪退没法直接从软件界面获得
> 
> 使用命令行运行，alist-xxxx -debug

FATA[2022-01-04 10:55:54]/source/bootstrap/setting.go:215 github.com/Xhofe/alist/bootstrap.InitSettings() failed write setting: Error 1366: Incorrect string value: '\xF0\x9F\x8F\xA0' for column 'value' at row 1

完整报错：https://netcut.cn/p/78c41283dbaef549

**Comment by Xhofe** [comment]
使用的是什么数据库？

**Comment by Joket-abc** [comment]
> 使用的是什么数据库？

MySQL

**Comment by Xhofe** [comment]
数据库编码不支持，需要修改为utf8mb4，支持完整的utf-8编码
