### ISSUE TITLE
Token鉴权 防盗链

### ISSUE THREAD

**Issue by kedyao** [Xhofe/alist#29]
可参考 https://github.com/townsinger/TCShare#安全规则
token 优先级最高 无视加密文件夹等
适用于 防止网盘地址暴露被外链至公共网络白嫖致死
ref防盗链可以被伪造 安全性略低

**Comment by LittleTurtle2333** [comment]
确实很有需要

**Comment by Xhofe** [comment]
可能暂时不会添加token鉴权。

**Comment by bebestmaple** [comment]
尝试使用nginx的防盗链，但失败，访问404了

**Comment by yang9w** [comment]
> 尝试使用nginx的防盗链，但失败，访问404了

主页点击进去不是404.刷新才是404.
