### ISSUE TITLE
一直转不显示数据

### ISSUE THREAD

**Issue by wendaleruan** [Xhofe/alist#3]
按照教程搭建好，一直转圈不显示数据
![image](https://user-images.githubusercontent.com/7631911/103137601-2e2c5d00-4705-11eb-95b8-9d0c89789014.png)

![image](https://user-images.githubusercontent.com/7631911/103137588-181e9c80-4705-11eb-9e4c-296292689224.png)

**Comment by Xhofe** [comment]
应该是后端返回的数据有问题，看一下network那里返回的数据？或者看一下日志

**Comment by wendaleruan** [comment]
network我也不会看~ 在这里 http://ali.tobo.me/ 反代了 http://127.0.0.1:5244/  
不分离的方式
![image](https://user-images.githubusercontent.com/7631911/103137814-6cc31700-4707-11eb-8cc6-a37d7409770c.png)

**Comment by Xhofe** [comment]
啊这 可以看一下日志吗 cat log.log

**Comment by wendaleruan** [comment]
![image](https://user-images.githubusercontent.com/7631911/103137985-ce37b580-4708-11eb-9315-2d7c774936b1.png)

**Comment by Xhofe** [comment]
我的锅 应该是反代那里写错了😭
反代配置文件那里http://127.0.0.1:5244/去掉后面的/

**Comment by wendaleruan** [comment]
ok，成功！谢谢！

**Comment by Xhofe** [comment]
不客气 😀
