### ISSUE TITLE
libc.so.6报错

### ISSUE THREAD

**Issue by tbc0309** [Xhofe/alist#322]
### Alist Version / Alist 版本

v2.0.5

### Describe the bug / 问题描述

执行报错，2.0.4没这个问题

### Reproduction / 复现链接

./alist

### 日志 / Logs

```shell
./alist: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by ./alist)
```

**Comment by Xhofe** [comment]
换了个xgo编译 可能glibc版本比较高 等会改回去吧。。

**Comment by Xhofe** [comment]
v2.0.5-libc已release
