### ISSUE TITLE
初始化数据库失败

### ISSUE THREAD

**Issue by rerunbug** [Xhofe/alist#33]
https://s3.ax1x.com/2021/03/13/6wU5DA.png

**Comment by Xhofe** [comment]
稍等 我正在替换release文件

**Comment by rerunbug** [comment]
辛苦了

**Comment by Xhofe** [comment]
应该可以了。

**Comment by rerunbug** [comment]
不行

**Comment by rerunbug** [comment]
https://s3.ax1x.com/2021/03/13/6wdtlF.png
不行

**Comment by Xhofe** [comment]
你的是什么系统？

**Comment by rerunbug** [comment]
CentOS 7.3

**Comment by Xhofe** [comment]
amd64吗

**Comment by rerunbug** [comment]
x86

**Comment by Xhofe** [comment]
不应该啊，你是重新下载了文件再运行的吗

**Comment by rerunbug** [comment]
是啊 
我试了一下amd64的他说.找不到 .alist 文件
https://s3.ax1x.com/2021/03/13/6wBAF1.png

**Comment by Xhofe** [comment]
> https://s3.ax1x.com/2021/03/13/6wdtlF.png
> 不行

你这里下载的是哪一个文件

**Comment by rerunbug** [comment]
https://s3.ax1x.com/2021/03/13/6wD99P.png

**Comment by Xhofe** [comment]
> 是啊
> 我试了一下amd64的他说.找不到 .alist 文件
> https://s3.ax1x.com/2021/03/13/6wBAF1.png

额 那这里又是啥意思

**Comment by rerunbug** [comment]
。。。。 要不我退回老版本吧

**Comment by rerunbug** [comment]
> > 是啊
> > 我试了一下amd64的他说.找不到 .alist 文件
> > https://s3.ax1x.com/2021/03/13/6wBAF1.png
> 
> 额 那这里又是啥意思
。。。。。。要不我退回老版本吧

**Comment by Xhofe** [comment]
好像是你的系统的glibc版本太低

**Comment by rerunbug** [comment]
好吧  谢谢啦

**Comment by Xhofe** [comment]
因为现在GitHub actions默认使用的是Ubuntu 20.04编译，使用的glibc版本是2.28 ，而centos7一般默认只支持到2.17

**Comment by Xhofe** [comment]
已经替换了，并且在centos7中试了一下，可以运行了。

**Comment by rerunbug** [comment]
> 已经替换amd64的release了，并且在centos7中试了一下，可以运行了。

完美
