### ISSUE TITLE
挂载和彩云 预览时出现错误

### ISSUE THREAD

**Issue by a936919** [Xhofe/alist#338]
### Alist Version / Alist 版本

v2.0.5-0-g4ea9371

### Describe the bug / 问题描述

挂载和彩云之后，可以访问所有目录
但是单击预览后会出现用户不存在报错
![image](https://user-images.githubusercontent.com/41937411/149429674-93ae6894-523c-45d8-9af7-93475b3948b8.png)

**Comment by 2826915729** [comment]
同样的问题

**Comment by Xhofe** [comment]
https://github.com/Xhofe/alist/commit/6f7465aab7fa654cccf94d3a1a94842247ed8988

**Comment by 2826915729** [comment]
> [6f7465a](https://github.com/Xhofe/alist/commit/6f7465aab7fa654cccf94d3a1a94842247ed8988)

v2.0.5-libc-0-gc9bc822
你好，我使用的是docker版

**Comment by Xhofe** [comment]
> > [6f7465a](https://github.com/Xhofe/alist/commit/6f7465aab7fa654cccf94d3a1a94842247ed8988)
> 
> v2.0.5-libc-0-gc9bc822
> 你好，我使用的是docker版

还未release，下个版本可用。

**Comment by pongfcnkl** [comment]
上传还是用户不存在
