### ISSUE TITLE
更新运行后进入子文件夹显示空白，报错如下

### ISSUE THREAD

**Issue by MFYDev** [Xhofe/alist#34]
![image](https://user-images.githubusercontent.com/53750381/111032416-12ed0600-8447-11eb-9b15-55853a962f1a.png)

请Xhofe帮忙看一下，所有配置都是正确的，不知道哪里出错了很奇怪

**Comment by Xhofe** [comment]
可以给一下地址吗

**Comment by MFYDev** [comment]
以下是地址

https://ali.mfy.world

**Comment by Xhofe** [comment]
抱歉 我api多打了一个点，没有测试直接使用gin的情况，已经替换了web部分的release，麻烦重新替换一下前端的文件。

**Comment by MFYDev** [comment]
收到，万分感谢Xhofe，我这就去试一下

**Comment by MFYDev** [comment]
我将后端前端全部重新替换了，

这次连根目录也无法显示了

报错显示 `/home/runner/work/alist/alist/server/models/file.go:33 record not found`

**Comment by Xhofe** [comment]
我访问了一下你的地址 看到的是没问题的啊

**Comment by MFYDev** [comment]
啊抱歉，刷新缓存之后恢复正常了，非常感谢Xhofe！这就去打赏！
