### ISSUE TITLE
手机端页面不显示 修改时间 排序的按钮

### ISSUE THREAD

**Issue by jiangjiangflies** [Xhofe/alist#349]
### Alist Version / Alist 版本

v2.0.5-libc

### Describe the bug / 问题描述

大佬您好！
我搭建好之后，用电脑浏览器访问，可以按名称、大小、修改时间进行文件排序。而手机端只显示名称和大小这两项，不显示修改时间。
这个是bug还是刻意为之呢？如果移动端只能显示两项，能否自定义排序依据？我比较关注最新上传的文件，所以对修改时间排序非常重要。
谢谢！

**Comment by Xhofe** [comment]
移动端太窄了，只能显示两项。添加账号的时候可以选择默认排序。

**Comment by jiangjiangflies** [comment]
> 移动端太窄了，只能显示两项。添加账号的时候可以选择默认排序。
添加账号的地方，更改默认排序出错

![BUK8ZA)J8XU`JC%797FMG_3](https://user-images.githubusercontent.com/16556935/149494540-3435fb3b-989c-4e97-9bfe-a3c01097c04d.png)

**Comment by Xhofe** [comment]
> > 移动端太窄了，只能显示两项。添加账号的时候可以选择默认排序。
> > 添加账号的地方，更改默认排序出错
> 
> ![BUK8ZA)J8XU`JC%797FMG_3](https://user-images.githubusercontent.com/16556935/149494540-3435fb3b-989c-4e97-9bfe-a3c01097c04d.png)

onedrive for business 和 Sharepoint只支持name排序。

**Comment by Xhofe** [comment]
> > 移动端太窄了，只能显示两项。添加账号的时候可以选择默认排序。
> > 添加账号的地方，更改默认排序出错
> 
> ![BUK8ZA)J8XU`JC%797FMG_3](https://user-images.githubusercontent.com/16556935/149494540-3435fb3b-989c-4e97-9bfe-a3c01097c04d.png)

onedrive for business 和 Sharepoint只支持name排序。

**Comment by jiangjiangflies** [comment]
> > > 移动端太窄了，只能显示两项。添加账号的时候可以选择默认排序。
> > > 添加账号的地方，更改默认排序出错
> > 
> > 
> > ![BUK8ZA)J8XU`JC%797FMG_3](https://user-images.githubusercontent.com/16556935/149494540-3435fb3b-989c-4e97-9bfe-a3c01097c04d.png)
> 
> onedrive for business 和 Sharepoint只支持name排序。

不是吧？我就是用的onedrive for business（CN），在电脑浏览器上可以点击修改时间进行排序的、

**Comment by Xhofe** [comment]
API不支持
> https://docs.microsoft.com/zh-cn/onedrive/developer/rest-api/concepts/optional-query-parameters?view=odsp-graph-online#sorting-collections
> 请注意，在 OneDrive for Business 和 SharePoint Server 2016 中，orderby 查询字符串仅支持 name 和 url。

**Comment by dlytang** [comment]
> API不支持
> 
> > https://docs.microsoft.com/zh-cn/onedrive/developer/rest-api/concepts/optional-query-parameters?view=odsp-graph-online#sorting-collections
> > 请注意，在 OneDrive for Business 和 SharePoint Server 2016 中，orderby 查询字符串仅支持 name 和 url。

那可不可以先查询出来之后再按时间排序呢？
