### ISSUE TITLE
./alist: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by ./alist)

### ISSUE THREAD

**Issue by HeJiangL** [Xhofe/alist#35]
amd64 运行启动时报错： ./alist: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by ./alist)

**Comment by Xhofe** [comment]
稍等我切换到16.04重新构建一下试试

**Comment by Xhofe** [comment]
已经替换amd64版本的release #33
