### ISSUE TITLE
部署bug docker平台

### ISSUE THREAD

**Issue by fengguowudi** [Xhofe/alist#354]
### Alist Version / Alist 版本

v2.0.5-libc

### Describe the bug / 问题描述

heroku railway 等平台全部编译失败，无法访问主页面。

### Reproduction / 复现链接

无

### 日志 / Logs

```shell
https://mcdlayj.herokuapp.com/
```

**Comment by ChirmyRam** [comment]
试试这个项目： [alist-heroku](https://github.com/sbwml/alist-heroku) ，使用的是最新的docker镜像： [sbwml/alist](https://hub.docker.com/r/sbwml/alist)

**Comment by Xhofe** [comment]
你这个日志 我看不到。

**Comment by Xhofe** [comment]
railway 请使用https://github.com/alist-org/alist-railway，但是容易触发DMCA

**Comment by Xhofe** [comment]
https://alist-test.herokuapp.com/

https://github.com/alist-org/alist-heroku

**Comment by fengguowudi** [comment]
INFO[2022-01-15 01:58:27] init log...                                  
INFO[2022-01-15 01:58:27] register driver: [123Pan]                    
INFO[2022-01-15 01:58:27] register driver: [139Yun]                    
INFO[2022-01-15 01:58:27] register driver: [189Cloud]                  
INFO[2022-01-15 01:58:27] register driver: [AliDrive]                  
INFO[2022-01-15 01:58:27] register driver: [Alist]                     
INFO[2022-01-15 01:58:27] register driver: [FTP]                       
INFO[2022-01-15 01:58:27] register driver: [GoogleDrive]               
INFO[2022-01-15 01:58:27] register driver: [Lanzou]                    
INFO[2022-01-15 01:58:27] register driver: [MediaTrack]                
INFO[2022-01-15 01:58:27] register driver: [Native]                    
INFO[2022-01-15 01:58:27] register driver: [Onedrive]                  
INFO[2022-01-15 01:58:27] register driver: [PikPak]                    
INFO[2022-01-15 01:58:27] register driver: [S3]                        
INFO[2022-01-15 01:58:27] register driver: [ShandianPan]               
INFO[2022-01-15 01:58:27] register driver: [Teambition]                
INFO[2022-01-15 01:58:27] register driver: [WebDav]                    
INFO[2022-01-15 01:58:27] reading config file: data/config.json        
FATA[2022-01-15 01:58:27] load config error: conf.Config.Database: conf.Database.Port: readUint64: unexpected character: �, error found in #10 byte of ...| "port": ,
    "name|..., bigger context ...|
    "password": "",
    "host": "",
    "port": ,
    "name": "",
    "table_prefix": "x_",
    "db|...

**Comment by fengguowudi** [comment]
而且mysql的plugin我也没看着

**Comment by fengguowudi** [comment]
能大概说一下位置吗

**Comment by fengguowudi** [comment]
heroku的没问题了

**Comment by Xhofe** [comment]
> 能大概说一下位置吗

部署后就能看到。在项目的页面

**Comment by fengguowudi** [comment]
那现在就是部署失败，log在上面

**Comment by Xhofe** [comment]
> 那现在就是部署失败，log在上面

请参照readme ，添加MySQL plugin再添加变量触发重新部署后才可以正常使用。
