### ISSUE TITLE
特定情况下Readme文档不会加载的问题

### ISSUE THREAD

**Issue by CuteCatXiao** [Xhofe/alist#355]
### Alist Version / Alist 版本

v2.0.5

### Describe the bug / 问题描述

当设定`default page size`小于Readme文档排序序号时,Readme文件将不会加载,直到点击Load More.

default page size:8
![image](https://user-images.githubusercontent.com/62191675/149522287-252a73d1-70cd-44b3-8ec8-ef5ee4b68327.png)
![output](https://user-images.githubusercontent.com/62191675/149522690-6d05b7cf-90f1-43e0-ad96-a04e805ff5fe.gif)

**Comment by CuteCatXiao** [comment]
![image](https://user-images.githubusercontent.com/62191675/149523426-5df3458a-5906-4460-921d-2131889c61e7.png)
当设定`default page size`为`pagination`时,Readme文档会跑到分页2

**Comment by Xhofe** [comment]
README尽量放在文件数量少的文件夹下吧，放在超过文件数量很多的文件夹里体验也不是很好的。

**Comment by CuteCatXiao** [comment]
8个不算很多吧.....? 
但是理论上不管default page size为何值时也应该显示Readme

**Comment by CuteCatXiao** [comment]
这个例子中可以看出,根目录下已经没有除Readme以外的任何文件,但仍不显示readme

**Comment by Xhofe** [comment]
README文件是在文件列表中获取的，你文件列表中没有README肯定不会加载。

**Comment by Xhofe** [comment]
你把default page size设置的刚好是除了readme之外的文件数量把readme挤到第二页那没有办法。

**Comment by CuteCatXiao** [comment]
但是这明显不符合逻辑的,如果分页设为6的话,那么readme会和第7个文件跑到第二页

**Comment by Xhofe** [comment]
所以不要吧分页设置的这么小。

**Comment by Xhofe** [comment]
正常做法是：page_size设置为30，在超过30个文件数量的文件夹中不设置readme。而是：
```bash
.
├── ...
├── folder_of_more_than_30_children_files
│   ├── file_01
│   ├── file_02
│   ├── file_03
│   ├── ...
│   ├── file_99
│   └── file_100
└── README.md
```

**Comment by CuteCatXiao** [comment]
分页设小是想加快文件列表の加载速度

本issue已经通过指定`home readme url`解决,建议在wiki中添加相关建议
