### ISSUE TITLE
天翼云盘上传内存OOM

### ISSUE THREAD

**Issue by OpenSourceUser2021** [Xhofe/alist#358]
### Alist Version / Alist 版本

2.0.5

### Describe the bug / 问题描述

内存OOM 严重

我的场景是 NAS 同步软件通过alist 同步文件到天翼云

### 日志 / Logs

```shell
windows 版
runtime: VirtualAlloc of 413515776 bytes failed with errno=1455
fatal error: out of memory

runtime stack:
runtime.throw({0xf52908, 0xc10cebb000})
        /usr/local/go/src/runtime/panic.go:1198 +0x76
runtime.sysUsed(0xc109420000, 0x18a5c000)
        /usr/local/go/src/runtime/mem_windows.go:83 +0x1c9
runtime.(*mheap).allocSpan(0x1aadfc0, 0xc52e, 0x0, 0x1)
        /usr/local/go/src/runtime/mheap.go:1268 +0x3a5
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:913 +0x69
runtime.systemstack()
        /usr/local/go/src/runtime/asm_amd64.s:383 +0x4e

linux arm64版
Fri Jan 14 21:02:07 2022 kern.info kernel: [130470.458696] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=alist-linux-arm,pid=3562,uid=0
Fri Jan 14 21:02:07 2022 kern.err kernel: [130470.471946] Out of memory: Killed process 3562 (alist-linux-arm) total-vm:3302172kB, anon-rss:1691156kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:3456kB oom_score_adj:0
Fri Jan 14 21:02:07 2022 kern.info kernel: [130470.660111] oom_reaper: reaped process 3562 (alist-linux-arm), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

**Comment by radowitz** [comment]
> 是在上传大文件时出现的OOM吗

上传几十G的文件，直接炸了甲骨文24G内存的机子，限制下内存使用吧

**Comment by Xhofe** [comment]
在接收上传文件时会可能会将文件所有内容读到内存，所以在超大文件时会OOM，我暂时还不知道如何处理。

**Comment by OpenSourceUser2021** [comment]
切片是否可行？例如先收100M 上传完 再收下一个100M ？同步软件的超时时间可以自定义 默认是30分钟。

**Comment by yiywain** [comment]
如果暂时无法解决,请限制上传文件大小吧

**Comment by OpenSourceUser2021** [comment]
早上又试了下， 一个目录放了十几个200M 到500M 不等的视频文件  同步到天翼云 （一次一个文件未开并行传输）但是还是OOM
Sat Jan 15 10:36:39 2022 kern.info kernel: [179341.862338] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=alist-linux-arm,pid=1952,uid=0
Sat Jan 15 10:36:39 2022 kern.err kernel: [179341.875573] Out of memory: Killed process 1952 (alist-linux-arm) total-vm:2895980kB, anon-rss:1680892kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:3404kB oom_score_adj:0
Sat Jan 15 10:36:39 2022 kern.info kernel: [179342.099052] oom_reaper: reaped process 1952 (alist-linux-arm), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

是不是缓存释放不及时？

**Comment by Xhofe** [comment]
> 早上又试了下， 一个目录放了十几个200M 到500M 不等的视频文件  同步到天翼云 （一次一个文件未开并行传输）但是还是OOM
> Sat Jan 15 10:36:39 2022 kern.info kernel: [179341.862338] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=alist-linux-arm,pid=1952,uid=0
> Sat Jan 15 10:36:39 2022 kern.err kernel: [179341.875573] Out of memory: Killed process 1952 (alist-linux-arm) total-vm:2895980kB, anon-rss:1680892kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:3404kB oom_score_adj:0
> Sat Jan 15 10:36:39 2022 kern.info kernel: [179342.099052] oom_reaper: reaped process 1952 (alist-linux-arm), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
> 
> 是不是缓存释放不及时？

刚发现WebDAV的上传文件流 我好像没有关闭，可能是因为这个原因，晚些时候我关闭再发个版本。

**Comment by Xhofe** [comment]
> https://github.com/go-resty/resty/issues/133#issuecomment-370636687

我好像找到问题所在了，不是由于接受文件的原因，而是因为使用了resty通过multipart/form-data的方式进行大文件上传，它需要将文件全部读入内存进行计算一些边界条件，它甚至需要原文件2倍多的内存。
> 测试：
上传1G文件至本地，内存占用：120MB
上传1G文件至天翼云盘，内存占用：2176MB

天翼云盘现在是有分段上传的接口的，尝试实现过，不过有错误，之后会尽量去实现分段上传。

**Comment by OpenSourceUser2021** [comment]
跟我的实验好像意思有点不一样“ 一个目录放了十几个200M 到500M 不等的视频文件 同步到天翼云 （一次一个文件未开并行传输）但是还是OOM” 就算2倍多 一个一个传 也不该占几个G 呀， 另外我在电脑上开alist 一样OOM。

**Comment by Xhofe** [comment]
> 跟我的实验好像意思有点不一样“ 一个目录放了十几个200M 到500M 不等的视频文件 同步到天翼云 （一次一个文件未开并行传输）但是还是OOM” 就算2倍多 一个一个传 也不该占几个G 呀， 另外我在电脑上开alist 一样OOM。

有oom堆栈信息吗 发一下

**Comment by Xhofe** [comment]
在v2.0.8中已改为chunk上传，可更新进行测试。

**Comment by OpenSourceUser2021** [comment]
回老家过年了，年后试试，新年快乐

**Comment by OpenSourceUser2021** [comment]
2.0.9 已修复
