### ISSUE TITLE
阿里云盘输入了file_id后依旧是root目录

### ISSUE THREAD

**Issue by jh3274** [Xhofe/alist#359]
### Alist Version / Alist 版本

v2.0.6

### Describe the bug / 问题描述

限制了file_id后依旧所有文件都在list里面

### Reproduction / 复现链接

1

### 日志 / Logs

```shell
1
```

**Comment by Xhofe** [comment]
https://alist-doc.nn.ci/docs/common-question#%E4%B8%8A%E4%BC%A0%E7%9A%84%E6%96%87%E4%BB%B6%E4%B8%8D%E6%98%BE%E7%A4%BA%E5%88%A0%E9%99%A4%E7%9A%84%E6%96%87%E4%BB%B6%E8%BF%98%E5%9C%A8%E4%BF%AE%E6%94%B9%E6%A0%B9%E7%9B%AE%E5%BD%95%E4%B8%8D%E7%94%9F%E6%95%88
