### ISSUE TITLE
Debian9 初始化数据库出现错误,启动失败.  

### ISSUE THREAD

**Issue by zhucaidan** [Xhofe/alist#36]
系统为Debian 9 amd64版本，刚刚刚新的1.0，log错误如下：

[36mINFO[0m[2021-03-13 10:50:44] 检查更新...                                      
[36mINFO[0m[2021-03-13 10:50:45] 当前已是最新版本:v1.0.0                              
[36mINFO[0m[2021-03-13 10:50:45] 读取配置文件...                                    
[36mINFO[0m[2021-03-13 10:50:45] 初始化client...                                 
[36mINFO[0m[2021-03-13 10:50:45] 初始化阿里云盘...                                   
[36mINFO[0m[2021-03-13 10:50:45] 当前用户信息:&{RespError:{Code: Message:} DomainId:bj29 UserId:xxx Avatar:xxx
[36mINFO[0m[2021-03-13 10:50:45] 初始化数据库...                                    
[31mERRO[0m[2021-03-13 10:50:45] 不支持的数据库类型:                                   
[31mERRO[0m[2021-03-13 10:50:45] 初始化数据库出现错误,启动失败.

**Comment by Xhofe** [comment]
看一下教程哈，需要添加新的配置项

**Comment by zhucaidan** [comment]
> 看一下教程哈，需要添加新的配置项

可以启动了，但是出现了新的问题，首页会一直转圈不显示任何内容，右上角还会提示“发现新版本”


log如下：

[36mINFO[0m[2021-03-13 20:14:41] 
 ________  ___       ___  ________  _________   
|\   __  \|\  \     |\  \|\   ____\|\___   ___\ 
\ \  \|\  \ \  \    \ \  \ \  \___|\|___ \  \_| 
 \ \   __  \ \  \    \ \  \ \_____  \   \ \  \  
  \ \  \ \  \ \  \____\ \  \|____|\  \   \ \  \ 
   \ \__\ \__\ \_______\ \__\____\_\  \   \ \__\
    \|__|\|__|\|_______|\|__|\_________\   \|__|
                            \|_________| 
[36mINFO[0m[2021-03-13 20:14:41] 检查更新...                                      
[36mINFO[0m[2021-03-13 20:14:41] 当前已是最新版本:v1.0.0                              
[36mINFO[0m[2021-03-13 20:14:41] 读取配置文件...                                    
[36mINFO[0m[2021-03-13 20:14:41] 初始化client...                                 
[36mINFO[0m[2021-03-13 20:14:41] 初始化阿里云盘...                                   
[36mINFO[0m[2021-03-13 20:14:43] 当前用户信息:&{RespError:{Code: Message:} DomainId:bj29 UserId:
XXX Avatar:XXX Email: NickName:XXX Phone:XXX Role:user Status:enabled UserName:XXX Description: DefaultDriveId:XXX UserData:mapXXX
[36mINFO[0m[2021-03-13 20:14:43] 初始化数据库...                                    
[36mINFO[0m[2021-03-13 20:14:43] 初始化定时任务:刷新token                              
[36mINFO[0m[2021-03-13 20:14:43] 初始化路由...                                     
[36mINFO[0m[2021-03-13 20:14:43] Starting server @ 0.0.0.0:5244

**Comment by zhucaidan** [comment]
> 看一下教程哈，需要添加新的配置项

可以了，不过之前的给root目录加密码方法失效了，就是新建一个文件夹命名为“.password-xxx”

现在新版怎样添加根目录密码呢？就是一打开网站就要输入密码那样

**Comment by Xhofe** [comment]
这个版本没有考虑给根目录加密码了。。

**Comment by Xhofe** [comment]
需要的话 我之后可以再添加一个配置

**Comment by zhucaidan** [comment]
> 需要的话 我之后可以再添加一个配置

好的。。感谢大佬，因为怕恶意下载
