### ISSUE TITLE
天翼云预览pdf时 pdf.js跨域问题

### ISSUE THREAD

**Issue by a936919** [Xhofe/alist#367]
### Alist Version / Alist 版本

v2.0.6-0-g21ca2f1

### Describe the bug / 问题描述

同一个域名端口 在和彩云预览pdf文件不会报cors错误
但是天翼云预览pdf文件会有如图报错
该怎么设置
![image](https://user-images.githubusercontent.com/41937411/149608057-b5bd8757-4cf0-474d-a371-65806d97e978.png)
![image](https://user-images.githubusercontent.com/41937411/149608080-3c05d594-1ede-43f7-a7da-b704a0c80e46.png)

**Comment by Xhofe** [comment]
这是由天翼云盘控制的，并非自己可以设置。而且你这好像是家庭云啊，我没有写家庭云的支持啊？？

**Comment by a936919** [comment]
应该不是家庭云
