### ISSUE TITLE
添加ftp后无法删除

### ISSUE THREAD

**Issue by stakeswky** [Xhofe/alist#371]
### Alist Version / Alist 版本

V2.0.6

### Describe the bug / 问题描述

添加外部ftp后发现点击删除无反应

**Comment by Xhofe** [comment]
如何复现，我测试可以删除。

**Comment by stakeswky** [comment]
我先是添加了ftp，但是因为未加端口连接失败，然后点击删除无反应，后加上端口后可以正常连接ftp，但点击删除仍然无反应

**Comment by Xhofe** [comment]
> 我先是添加了ftp，但是因为未加端口连接失败，然后点击删除无反应，后加上端口后可以正常连接ftp，但点击删除仍然无反应

我按照你的流程试了一遍，还是可以直接删除，无法复现。
