### ISSUE TITLE
和彩云webdav问题

### ISSUE THREAD

**Issue by a936919** [Xhofe/alist#373]
### Alist Version / Alist 版本

v2.0.6-0-g21ca2f1

### Describe the bug / 问题描述

![image](https://user-images.githubusercontent.com/41937411/149642275-f62316f5-bcd8-4783-8a87-ede1dc5b258c.png)
只能新建文件夹但是上传删除新建文件都不行
可能是图片上的account的问题吧

**Comment by Xhofe** [comment]
已经在的dev分支提交，下个版本可用。

**Comment by a936919** [comment]
好的谢谢

**Comment by tsui603** [comment]
v2.2.0-0-g15651a4  还是同样的问题啊
