### ISSUE TITLE
和彩云无法预览视频

### ISSUE THREAD

**Issue by 2826915729** [Xhofe/alist#374]
### Alist Version / Alist 版本

v2.0.6-0-g21ca2f1

### Describe the bug / 问题描述

![Screenshot_2022-01-15-20-43-37-261_com kiwibrowser browser dev](https://user-images.githubusercontent.com/31442507/149643870-e1ad3996-e817-4dc3-befb-a272d1c76ab1.jpg)
和彩云下载链接有效次数只有一次，不能作为视频预览url，得另外使用原视频链接才能播放预览

### Reproduction / 复现链接

[alist 视频播放](https://pan.vpshax.ml/%E5%92%8C%E5%BD%A9%E4%BA%91/Screenrecorder-2022-01-07-21-00-19-919.mp4) 
[原视频资源链接](http://video.mcloud.139.com/StorageWeb/servlet/GetFileByURLServlet?dm=D960&root=/mnt/wfs97&pt=/52d/22&fileid=K752d228d6daad995b918c3eef023a016c.mp4&type=52&ui=MTU4MTMwNjI4Mjk=&ci=0011g3Yxi24i0622022011520571404k&cn=Screenrecorder-2022-...&ct=3&time=1642262366&exp=86400&code=A8EB35E5C85C1FA136E2C31227EF131F3E8446383B41E0D97C539FC2B38FD418&ec=1&bucketName=hcy-a-02)

**Comment by Xhofe** [comment]
?所以如何获取

**Comment by 2826915729** [comment]
> ?所以如何获取
我发现了一种可以从视频预览图URL中的信息，修改后可以获得预览视频链接，不过测试了有限制，视频会被进行压缩，比较大的视频文件会报错无法使用

https://pan.vpshax.ml/d/Home/%E5%92%8C%E5%BD%A9%E4%BA%91.txt?sign=9c634e9e0a873333

**Comment by 2826915729** [comment]
`Indicate whether to send a cookie in a cross-site request by specifying its SameSite attribute`
会不会与这条控制台报错有关系
