### ISSUE TITLE
Windows下部分webdav软件上传

### ISSUE THREAD

**Issue by Xhofe** [Xhofe/alist#376]
### Alist Version / Alist 版本

v2.0.6

### Describe the bug / 问题描述

Windows下的部分软件（有可能都是）在上传文件时会新建一个空文件，导致上传失败。

**Comment by ddd-zero** [comment]
我挂了个天翼云，开启webdav。然后用raidrive挂载，就会出现这样，会有2个0kb的程序。

**Comment by zongceng** [comment]
挂载的是本地盘，也是这样的情况，只能用admin账号，其他新建账号无法上传
