### ISSUE TITLE
获取直链的链接全都改变了吗?

### ISSUE THREAD

**Issue by jing5460** [Xhofe/alist#38]
原来的:
https://ae01.alicdn.com/kf/Uc03063d4ce5047a0bbdd25f9dbc3501ay.jpg
现在的:
http://......../d/root/电影 一只鱼/僵尸（七日重生）.超清国粤双语中字.mp4?pw=
    想知道后期会改回原来的, 还是以后都用这种链接了

**Comment by Xhofe** [comment]
对的 以后都会用这种按照目录结构的链接
