### ISSUE TITLE
希望添加更多后缀的视频预览

### ISSUE THREAD

**Issue by zsbai** [Xhofe/alist#39]
希望添加ts后缀视频的在线预览

**Comment by zsbai** [comment]
还有一个建议，希望可以把链接中的中文改成某种编码,不然在微信中无法直接点开...或者可以在配置文件里增加一个选项？

**Comment by Xhofe** [comment]
下午试一下😄

**Comment by Xhofe** [comment]
试了一下 还是没啥好的办法支持ts 我尝试转换成m3u8使用hls但是需要把视频加载完才能播放
体验太差了，但是增加了一下flv后缀的预览。
