### ISSUE TITLE
docker的默认密码是什么。

### ISSUE THREAD

**Issue by bbhxwl** [Xhofe/alist#392]
### Alist Version / Alist 版本

v

### Describe the bug / 问题描述

docker的默认密码是什么。

**Comment by Joyace** [comment]
同问

**Comment by Xhofe** [comment]
- https://hub.docker.com/r/xhofe/alist
  ![docker-hub](https://store.heytapimage.com/cdo-portal/feedback/202201/21/a2fbb612fa3e893bf5017df90d00d5f8.png)
- https://alist-doc.nn.ci/docs/install/docker
  ![alist-doc](https://store.heytapimage.com/cdo-portal/feedback/202201/21/4c5d5668d8e53cdbe55c171cbe03416a.png)
