### ISSUE TITLE
挂载和彩云访问文件目录发生错误

### ISSUE THREAD

**Issue by cxkjntm233** [Xhofe/alist#397]
### Alist Version / Alist 版本

v2.06

### Describe the bug / 问题描述
测试了下，挂载和彩云报这个错误与文件夹里面存入文件大小关，存入的单个文件大小超过了2G就会报错，低于2G就是正常的。
错误返回:
GetDiskResult. ContentList. []_39.Content. _39.Content.ContentSize. ReadInt32. overflow. 3380183338, error found in #10 byte of ...|3380183338,"contentD|..., bigger context ...|ip","contentSuffix"."zip","contentSize".3380183338,"contentDesc"."","contentType".0,"contentOrigin".|...

**Comment by Xhofe** [comment]
无法复现。

**Comment by cxkjntm233** [comment]
文件夹里面单个文件大小低于2G不会发生这种问题，大于2G才会出现

**Comment by cxkjntm233** [comment]
http://nas.imouto.fun/ALcot%20Honey%20Comb%E7%A4%BE(%E8%9C%82%E5%B7%A2%E7%A4%BE%20Alcot%E3%83%8F%E3%83%8B%E3%82%AB%E3%83%A0)

http://nas.imouto.fun/



除了第一个，其他的文件夹全报错
