### ISSUE TITLE
可不可以服务器文件列目录就好了

### ISSUE THREAD

**Issue by notemx** [Xhofe/alist#4]
如果能改成有服务器文件列目录就好了，希望能出个同款服务器文件列目录。。。

**Comment by Xhofe** [comment]
服务器文件列目录的程序已经有很多了哦 所以暂时没有这个计划😁

**Comment by notemx** [comment]
> 服务器文件列目录的程序已经有很多了哦 所以暂时没有这个计划😁

其它的是很多，喜欢现在这种风格的。希望可以加上这个功能

**Comment by dumasss163** [comment]
大佬是怎么知道服务器接口的哦?好像现在只有手机端，而没有桌面端？

**Comment by Xhofe** [comment]
> 大佬是怎么知道服务器接口的哦?好像现在只有手机端，而没有桌面端？

有web端的啊

**Comment by dumasss163** [comment]
> > 大佬是怎么知道服务器接口的哦?好像现在只有手机端，而没有桌面端？
> 
> 有web端的啊

哦，我去看看，thx
