### ISSUE TITLE
天翼云盘排序

### ISSUE THREAD

**Issue by nomoneynolife** [Xhofe/alist#407]
### Alist Version / Alist 版本

v2.0.7

### Describe the bug / 问题描述

尝试了所有设置都没办法正常排序
01.
02.
03.
~~~
这样排列

点击 我部署的 alist 首页 下面的名称能正常排序
在后台云盘设置中
排序 选“名称 ”
desc 分别选 “false” “true”
都不好使~

### Reproduction / 复现链接

### 日志 / Logs

![image](https://user-images.githubusercontent.com/53741948/150508425-bc9bb371-615f-4ee0-9bfa-9e0dbe965640.png)

**Comment by nomoneynolife** [comment]
点击 程序 首页 下面的名称能正常排序
在设置中 设置 
排序 名称 
desc false true
都不好使~

**Comment by Xhofe** [comment]
天翼云盘排序使用的是它自身的api，看起来他的api也是有问题的，官网排序也不是 01-02-03的。
下个版本给他改成本地排序吧。
