### ISSUE TITLE
Feature Request: 多盘符支持

### ISSUE THREAD

**Issue by MFYDev** [Xhofe/alist#41]
建议增加此功能，功能预览类似于GoIndex里的多盘符切换功能。

需要这个功能的目的主要是在于可以在单域名单独页面中只显示对应盘符对应的文件夹以及相关内容，感觉这个功能需求挺大的。

Goindex中的盘符使用的是类似于 https://goindex/0:/ 这种的，盘符默认为0，1，2依次增加。

或者能把这个功能做成带单独开关的也可以，那样就更好了。

**Comment by Xhofe** [comment]
已在[v1.0.1](https://github.com/Xhofe/alist/releases/tag/v1.0.1)中实现
