### ISSUE TITLE
5d72229 从这个 flac 文件获取到的的封面为空白

### ISSUE THREAD

**Issue by wc7086** [Xhofe/alist#423]
### Alist Version / Alist 版本

5d72229

### Describe the bug / 问题描述

直接将以下文件上传到网盘后在 alist 打开即可复现。

https://transfer.sh/Mi4WV1/%E4%BC%8D%E4%BD%B0%20&%20China%20Blue%20-%20%E6%9E%AB%E5%8F%B6.flac

**Comment by Xhofe** [comment]
封面为对应存储提供的缩略图，并不是由程序获取。

**Comment by wc7086** [comment]
我看 wav 没得到封面显示了预设图片，但这个 flac 没得到封面也没显示预设图片，还以为是获取失败...
