### ISSUE TITLE
粗问题了!最新安装完页面空白的原因来了!不解决用不了!

### ISSUE THREAD

**Issue by BILLfreevpn** [Xhofe/alist#428]
### Alist Version / Alist 版本

都有问题

### Describe the bug / 问题描述

有点夸大其词,但绝对是大问题!
配置文件'config.json'中
````````
assets​
使用的静态资源，可选local/zhimg/jsdelivr，默认为zhimg（知乎在国内的unpkg镜像，速度最快
````````
的**zhimg用不了**了,导致有两个js加载不出来
**更改为'jsdelivr'即可解决!**

**Comment by BILLfreevpn** [comment]
对了,作者你的demo也记得更一下

**Comment by Xhofe** [comment]
只是你打不开而已。。我这里正常
