### ISSUE TITLE
使用Actions最新版构建的程序下载有密码文件显示密码错误

### ISSUE THREAD

**Issue by MFYDev** [Xhofe/alist#43]
复现步骤：

1. 从actions下载最新版的 alist 和 alist-web
2. 上传测试文件 test.password-test 至根目录
3. 输入密码正确后可以前端访问
4. 点击下载按钮之后，可以看到密码成功变成哈希，但是返回如下密码错误 error
`{"meta":{"code":401,"msg":"wrong password."}}`

复现概率100%

**Comment by Xhofe** [comment]
看了一下 确实我把hash写反了😅 下午来改

**Comment by MFYDev** [comment]
哈哈，好的好的
