### ISSUE TITLE
加密路径 访问问题

### ISSUE THREAD

**Issue by weizai408** [Xhofe/alist#432]
### Alist Version / Alist 版本

最新版

### Describe the bug / 问题描述

如果加密前 打开过路径，然后加密该路径 再访问该路径时 不会提示输入密码

**Comment by Xhofe** [comment]
退出登录了吗

**Comment by weizai408** [comment]
windows10 edge  先访问自己的根目录，然后进元信息里面 加密根目录 /  .  即使退出管理员 然后访问根目录 照样不提示输入密码。 换一个浏览器  就会提示。

**Comment by Xhofe** [comment]
看请求头中的authorization 有信息就是没退出登录。

**Comment by Xhofe** [comment]
换浏览器能提示就没问题
