### ISSUE TITLE
复制直连失效，前面没有网址

### ISSUE THREAD

**Issue by zhucaidan** [Xhofe/alist#44]
一个资源放在带密码文件夹里的，点复制直连是这样

/d/root/软件工具/cn_office_professional_plus_2016_x86_x64_dvd_6969182.iso?pw=xxx123

**Comment by Xhofe** [comment]
之前的有问题 我替换过一次前端的release，所以需要更新替换一下

**Comment by zhucaidan** [comment]
> 之前的有问题 我替换过一次前端的release，所以需要更新替换一下

v1.0.0那个不是最新的吗。。

**Comment by Xhofe** [comment]
> > 之前的有问题 我替换过一次前端的release，所以需要更新替换一下
> 
> v1.0.0那个不是最新的吗。。

是的 我替换过里面的文件
