### ISSUE TITLE
密码正确却无法登录

### ISSUE THREAD

**Issue by ding113** [Xhofe/alist#441]
### Alist Version / Alist 版本

v2.0.7​

### Describe the bug / 问题描述

使用脚本安装。
在后台登录时，多次出现密码正确但提示wrong password
实测清空浏览器缓存可解。可能是浏览器的适配问题？
测试浏览器：Safari 15.2
平台： iOS/macOS

### Reproduction / 复现链接

无

### 日志 / Logs

```shell
录屏：https://url.ygxz.ga/waKWX
```

**Comment by Xhofe** [comment]
不反代直接端口访问试试。

**Comment by ding113** [comment]
> 不反代直接端口访问试试。

简单试了下确实没有问题。
那请问反代的话没有办法解决吗

**Comment by Xhofe** [comment]
> > 不反代直接端口访问试试。
> 
> 简单试了下确实没有问题。 那请问反代的话没有办法解决吗

禁用缓存。

**Comment by ZacRenis** [comment]
特别是修改配置文件端口后就登不上了，我是用winget安装的，并使用官方教程中vbs守护进程！也出现同样问题，密码明明正确却并不能登录

**Comment by ZHANGJW1999** [comment]
> 

怎么解决啊
