### ISSUE TITLE
123网盘下载bug

### ISSUE THREAD

**Issue by 2826915729** [Xhofe/alist#449]
### Alist Version / Alist 版本

v2.0.7-0-g4bcc635-docker

### Describe the bug / 问题描述

下载文件的话文件名是正常的名称，文件却是最后上传的文件，大小也一样

### Reproduction / 复现链接

https://pan.vpshax.ml/123%E7%BD%91%E7%9B%98

**Comment by Xhofe** [comment]
通过本程序上传的？

**Comment by 2826915729** [comment]
是的

**Comment by Xhofe** [comment]
上传的时候写死了md5 没想到123会只通过md5识别文件 直接覆盖文件。所以先不要使用本程序上传，而是从官网上传，下个版本修复此问题。

**Comment by Xhofe** [comment]
Fix in v2.0.8
