### ISSUE TITLE
v1.0.1版本无法正常工作。。。

### ISSUE THREAD

**Issue by zhucaidan** [Xhofe/alist#45]
1、首页会一直转圈
2、rebuild提示 drive isn't exist.
3、收益一直提示更新，但是前后端都已经是最新版了

**Comment by Xhofe** [comment]
配置文件有修改 我等会来写

**Comment by zhucaidan** [comment]
好的。。辛苦，是不是把conf.yml的example放到release里会比较好

**Comment by liuyunwuhen** [comment]
> 好的。。辛苦，是不是把conf.yml的example放到release里会比较好
支持
我也直接残了，不停提示更新

**Comment by szsyzx** [comment]
坐等老大更新

**Comment by Xhofe** [comment]
现在应该可以了。

**Comment by szsyzx** [comment]
Sorry, the path you visited does not exist.
已经下载最新的了
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Xhofe/alist"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月17日(星期三) 中午1:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Xhofe/alist] v1.0.1版本无法正常工作。。。 (#45)





 
现在应该可以了。

**Comment by Xhofe** [comment]
> Sorry, the path you visited does not exist. 已经下载最新的了 

需要修改配置文件以及手动rebuild一下，具体见文档

**Comment by szsyzx** [comment]
手动rebuild一下 具体怎么操作
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Xhofe/alist"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月17日(星期三) 中午1:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Xhofe/alist] v1.0.1版本无法正常工作。。。 (#45)





  
Sorry, the path you visited does not exist. 已经下载最新的了
  
需要修改配置文件以及手动rebuild一下，具体见文档

**Comment by Xhofe** [comment]
> 手动rebuild一下 具体怎么操作 

页面底部rebuild点一下输入密码然后确定，每个盘都需要rebuild。

**Comment by zhucaidan** [comment]
可以了，good good

**Comment by holll** [comment]
无论是否输入正确密码，均显示drive isn't exist
server:
  port: "5244"
  search: true
  static: dist
  site_url: '*'
  password: "123456"
ali_drive:
  api_url: https://api.aliyundrive.com/v2
  max_files_count: 3000
  drives:
  - refresh_token: 45******17b
    root_folder: 60******036
    name: drive0
    password: ""
    hide: false

**Comment by Xhofe** [comment]
> 无论是否输入正确密码，均显示drive isn't exist
> 
> server:
> 
>   port: "5244"
> 
>   search: true
> 
>   static: dist
> 
>   site_url: '*'
> 
>   password: "123456"
> 
> ali_drive:
> 
>   api_url: https://api.aliyundrive.com/v2
> 
>   max_files_count: 3000
> 
>   drives:
> 
>   - refresh_token: 45******17b
> 
>     root_folder: 60******036
> 
>     name: drive0
> 
>     password: ""
> 
>     hide: false

每个盘第一次均需rebuild一下哈😁

**Comment by holll** [comment]
> > 无论是否输入正确密码，均显示drive isn't exist
> > server:
> > port: "5244"
> > search: true
> > static: dist
> > site_url: '*'
> > password: "123456"
> > ali_drive:
> > api_url: https://api.aliyundrive.com/v2
> > max_files_count: 3000
> > drives:
> > 
> > * refresh_token: 45******17b
> >   root_folder: 60******036
> >   name: drive0
> >   password: ""
> >   hide: false
> 
> 每个盘第一次均需rebuild一下哈😁

作者大大，我就只有一个盘，在点击页面底部rebuid时，就是发生drive isn't exist。edge已开启调试模式禁用缓存，应该不是缓存问题。我拿您的实例站试了，密码错误会有password wrong提示，但我搭建的，就只有drive isn't exist

**Comment by Xhofe** [comment]
> > > 无论是否输入正确密码，均显示drive isn't exist
> 
> > > server:
> 
> > > port: "5244"
> 
> > > search: true
> 
> > > static: dist
> 
> > > site_url: '*'
> 
> > > password: "123456"
> 
> > > ali_drive:
> 
> > > api_url: https://api.aliyundrive.com/v2
> 
> > > max_files_count: 3000
> 
> > > drives:
> 
> > > 
> 
> > > * refresh_token: 45******17b
> 
> > >   root_folder: 60******036
> 
> > >   name: drive0
> 
> > >   password: ""
> 
> > >   hide: false
> 
> > 
> 
> > 每个盘第一次均需rebuild一下哈😁
> 
> 
> 
> 作者大大，我就只有一个盘，在点击页面底部rebuid时，就是发生drive isn't exist。edge已开启调试模式禁用缓存，应该不是缓存问题。我拿您的实例站试了，密码错误会有password wrong提示，但我搭建的，就只有drive isn't exist

发/私我一下地址

**Comment by holll** [comment]
github好像没有站内信功能，方便留下您的工作邮箱吗？


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月17日 22:46:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Xhofe/alist] v1.0.1版本无法正常工作。。。 (#45)




    
无论是否输入正确密码，均显示drive isn't exist
     
server:
     
port: "5244"
     
search: true
     
static: dist
     
site_url: '*'
     
password: "123456"
     
ali_drive:
     
api_url: https://api.aliyundrive.com/v2
     
max_files_count: 3000
     
drives:
          
refresh_token: 45******17b 
     
root_folder: 60******036
     
name: drive0
     
password: ""
     
hide: false
      
每个盘第一次均需rebuild一下哈😁
  
作者大大，我就只有一个盘，在点击页面底部rebuid时，就是发生drive isn't exist。edge已开启调试模式禁用缓存，应该不是缓存问题。我拿您的实例站试了，密码错误会有password wrong提示，但我搭建的，就只有drive isn't exist
  
发/私我一下地址

**Comment by Xhofe** [comment]
> github好像没有站内信功能，方便留下您的工作邮箱吗？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年3月17日 22:46:02 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Xhofe/alist] v1.0.1版本无法正常工作。。。 (#45) 无论是否输入正确密码，均显示drive isn't exist server: port: "5244" search: true static: dist site_url: '*' password: "123456" ali_drive: api_url: https://api.aliyundrive.com/v2 max_files_count: 3000 drives: refresh_token: 45******17b root_folder: 60******036 name: drive0 password: "" hide: false 每个盘第一次均需rebuild一下哈😁 作者大大，我就只有一个盘，在点击页面底部rebuid时，就是发生drive isn't exist。edge已开启调试模式禁用缓存，应该不是缓存问题。我拿您的实例站试了，密码错误会有password wrong提示，但我搭建的，就只有drive isn't exist 发/私我一下地址 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

i@nn.ci
