### ISSUE TITLE
更新之后白界面

### ISSUE THREAD

**Issue by xionger-096** [Xhofe/alist#455]
### Alist Version / Alist 版本

v2.0.7

### Describe the bug / 问题描述

更新之后访问网址就直接白界面，清除缓存，重启进程，通过IP访问都是白界面，请问如何解决

**Comment by Xhofe** [comment]
配置文件：config.json
assets的值从zhimg改成空即可。即：
"assets":"",

**Comment by xionger-096** [comment]
已成功解决，感谢大佬
