### ISSUE TITLE
现在直链地址又换了吗

### ISSUE THREAD

**Issue by jing5460** [Xhofe/alist#46]
http://xxxxxx.cc/d/drive0/王琪把《可可托海的牧羊人》带到2021春晚现场 凄美旋律动人十分神曲属性超级洗脑【综艺风向标】.mp4?pw=907325c69271ddf0

**Comment by Xhofe** [comment]
drive0是可以自己定义的 以前是默认一个盘root ，现在可以添加多个，drive0是我随便写的 吧第一个盘name改成root重启就跟之前一样了

**Comment by jing5460** [comment]
我一下子添加了四个盘,  只能用第一个!

**Comment by Xhofe** [comment]
添加之后都需要rebuild

**Comment by jing5460** [comment]
只显示 两个盘

**Comment by Xhofe** [comment]
看一下配置文件和地址

**Comment by jing5460** [comment]
建议直链地址以后可以固定统一,每次更改之后,网站上的所有地址也跟着失效,网址链接多的时候更改很麻烦!

**Comment by jing5460** [comment]
https://img.rruu.net/image/6052cdc957dcb

**Comment by Xhofe** [comment]
这次改动并没有改变直链地址啊只要盘名为root就跟上一版本一样

**Comment by jing5460** [comment]
https://img.rruu.net/image/6052ce198eb51

**Comment by jing5460** [comment]
只显示了两个盘,第二个盘用不了

**Comment by Xhofe** [comment]
> 只显示了两个盘,第二个盘用不了

发/私一下地址哈

**Comment by Xhofe** [comment]
修改配置文件后需要重启

**Comment by jing5460** [comment]
> 修改配置文件后需要重启

http://aliyunpan.4kyu.cc/

**Comment by jing5460** [comment]
日志https://img.rruu.net/image/6052cf9980702

**Comment by Xhofe** [comment]
>  日志https://img.rruu.net/image/6052cf9980702

你这次启动是失败的 端口被占用 运行的还是上一次的结果 需要杀掉原先的进程：pkill alist 再启动

**Comment by jing5460** [comment]
好了,这么说我现在四个盘的帐号只需要一个域名就可以了?

**Comment by jing5460** [comment]
https://img.rruu.net/image/6052d176ea3ef

**Comment by Xhofe** [comment]
是的。

**Comment by Xhofe** [comment]
> https://img.rruu.net/image/6052d176ea3ef

自行修改name 不是一定要填手机号

**Comment by jing5460** [comment]
可以中文吗

**Comment by Xhofe** [comment]
> 可以中文吗
> 
> 

可以的

**Comment by jing5460** [comment]
d/root/电影 一只鱼/僵尸（七日重生）.超清国粤双语中字.mp4?pw=eb0a65cc39739320
现在的直链链接必需添加  Pw=后面这一段,  不然无法解析出来

**Comment by Xhofe** [comment]
> d/root/电影 一只鱼/僵尸（七日重生）.超清国粤双语中字.mp4?pw=eb0a65cc39739320
> 
> 现在的直链链接必需添加  Pw=后面这一段,  不然无法解析出来

那是因为你的盘/文件夹设置了密码，不添加的话就没有了。不设置这一串的话就可以用直链绕过密码了。

**Comment by jing5460** [comment]
取消了这个设置  , 后面那串怎么还是存在

**Comment by Xhofe** [comment]
> 取消了这个设置 , 后面那串怎么还是存在

删除密码也需要rebuild。

**Comment by jing5460** [comment]
https://img.rruu.net/image/6052fe1338f4e
好像不行啊

**Comment by Xhofe** [comment]
> https://img.rruu.net/image/6052fe1338f4e
> 
> 好像不行啊
> 
> 

填''->重启->rebuild

**Comment by jing5460** [comment]
哪个位置

**Comment by Xhofe** [comment]
> 哪个位置
> 
> 

password

**Comment by jing5460** [comment]
https://img.rruu.net/image/605300f1bf436

**Comment by Xhofe** [comment]
下面那个 上面那个用于重建目录是必填的 不填无法重建

**Comment by jing5460** [comment]
password: password #用于重建目录
password: #该盘密码，空则不设密码，修改需要重建生效

**Comment by jing5460** [comment]
https://ae01.alicdn.com/kf/U3f7d8ae2c2694256a0b39578aee3470dK.jpg
这样子吗

**Comment by Xhofe** [comment]
> https://ae01.alicdn.com/kf/U3f7d8ae2c2694256a0b39578aee3470dK.jpg
> 
> 这样子吗

……填''
后面的是步骤

**Comment by jing5460** [comment]
留空无法进入网盘

**Comment by jing5460** [comment]
非得提示密码登录

**Comment by Xhofe** [comment]
吧数据库删了重启 再去rebuild

**Comment by jing5460** [comment]
好了, 非常感谢大佬耐心提点!
