### ISSUE TITLE
访问alist时报错"We're sorry but alist doesn't work properly without JavaScript enabled. Please enable it to continue"

### ISSUE THREAD

**Issue by luckyhacking** [Xhofe/alist#468]
### Alist Version / Alist 版本

v2.0.8

### Describe the bug / 问题描述

![image](https://user-images.githubusercontent.com/8591495/151953713-45c3b032-661e-421d-8008-43715eddb7fe.png)

使用docker部署, 日志返回200, 但是浏览器中无法访问;

**Comment by Xhofe** [comment]
https://alist-doc.nn.ci/docs/common-question#%E5%85%B3%E4%BA%8E%E6%B5%8F%E8%A7%88%E5%99%A8%E6%94%AF%E6%8C%81%E5%BA%A6

换个浏览器

**Comment by luckyhacking** [comment]
@Xhofe 默认浏览器chrome 97.0.4692.99和safari都无法访问, 应该不是浏览器的问题

**Comment by Xhofe** [comment]
地址

**Comment by luckyhacking** [comment]
https://alist.wrss.top/

**Comment by luckyhacking** [comment]
搞定, 多谢
