### ISSUE TITLE
提两点建议

### ISSUE THREAD

**Issue by naicfeng** [Xhofe/alist#47]
1.缓存不应该直接缓存全部资源。例：我有一个目录下好几万文件，会导致数据库事务锁超时。
（思路：分层，仅缓存到2-3层目录。后续访问数据库没有的内容先检查一遍，有则缓存到数据库，无则返回404）

2.列表页面应该加入分页功能，不应单独一个`max_files_count`全敲死了

**Comment by Xhofe** [comment]
收到 感谢你的建议🙏

**Comment by naicfeng** [comment]
> 收到 感谢你的建议🙏

了解到难度了，阿里是用`parent_file_id`来标定文件的，通过目录无法直接取。
第一条建议应该无法实现，但是它提供了`next_marker`还是用分页比较好。在ReBuild的时候给前端一个回调，避免http超时。

**Comment by bebestmaple** [comment]
是否可以通过使用redis等缓存组件而不是使用数据库，这样既可以提升速度，而且也可以通过设置过期时间等手段达到定时更新目录的目的

**Comment by naicfeng** [comment]
> 是否可以通过使用redis等缓存组件而不是使用数据库，这样既可以提升速度，而且也可以通过设置过期时间等手段达到定时更新目录的目的

这个思路不错

**Comment by Xhofe** [comment]
> 是否可以通过使用redis等缓存组件而不是使用数据库，这样既可以提升速度，而且也可以通过设置过期时间等手段达到定时更新目录的目的

其实以前就是这样做的，但是这样做无法按照文件结构形式的url访问，所以之后才引入了数据库。

**Comment by naicfeng** [comment]
> > 是否可以通过使用redis等缓存组件而不是使用数据库，这样既可以提升速度，而且也可以通过设置过期时间等手段达到定时更新目录的目的
> 
> 其实以前就是这样做的，但是这样做无法按照文件结构形式的url访问，所以之后才引入了数据库。

每一级目录的目录名作为key，存储当前目录下的文件名。
查询不用一次性查询出来，一级一级往下查询，就可以根据文件结构访问。

```
{
root:{folder1,folder2}
}

{
folder1:{
    file1:{pid:xxx},
    file2:{pid:xxx}
    }
}

```
 GET `url/root/folder1/file2` to get `pid:xxx`

不知道这样可行不

**Comment by Xhofe** [comment]
> > > 是否可以通过使用redis等缓存组件而不是使用数据库，这样既可以提升速度，而且也可以通过设置过期时间等手段达到定时更新目录的目的
> > 
> > 
> > 其实以前就是这样做的，但是这样做无法按照文件结构形式的url访问，所以之后才引入了数据库。
> 
> 每一级目录的目录名作为key，存储当前目录下的文件名。
> 查询不用一次性查询出来，一级一级往下查询，就可以根据文件结构访问。
> 
> ```
> {
> root:{folder1,folder2}
> }
> 
> {
> folder1:{
>     file1:{pid:xxx},
>     file2:{pid:xxx}
>     }
> }
> ```
> 
> GET `url/root/folder1/file2` to get `pid:xxx`
> 
> 不知道这样可行不

这样文件多对内存压力有点大啊。。

**Comment by naicfeng** [comment]
> > > > 是否可以通过使用redis等缓存组件而不是使用数据库，这样既可以提升速度，而且也可以通过设置过期时间等手段达到定时更新目录的目的
> > > 
> > > 
> > > 其实以前就是这样做的，但是这样做无法按照文件结构形式的url访问，所以之后才引入了数据库。
> > 
> > 
> > 每一级目录的目录名作为key，存储当前目录下的文件名。
> > 查询不用一次性查询出来，一级一级往下查询，就可以根据文件结构访问。
> > ```
> > {
> > root:{folder1,folder2}
> > }
> > 
> > {
> > folder1:{
> >     file1:{pid:xxx},
> >     file2:{pid:xxx}
> >     }
> > }
> > ```
> > 
> > 
> > GET `url/root/folder1/file2` to get `pid:xxx`
> > 不知道这样可行不
> 
> 这样文件多对内存压力有点大啊。。

只是一个思路。

其实主要是写入的时候超时比较影响。
构建目录的时候，先写到缓存(因为网络因素，影响大)。
等全部从网络获取完毕后。再，事务→删除内容→写入内容→提交事务

**Comment by bebestmaple** [comment]
> > > > > 是否可以通过使用redis等缓存组件而不是使用数据库，这样既可以提升速度，而且也可以通过设置过期时间等手段达到定时更新目录的目的
> > > > 
> > > > 
> > > > 其实以前就是这样做的，但是这样做无法按照文件结构形式的url访问，所以之后才引入了数据库。
> > > 
> > > 
> > > 每一级目录的目录名作为key，存储当前目录下的文件名。
> > > 查询不用一次性查询出来，一级一级往下查询，就可以根据文件结构访问。
> > > ```
> > > {
> > > root:{folder1,folder2}
> > > }
> > > 
> > > {
> > > folder1:{
> > >     file1:{pid:xxx},
> > >     file2:{pid:xxx}
> > >     }
> > > }
> > > ```
> > > 
> > > 
> > > GET `url/root/folder1/file2` to get `pid:xxx`
> > > 不知道这样可行不
> > 
> > 这样文件多对内存压力有点大啊。。
> 
> 只是一个思路。
> 
> 其实主要是写入的时候超时比较影响。
> 构建目录的时候，先写到缓存(因为网络因素，影响大)。
> 等全部从网络获取完毕后。再，事务→删除内容→写入内容→提交事务

1. 主要问题应该是过多文件写入数据库的影响，如上所述，可以选择先写入缓存，写入数据库也可以用队列的形式削峰
2. 针对文件过多对内存压力大的问题，个人还没有什么概念，大概多少文件会占用多大的内存，可以请教下不？
