### ISSUE TITLE
从后台直接返回首页时未应用自定义head

### ISSUE THREAD

**Issue by Joket-abc** [Xhofe/alist#470]
### Alist Version / Alist 版本

v2.0.8

### Describe the bug / 问题描述

1、进入后台
2、点击右下角返回首页按钮
自定义head未被应用
![image](https://user-images.githubusercontent.com/61594596/152160221-ff12f206-4331-4df5-9512-36b6b6119357.png)

自定义body似乎也未被应用，但是我没有设置自定义body，所以没有测试
![image](https://user-images.githubusercontent.com/61594596/152160315-494b26bc-38b5-437a-ac48-eb44761bc6f9.png)

**Comment by Xhofe** [comment]
spa路由跳转就是这样的，预期行为，非bug。
