### ISSUE TITLE
这个菜单栏显示不全，算是BUG么

### ISSUE THREAD

**Issue by ddd-zero** [Xhofe/alist#471]
### Alist Version / Alist 版本

lastest

### Describe the bug / 问题描述

![QQ截图20220203015220](https://user-images.githubusercontent.com/57771987/152209722-2e6d0859-36ca-4ef3-a07a-0486b0e98acc.png)

下面的选项都看不见了。

**Comment by Xhofe** [comment]
- #227
- #418
