### ISSUE TITLE
用via等浏览器下载文件是吧

### ISSUE THREAD

**Issue by GaodaGG** [Xhofe/alist#481]
### Alist Version / Alist 版本

v2.0.9

### Describe the bug / 问题描述

![Screenshot_20220205-025859_Via_1](https://user-images.githubusercontent.com/94783802/152587985-a6b0fa25-acb0-41cc-9545-d1c07b068312.png)
似乎仅限阿里云盘

### Reproduction / 复现链接

[复现链接](https://alist.now.sh/阿里云盘/图片/2.jpg) 

### 日志 / Logs

```shell
[GIN] 2022/02/05 - 02:53:55 | 302 |      84.576ms |   113.200.86.44 | GET      "/d/gm/pe.apk"
```

**Comment by GaodaGG** [comment]
标题是下载失败💦💦

**Comment by Xhofe** [comment]
官网能下载？ 去via浏览器或者阿里云盘反馈而不是这里。

**Comment by qyxk** [comment]
貌似勾上代理就行了吧
