### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by maple185** [Xhofe/alist#485]
### Alist Version / Alist 版本

V2.0.9

### Describe the bug / 问题描述

[alist-windows-4.0-amd64.zip](https://github.com/Xhofe/alist/releases/download/v2.0.9/alist-windows-4.0-amd64.zip)

最新V2.0.9，WINDOWS 64位服务端版本，在WIN10和WIN11下全新运行，使用alist登录后台，报错：Invalid token，V2.0.8无此情况

**Comment by Xhofe** [comment]
密码错误。

**Comment by maple185** [comment]
> 密码错误。

感谢回复，那么V2.0.9版本是修改了默认密码alist，为其他了吗？

**Comment by Xhofe** [comment]
> > 密码错误。
> 
> 感谢回复，那么V2.0.9版本是修改了默认密码alist，为其他了吗？

看文档
看文档
看文档

**Comment by maple185** [comment]
> > > 密码错误。
> > 
> > 
> > 谢谢回复，那么V2.0.9版本是修改了默认密码alist，为其他了吗？
> 
> 看文档 看 文档

感谢，已解决。

最新版本“首次运行会输出初始密码”，
