### ISSUE TITLE
path not found

### ISSUE THREAD

**Issue by rerunbug** [Xhofe/alist#49]
我感觉全天下就我一个配置出现毛病的人了
心累💔💔💔💔
https://s3.ax1x.com/2021/03/19/6WZHLd.png
https://s3.ax1x.com/2021/03/19/6WZqeA.png

**Comment by phoon** [comment]
在web页面`rebuild`重建一下目录

**Comment by rerunbug** [comment]
会提示 drive isn't exist.

**Comment by rerunbug** [comment]
> 在web页面`rebuild`重建一下目录

会提示 drive isn't exist.

**Comment by Xhofe** [comment]
私一下地址和配置文件。i@nn.ci

**Comment by vbskycn** [comment]
我的也会出现这种情况

**Comment by vbskycn** [comment]
> 私一下地址和配置文件。[i@nn.ci](mailto:i@nn.ci)

用默认的配置文件也会path not found.

**Comment by rerunbug** [comment]
> > 私一下地址和配置文件。[i@nn.ci](mailto:i@nn.ci)
> 
> 用默认的配置文件也会path not found.
已经发了 配置文件了
等等吧

**Comment by vbskycn** [comment]
错误 截图

![错误截图2.png](https://ae04.alicdn.com/kf/U55c0e69989c040beb7d55a46c016f962U.jpg)
![错误截图.png](https://sc04.alicdn.com/kf/U5bfdf4fe07d44a2388404f3873de1987O.jpg)

**Comment by vbskycn** [comment]
已经搞定，还是配置文件的问题

**Comment by rerunbug** [comment]
怎么搞的啊

**Comment by rerunbug** [comment]
> 已经搞定，还是配置文件的问题

怎么搞的啊

**Comment by rerunbug** [comment]
我发现这个问题好像是上一个版本留下的缓存导致的 
我用手机登录了 就可以
电脑重启了一遍就可以了

**Comment by Cicini** [comment]
> 已经搞定，还是配置文件的问题

我这边也有这样的问题
暂时没发现配置文件有什么地方有问题
