### ISSUE TITLE
希望可以抽时间添加Teambition

### ISSUE THREAD

**Issue by zsbai** [Xhofe/alist#5]
以前一直用的是teambition，希望可以抽时间加上（辛苦辛苦

**Comment by zsbai** [comment]
作者可以加一个赞赏码什么的，辛苦了（以前找了好长时间阿里网盘的项目

**Comment by Xhofe** [comment]
> 以前一直用的是teambition，希望可以抽时间加上（辛苦辛苦

`teambition`可以看看[这篇](https://www.52pojie.cn/thread-1320716-1-1.html)，我没有邀请码😭，以后有了的话，会看情况整合的

**Comment by Xhofe** [comment]
> 作者可以加一个赞赏码什么的，辛苦了（以前找了好长时间阿里网盘的项目

赞赏码的话，教程的博客里是有的哈，`README`也有徽章的😁

**Comment by zsbai** [comment]
> > 作者可以加一个赞赏码什么的，辛苦了（以前找了好长时间阿里网盘的项目
> 
> 赞赏码的话，教程的博客里是有的哈，`README`也有徽章的😁

找到了，请作者一杯奶茶😁

**Comment by Xhofe** [comment]
> > > 作者可以加一个赞赏码什么的，辛苦了（以前找了好长时间阿里网盘的项目
> > 
> > 
> > 赞赏码的话，教程的博客里是有的哈，`README`也有徽章的😁
> 
> 找到了，请作者一杯奶茶😁

😘谢谢你
