### ISSUE TITLE
invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by vbskycn** [Xhofe/alist#50]
Rebuild后，报这个错

![错误截图3.png](https://ae04.alicdn.com/kf/U5701477e010241b4aa196ae0e55cf72fo.jpg)

**Comment by Xhofe** [comment]
麻烦发一下日志，我好看一下是哪个地方报的错。

**Comment by vbskycn** [comment]
没有找到哪里有日志，跟目录下没有log文件

**Comment by Xhofe** [comment]
结束之前的进程直接 ./alist -debug
然后rebuild一下，看打印的日志。

**Comment by bebestmaple** [comment]
这个有点像是 token失效了
