### ISSUE TITLE
希望加密文件夹的方式加回原来的方式

### ISSUE THREAD

**Issue by ghost** [Xhofe/alist#51]
更新版本后发现加密不可用了，细看文档才知道加密方式修改 为，，，文件名后面增加.password-密码   了。。。。   

但是由于数量太多，还是希望能同时兼容旧方式的加密，也就是在 文件夹下新建'.password-密码' 就加密整个文件夹。

**Comment by Xhofe** [comment]
只需要加密外层目录，里面的内容都会被设置密码啊。

**Comment by hais1992** [comment]
> 只需要加密外层目录，里面的内容都会被设置密码啊。

是这样的，因为我需要用到其它脚本自动上传文件，且目录路径修改起来不方便。。。 密码且需两三天修改一次， 希望大佬能加回旧的加密方案~

**Comment by Xhofe** [comment]
v2之后不会再加回旧的加密方案~
