### ISSUE TITLE
webdav使用Visitor挂载后能直接看到隐藏和加密的文件及文件夹

### ISSUE THREAD

**Issue by ilay1678** [Xhofe/alist#522]
### Alist Version / Alist 版本

v2.0.9-0-ga229035

### Describe the bug / 问题描述

webdav使用Visitor挂载后能直接看到隐藏和加密的文件及文件夹

**Comment by Xhofe** [comment]
1. 实测非账号文件夹隐藏看不见
2. WebDAV不支持双重验证

**Comment by ilay1678** [comment]
> 1. 实测非账号文件夹隐藏看不见
> 2. WebDAV不支持双重验证

我是隐藏的账号级文件夹，访客账户挂载能直接看到。还是说webdav不支持账号文件夹隐藏

**Comment by Xhofe** [comment]
> > 1. 实测非账号文件夹隐藏看不见
> > 2. WebDAV不支持双重验证
> 
> 我是隐藏的账号级文件夹，访客账户挂载能直接看到。还是说webdav不支持账号文件夹隐藏

支持 忘记加了 下个版本加
