### ISSUE TITLE
123pan打开错误

### ISSUE THREAD

**Issue by love2wind** [Xhofe/alist#523]
### Alist Version / Alist 版本

v2.0.9-0-ga229035-dirty

### Describe the bug / 问题描述

添加123pan以后打开显示`请输入OrderBy`
无论添加根目录还是目录都是一样的

### Reproduction / 复现链接

https://alist.niege.ga/123pan

### 日志 / Logs

```shell
```
![image](https://user-images.githubusercontent.com/11996852/153552216-8792e0b9-dfc7-48e5-ba7a-8f317aa714dd.png)

**Comment by Xhofe** [comment]
善用搜索。
#440

**Comment by love2wind** [comment]
> 善用搜索。 #440

谢谢
