### ISSUE TITLE
文件名或路径名带有符号 # 的内容无法访问

### ISSUE THREAD

**Issue by OriLight152** [Xhofe/alist#526]
### Alist Version / Alist 版本

v2.0.9-0-ga229035-dirty

### Describe the bug / 问题描述

当路径名或文件名带有#号时，#号之后的内容会被忽略
例如访问 `Test/Test#` 文件夹包括该文件夹下所有的文件时，都会自动跳转到 `Test/Test`

演示GIF
![GIF 2022-2-11 22-05-28](https://user-images.githubusercontent.com/61224409/153605885-420eb4a9-c311-4f9b-b335-eeae832ea80e.gif)

### Reproduction / 复现链接

https://dl.amarea.cn/阿里云盘/Test#
https://dl.amarea.cn/阿里云盘/Test#/OneDrive%20%E5%85%A5%E9%97%A8.pdf
https://dl.amarea.cn/阿里云盘/Test/1#fundamentals-of-computer-graphics-4th.pdf
https://test.roxylib.com/动画/生肉/MKV收藏/『無職転生 ～異世界行ったら本気だす～』 Blu-ray Chapter 1/NCOP

**Comment by Xhofe** [comment]
提issue之前请先看看有无重复。
