### ISSUE TITLE
希望可以提供打包后的linux386文件

### ISSUE THREAD

**Issue by JobinBai** [Xhofe/alist#53]
mac上无法打包linux386文件

**Comment by Xhofe** [comment]
事实上，我并不知道如何去在amd64平台上支持CGO去交叉编译386平台的目标文件，因为sqlite3使用到了cgo，他可能会无法正常工作。但是我按照经验在[github actions build](https://github.com/Xhofe/alist/actions/runs/672157565)中添加了linux_386的构建，你可以先下载[alist_linux_386.zip](https://github.com/Xhofe/alist/files/6176742/alist_linux_386.zip)尝试一下是否可以正常工作，如果可以的话，之后会加入到release中，否则你可以自己在目标机器上进行构建：
```sh
sudo apt install golang
go env -w GO111MODULE=on
go env -w GOPROXY=https://goproxy.cn,direct
git clone https://github.com/Xhofe/alist.git
cd alist
go build alist.go
```

**Comment by JobinBai** [comment]
我直接在目标机器上构建了，可以正常使用了。感谢
