### ISSUE TITLE
加密和隐藏后输入完整路径一样可以访问

### ISSUE THREAD

**Issue by a05332481** [Xhofe/alist#534]
### Alist Version / Alist 版本

v2.0.9

### Describe the bug / 问题描述

挂载google drive后加密或者隐藏文件夹后只要输入完整路劲就可以访问，如果加密根目录/ 可以通过github.com/movie访问movie文件夹的内容

**Comment by Xhofe** [comment]
提issue之前请先1. 查阅文档 2.搜索有无重复issue或discussion。
- https://alist-doc.nn.ci/docs/setting/private#%E6%A3%80%E6%9F%A5%E7%88%B6%E6%96%87%E4%BB%B6%E5%A4%B9%E5%AF%86%E7%A0%81
- #157

**Comment by bbhxwl** [comment]
我设置了/adl   密码了，直接访问这个是需要密码，子路径访问不需要密码，浏览器无痕，并且开了 检查父文件夹密码

**Comment by Xhofe** [comment]
测试无问题：https://alist.xhofe.top/%E9%98%BF%E9%87%8C%E4%BA%91%E7%9B%98/%E5%AF%86%E7%A0%81-123456/%E6%B5%8B%E8%AF%95%E5%86%85%E9%83%A8%E6%96%87%E4%BB%B6%E5%A4%B9/%E5%AD%99%E5%AD%90%E6%96%87%E4%BB%B6%E5%A4%B9 请检查你的设置。

**Comment by bbhxwl** [comment]
> 测试无问题：https://alist.xhofe.top/%E9%98%BF%E9%87%8C%E4%BA%91%E7%9B%98/%E5%AF%86%E7%A0%81-123456/%E6%B5%8B%E8%AF%95%E5%86%85%E9%83%A8%E6%96%87%E4%BB%B6%E5%A4%B9/%E5%AD%99%E5%AD%90%E6%96%87%E4%BB%B6%E5%A4%B9 请检查你的设置。

我知道了，我是想让知道密码的人都能上传，因此我还要给每个路径设置权限，所以没有密码了。没办法让能进到目录的人有权限下载上传么，

**Comment by Xhofe** [comment]
开启上传只能针对单个文件夹，对子文件夹无效。
