### ISSUE TITLE
更版本后一直无法启动Alsit

### ISSUE THREAD

**Issue by jing5460** [Xhofe/alist#535]
### Alist Version / Alist 版本

v2.0.9

### Describe the bug / 问题描述

之前配置好的data.db  一直 无法启动！
删掉再次配置可行，用一两天会502，然后再次无法启动
试过注释zhimg、jsdelivr。
试过Issue 提供的方法！！！
如下图，每次启动都一直卡在最后这个位置 无法启动.

### Reproduction / 复现链接

{
  "address": "0.0.0.0",
  "port": 5244,
  "assets": "jsdelivr",
  "database": {
    "type": "sqlite3",
    "user": "",
    "password": "",
    "host": "",
    "port": 0,
    "name": "",
    "table_prefix": "x_",
    "db_file": "data/data.db",
    "ssl_mode": "disable"
  },
  "scheme": {
    "https": false,
    "cert_file": "",
    "key_file": ""
  },
  "cache": {
    "expiration": 60,
    "cleanup_interval": 120
  }
}

### 日志 / Logs

```shell
![image](https://user-images.githubusercontent.com/38358681/153812187-c29cc566-9e29-408c-af48-657308653c1c.png)
```
![image](https://user-images.githubusercontent.com/38358681/153813904-5df93745-529b-4ed1-a191-af5c669a657f.png)

INFO[2022-02-14 14:44:11] init log...                                  
INFO[2022-02-14 14:44:11] register driver: [123Pan]                    
INFO[2022-02-14 14:44:11] register driver: [139Yun]                    
INFO[2022-02-14 14:44:11] register driver: [189Cloud]                  
INFO[2022-02-14 14:44:11] register driver: [AliDrive]                  
INFO[2022-02-14 14:44:11] register driver: [Alist]                     
INFO[2022-02-14 14:44:11] register driver: [Baidu.Disk]                
INFO[2022-02-14 14:44:11] register driver: [FTP]                       
INFO[2022-02-14 14:44:11] register driver: [GoogleDrive]               
INFO[2022-02-14 14:44:11] register driver: [Lanzou]                    
INFO[2022-02-14 14:44:11] register driver: [MediaTrack]                
INFO[2022-02-14 14:44:11] register driver: [Native]                    
INFO[2022-02-14 14:44:11] register driver: [Onedrive]                  
INFO[2022-02-14 14:44:11] register driver: [PikPak]                    
INFO[2022-02-14 14:44:11] register driver: [S3]                        
INFO[2022-02-14 14:44:11] register driver: [ShandianPan]               
INFO[2022-02-14 14:44:11] register driver: [Teambition]                
INFO[2022-02-14 14:44:11] register driver: [WebDav]                    
INFO[2022-02-14 14:44:11] register driver: [Yandex.Disk]               
INFO[2022-02-14 14:44:11] reading config file: data/config.json        
INFO[2022-02-14 14:44:11] init cron...                                 
INFO[2022-02-14 14:44:11] init model...                                
INFO[2022-02-14 14:44:11] auto migrate model...                        
INFO[2022-02-14 14:44:11] init settings...                             
INFO[2022-02-14 14:44:11] init accounts...                             
INFO[2022-02-14 14:44:11] start init account: [阿里云盘「5474」], type: [AliDrive] 
INFO[2022-02-14 14:44:14] success init account: 阿里云盘「5474」, type: AliDrive 
INFO[2022-02-14 14:44:14] start init account: [阿里云盘「5460」], type: [AliDrive] 
INFO[2022-02-14 14:44:15] success init account: 阿里云盘「5460」, type: AliDrive 
INFO[2022-02-14 14:44:15] start init account: [阿里云盘「2405」], type: [AliDrive] 
INFO[2022-02-14 14:44:16] success init account: 阿里云盘「2405」, type: AliDrive 
INFO[2022-02-14 14:44:16] start init account: [阿里云盘「0204」], type: [AliDrive] 
INFO[2022-02-14 14:44:17] success init account: 阿里云盘「0204」, type: AliDrive 
INFO[2022-02-14 14:44:17] start init account: [阿里云盘「3692」], type: [AliDrive] 
INFO[2022-02-14 14:44:18] success init account: 阿里云盘「3692」, type: AliDrive 
INFO[2022-02-14 14:44:18] start init account: [阿里云盘「3443」], type: [AliDrive] 
INFO[2022-02-14 14:44:19] success init account: 阿里云盘「3443」, type: AliDrive 
INFO[2022-02-14 14:44:19] start init account: [阿里云盘「4129」], type: [AliDrive] 
INFO[2022-02-14 14:44:21] success init account: 阿里云盘「4129」, type: AliDrive 
INFO[2022-02-14 14:44:21] start init account: [天翼云盘], type: [189Cloud] 
INFO[2022-02-14 14:44:26] success init account: 天翼云盘, type: 189Cloud   
INFO[2022-02-14 14:44:26] start init account: [和彩云盘], type: [139Yun]

**Comment by Xhofe** [comment]
暂时的请求未配置超时，你的服务器与和彩云的连接有问题，所以一直连不上卡在这里了。
删除掉和彩云的账号就行了。

**Comment by jing5460** [comment]
在另一台服务器上是可以的，之前也发过给你试过

**Comment by Xhofe** [comment]
所以你这台服务器和彩云有问题啊

**Comment by jing5460** [comment]
果然是这个和彩云问题
