### ISSUE TITLE
一些 actions 的

### ISSUE THREAD

**Issue by xrkffgg** [Xhofe/alist#547]
### Alist Version / Alist 版本

v2

### Describe the bug / 问题描述

 - https://github.com/Xhofe/alist/blob/v2/.github/workflows/issue_month_statistics.yml 这个 month-statistics 其实是有些 bug 的，暂不建议使用。。。后期倒是可以关注下 https://github.com/actions-cool/issues-month-statistics
 - https://github.com/Xhofe/alist/blob/v2/.github/workflows/issue_wontfix.yml 可以写成 `actions: 'create-comment, close-issue'`

顺便 v3 发布~ 欢迎使用，有问题 https://github.com/actions-cool/issues-helper/issues

### Reproduction / 复现链接

none

### 日志 / Logs

```shell
none
```

**Comment by Xhofe** [comment]
好的 感谢。
