### ISSUE TITLE
可以请教一下如何反代到网站的二级目录吗？

### ISSUE THREAD

**Issue by zhouguangyou1994** [Xhofe/alist#55]
正常的反代二级目录的方法反代这个无法正常使用，有大佬弄过吗？请教一下

**Comment by Xhofe** [comment]
以反代到/alist/二级目录做演示：
修改以下文件：
https://github.com/Xhofe/alist-web/blob/7fdd9809fcfea81774840c81f189753171d1d04b/vue.config.js#L3
publicPath修改为相对路径'./'（可能会有问题）或反代的二级绝对路径'/alist/'
https://github.com/Xhofe/alist-web/blob/7fdd9809fcfea81774840c81f189753171d1d04b/.env.production#L3
VUE_APP_API_URL修改为'/alist/'（可能会有问题）或二级网址'https://xxx.com/alist/'
然后"yarn && yarn build"打包生成dist部署，附nginx反代配置：
```nginx
    location /alist/ {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_redirect off;
        proxy_pass http://127.0.0.1:5244/;
        
        # 如果您要使用本地存储策略，请将下一行注释符删除，并更改大小为理论最大文件尺寸
        client_max_body_size 20000m;
    }
```

**Comment by naicfeng** [comment]
> ```nginx
> 如果您要使用本地存储策略，请将下一行注释符删除，并更改大小为理论最大文件尺寸
> ```

怎么感觉是从`cloudreve`复制过来的，(dog

**Comment by Xhofe** [comment]
> > ```nginx
> > 如果您要使用本地存储策略，请将下一行注释符删除，并更改大小为理论最大文件尺寸
> > ```
> 
> 怎么感觉是从`cloudreve`复制过来的，(dog

是的😂忽略最后一行哈

**Comment by zhouguangyou1994** [comment]
> > > ```nginx
> > > 如果您要使用本地存储策略，请将下一行注释符删除，并更改大小为理论最大文件尺寸
> > > ```
> > 
> > 
> > 怎么感觉是从`cloudreve`复制过来的，(dog
> 
> 是的😂忽略最后一行哈

**Comment by zhouguangyou1994** [comment]
> 以反代到/alist/二级目录做演示：
> 修改以下文件：
> https://github.com/Xhofe/alist-web/blob/7fdd9809fcfea81774840c81f189753171d1d04b/vue.config.js#L3
> publicPath修改为相对路径'./'（可能会有问题）或反代的二级绝对路径'/alist/'
> https://github.com/Xhofe/alist-web/blob/7fdd9809fcfea81774840c81f189753171d1d04b/.env.production#L3
> VUE_APP_API_URL修改为'/alist/'（可能会有问题）或二级网址'https://xxx.com/alist/'
> 然后"yarn && yarn build"打包生成dist部署，附nginx反代配置：
> 
> ```nginx
>     location /alist/ {
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_set_header Host $http_host;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_redirect off;
>         proxy_pass http://127.0.0.1:5244/;
>     }
> ```



> 以反代到/ alist /二级目录做演示：
> 修改以下文件：
> [https](https://github.com/Xhofe/alist-web/blob/7fdd9809fcfea81774840c81f189753171d1d04b/vue.config.js#L3) : [//github.com/Xhofe/alist-web/blob/7fdd9809fcfea81774840c81f189753171d1d04b/vue.config.js#L3](https://github.com/Xhofe/alist-web/blob/7fdd9809fcfea81774840c81f189753171d1d04b/vue.config.js#L3)
> publicPath修改为相对路径'./ '（可能会有问题）或反代的二级绝对路径'/ ALIST / '
> https://github.com/Xhofe/alist-web/blob/7fdd9809fcfea81774840c81f189753171d1d04b/.env.production#L3
> VUE_APP_API_URL修改为'/ ALIST /'（可能会有问题）或二级网址' https://xxx.com/alist/ '
> 然后“ yarn && yarn build”打包生成分布，附nginx反代配置：
> 
> ```nginx
>     位置 / alist / {
>          proxy_set_header X-Forwarded-For $ proxy_add_x_forwarded_for ;
>         proxy_set_header主机$ http_host ;
>         proxy_set_header X-Real-IP $ remote_addr ;
>         proxy_redirect关闭;
>         proxy_pass http://127.0.0.1:5244/;
>     }
> ```

按教程亲测不行 ，
二级目录是这样的，导致获取失败
https://alist.xxx.de/alist/api/path 
{path: "drive0", password: ""}
password: ""
path: "alist/drive0"   //正常的显示是path: "drive0"

https://alist.xxx.de/alist/api/rebuild/alist/密码
rebuild请求的链接也是不对的，手动修改成https://alist.xxx.de/alist/api/rebuild/drive0/密码，貌似正常

应该就是path这方面的原因，目前使用二级域名了，本来打算二级目录的，一直没办法成功

**Comment by Xhofe** [comment]
自测 没有问题https://api.xhofe.top/alist/

**Comment by zhouguangyou1994** [comment]
> 自测 没有问题https://api.xhofe.top/alist/

修改以下文件：
https://github.com/Xhofe/alist-web/blob/7fdd9809fcfea81774840c81f189753171d1d04b/vue.config.js#L3
publicPath修改为反代的二级绝对路径'/alist/'
https://github.com/Xhofe/alist-web/blob/7fdd9809fcfea81774840c81f189753171d1d04b/.env.production#L3
VUE_APP_API_URL修改为'/alist/'（可能会有问题）或二级网址'https://xxx.com/alist/'
我的反代这样才行
`    location ~ ^/alist/(.*) {
        rewrite ^/alist/(.*)$ /$1;break;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_redirect off;
        proxy_pass http://127.0.0.1:5244;
    }`
成功了

**Comment by vickunwu** [comment]
可否将二级目录添加成配置项呢？

**Comment by ihipop** [comment]
这样太麻烦了，可否考虑二级路径从浏览器里面获取啊？虚拟路由都是@开头的，应该简单修改这里就可以了吧

https://github.com/alist-org/alist-web/blob/af3e2c859602501478f57478fb80e5fc794d5426/src/utils/address.ts#L2-L4

**Comment by jerrychen417** [comment]
> 自测 没有问题https://api.xhofe.top/alist/

怎么配置的可以发一下吗

**Comment by saury** [comment]
[如何对子目录进行反向代理？](https://alist.nn.ci/zh/faq/howto.html#%E5%A6%82%E4%BD%95%E5%AF%B9%E5%AD%90%E7%9B%AE%E5%BD%95%E8%BF%9B%E8%A1%8C%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86)
