### ISSUE TITLE
蓝奏云链接分享，点开具体文件报这个错，是什么原因哇

### ISSUE THREAD

**Issue by dddmw01** [Xhofe/alist#554]
### Alist Version / Alist 版本

2

### Describe the bug / 问题描述

错误
json: cannot unmarshal number into Go struct field LanzouLinkResp.url of type string

### Reproduction / 复现链接

无

### 日志 / Logs

```shell
错误
json: cannot unmarshal number into Go struct field LanzouLinkResp.url of type string
```

**Comment by Xhofe** [comment]
提供一下分享链接。
