### ISSUE TITLE
打开网页是白屏状态

### ISSUE THREAD

**Issue by xjc19960724** [Xhofe/alist#557]
### Alist Version / Alist 版本

2.0.10

### Describe the bug / 问题描述

打开网页是白屏状态，已改配置文件中的temp_dir的值由空改为data/tem
![屏幕截图 2022-02-17 234332](https://user-images.githubusercontent.com/61687015/154517301-833ad166-3847-4e2e-9473-e046ee10efd2.png)
p

**Comment by doocii** [comment]
https://unpkg.zhimg.com/alist-web@2.0.7/dist/assets/vendor.442eedbd.js 链接挂了

**Comment by Xhofe** [comment]
> https://unpkg.zhimg.com/alist-web@2.0.7/dist/assets/vendor.442eedbd.js 链接挂了

zhimg cdn有问题，请不要再使用。

**Comment by tidymoon** [comment]
高峰期的话jsdelivr间歇性挂
能否考虑换一下cdn呢？

**Comment by Xhofe** [comment]
> 高峰期的话jsdelivr间歇性挂 能否考虑换一下cdn呢？

谁给我提供cdn？？？

**Comment by tidymoon** [comment]
> 

emmm也是
能否提供一个选项来选择从自己的（不是指用户）的服务器来加载呢
看了一下好像好像也就600kb左右吧 我觉得应该问题不大

**Comment by tidymoon** [comment]
> > 高峰期的话jsdelivr间歇性挂 能否考虑换一下cdn呢？
> 
> 谁给我提供cdn？？？

emmm也是
能否提供一个选项来选择从自己的（不是指用户）的服务器来加载呢
看了一下好像好像也就600kb左右吧 我觉得应该问题不大

**Comment by Xhofe** [comment]
> > > 高峰期的话jsdelivr间歇性挂 能否考虑换一下cdn呢？
> > 
> > 
> > 谁给我提供cdn？？？
> 
> emmm也是 能否提供一个选项来选择从自己的（不是指用户）的服务器来加载呢 看了一下好像好像也就600kb左右吧 我觉得应该问题不大

？？这是什么 https://alist-doc.nn.ci/docs/setting/config#assets

**Comment by xiaocsl** [comment]
IOS 设备都是空白也,试了多台设备.只有 IOS 正常显示页面.
手头没调试环境,简单抓下包看了下,IOS端加载完资源以后,没有任何 /api/* 路径的请求.

**Comment by Xhofe** [comment]
> IOS 设备都是空白也,试了多台设备.只有 IOS 正常显示页面.
> 手头没调试环境,简单抓下包看了下,IOS端加载完资源以后,没有任何 /api/* 路径的请求.

https://alist-doc.nn.ci/docs/common-question#%E5%85%B3%E4%BA%8E%E6%B5%8F%E8%A7%88%E5%99%A8%E6%94%AF%E6%8C%81%E5%BA%A6

**Comment by xiaocsl** [comment]
> > IOS 设备都是空白也,试了多台设备.只有 IOS 正常显示页面.
> > 手头没调试环境,简单抓下包看了下,IOS端加载完资源以后,没有任何 /api/* 路径的请求.
> 
> https://alist-doc.nn.ci/docs/common-question#%E5%85%B3%E4%BA%8E%E6%B5%8F%E8%A7%88%E5%99%A8%E6%94%AF%E6%8C%81%E5%BA%A6

查了下.因为需求手头两个 iOS 设备一年多没更新系统. Safari 版本"太旧"

原因在:[https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener#browser_compatibility](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener#browser_compatibility)
``` JavaScript
function _A(e) {
    if (!("matchMedia"in window))
        return so;
    var t = window.matchMedia(Kw.dark)
      , r = function() {
        e(t.matches ? "dark" : "light", !0)
    };
    return t.addEventListener("change", r),
    function() {
        t.removeEventListener("change", r)
    }
}
```

不是啥重要功能,放个粗暴的解决方案.后台 自定义头部加了个 <script> 标签.
```HTML
<script>
window.matchMediaBak = window.matchMedia;
window.matchMedia = function(e){
    let result = window.matchMediaBak(e);
    if(result.addEventListener == undefined){
        result.addEventListener = function(){};
        result.removeEventListener = function(){};
    }
    return result;
}
</script>
```

**Comment by mcnk328** [comment]
> > > IOS 设备都是空白也,试了多台设备.只有 IOS 正常显示页面.
> > > 手头没调试环境,简单抓下包看了下,IOS端加载完资源以后,没有任何 /api/* 路径的请求.
> > 
> > 
> > https://alist-doc.nn.ci/docs/common-question#%E5%85%B3%E4%BA%8E%E6%B5%8F%E8%A7%88%E5%99%A8%E6%94%AF%E6%8C%81%E5%BA%A6
> 
> 查了下.因为需求手头两个 iOS 设备一年多没更新系统. Safari 版本"太旧"
> 
> 原因在:https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener#browser_compatibility
> 
> ```js
> function _A(e) {
>     if (!("matchMedia"in window))
>         return so;
>     var t = window.matchMedia(Kw.dark)
>       , r = function() {
>         e(t.matches ? "dark" : "light", !0)
>     };
>     return t.addEventListener("change", r),
>     function() {
>         t.removeEventListener("change", r)
>     }
> }
> ```
> 
> 不是啥重要功能,放个粗暴的解决方案.后台 自定义头部加了个 <script> 标签.
> 
> ```
> <script>
> window.matchMediaBak = window.matchMedia;
> window.matchMedia = function(e){
>     let result = window.matchMediaBak(e);
>     if(result.addEventListener == undefined){
>         result.addEventListener = function(){};
>         result.removeEventListener = function(){};
>     }
>     return result;
> }
> </script>
> ```

感谢老哥，困扰好一阵的白屏解决了

**Comment by xiaocsl** [comment]
> > > > IOS 设备都是空白也,试了多台设备.只有 IOS 正常显示页面.
> > > > 手头没调试环境,简单抓下包看了下,IOS端加载完资源以后,没有任何 /api/* 路径的请求.
> > > 
> > > 
> > > https://alist-doc.nn.ci/docs/common-question#%E5%85%B3%E4%BA%8E%E6%B5%8F%E8%A7%88%E5%99%A8%E6%94%AF%E6%8C%81%E5%BA%A6
> > 
> > 
> > 查了下.因为需求手头两个 iOS 设备一年多没更新系统. Safari 版本"太旧"
> > 原因在:https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener#browser_compatibility
> > ```js
> > function _A(e) {
> >     if (!("matchMedia"in window))
> >         return so;
> >     var t = window.matchMedia(Kw.dark)
> >       , r = function() {
> >         e(t.matches ? "dark" : "light", !0)
> >     };
> >     return t.addEventListener("change", r),
> >     function() {
> >         t.removeEventListener("change", r)
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 不是啥重要功能,放个粗暴的解决方案.后台 自定义头部加了个 <script> 标签.
> > ```
> > <script>
> > window.matchMediaBak = window.matchMedia;
> > window.matchMedia = function(e){
> >     let result = window.matchMediaBak(e);
> >     if(result.addEventListener == undefined){
> >         result.addEventListener = function(){};
> >         result.removeEventListener = function(){};
> >     }
> >     return result;
> > }
> > </script>
> > ```
> 
> 请教大佬： 的确，ios12.X的iPhone设备，进网页白屏。用了你的<script> 代码，页面可以正常进了。但访问网盘里的视频，无法正常播放。请教还有解决方法吗？

一般 iOS 设备对网页端的视频格式要求很严格,所以基本不会考虑 iOS 页面视频播放的兼容性问题.
如果只是看视频的话,推荐 "ES文件浏览器" 之类的挂在 webdav 体验才叫一个极致.
也可以用类似于"夸克浏览器"这种额外实现视频播放接口的浏览器,基本能解决90%的兼容性问题.

**Comment by Joyist2021** [comment]
手机访问白屏，加入官方演示站代码
方法.后台 自定义头部添加代码
`
<style>
.chakra-ui-light{
  background-image: url(https://alist.xhofe.top/d/%E6%9C%AC%E5%9C%B0%E5%AD%98%E5%82%A8/bg2.svg?sign=42cb557b01021920);
  /*background-attachment: fixed;*/
}
</style>
<link rel="stylesheet" href="https://npm.elemecdn.com/font-awesome/css/font-awesome.min.css">
    <script>
      window.matchMediaBak = window.matchMedia;
      window.matchMedia = function (e) {
        let result = window.matchMediaBak(e);
        if (!result.addEventListener) {
          result.addEventListener = function (event, listener) {
            result.addListener(listener);
          };
          result.removeEventListener = function (event, listener) {
            result.removeListener(listener);
          };
        }
        return result;
      };
      this.globalThis || (this.globalThis = this);
    </script>
`
