### ISSUE TITLE
解析json[Gateway Timeout]出错:invalid character 'G' looking for beginning of value 

### ISSUE THREAD

**Issue by zhouguangyou1994** [Xhofe/alist#56]
[36mINFO[0m[2021-03-22 18:54:52] 检查更新...                                      
[36mINFO[0m[2021-03-22 18:54:53] 当前已是最新版本:v1.0.1                              
[36mINFO[0m[2021-03-22 18:54:53] 读取配置文件...                                    
[36mINFO[0m[2021-03-22 18:54:53] 初始化client...                                 
[36mINFO[0m[2021-03-22 18:54:53] 初始化阿里云盘...                                   
[36mINFO[0m[2021-03-22 18:54:53] 刷新所有token...                                 
[36mINFO[0m[2021-03-22 18:54:53] 刷新[drive0]token...                           
[36mINFO[0m[2021-03-22 18:54:53] 初始化盘[drive0]成功:&{RespError:{Code: Message:} DomainId:bj29 UserId:358de23c407645*** Avatar: CreatedAt:1605696234343 UpdatedAt:1615598425294 Email: NickName:印度 Phone:184*80 Role:user Status:enabled UserName:184***580 Description: DefaultDriveId:418097 UserData:map[share:5fb4faeb23edc8a3f4b84c4094f9c63284c89577]} 
[36mINFO[0m[2021-03-22 18:54:53] 初始化数据库...                                    
[36mINFO[0m[2021-03-22 18:54:53] 迁移数据库...                                     
[36mINFO[0m[2021-03-22 18:54:53] 初始化定时任务:刷新token                              
[36mINFO[0m[2021-03-22 18:54:53] 初始化路由...                                     
[36mINFO[0m[2021-03-22 18:54:53] Starting server @ 0.0.0.0:5244  

重建目录rebuild输入密码后显示：
[36mINFO[0m[2021-03-22 18:58:54] 开始构建目录树...                                   
[31mERRO[0m[2021-03-22 18:59:22] 解析json[Gateway Timeout]出错:invalid character 'G' looking for beginning of value

**Comment by zhouguangyou1994** [comment]
解决了，文件数太多rebuild不出来，大概有几万-十几万的文件数量吧，设置成max_files_count: 999999也不行

**Comment by Xhofe** [comment]
之后会加入每次只请求指定深度的文件进行存储 可能会有所改善。
