### ISSUE TITLE
如何可以支持搜索加密文件夹？

### ISSUE THREAD

**Issue by hais1992** [Xhofe/alist#57]
可以支持类似这样的API 么？  

/root?q=关键字&pw=密码

或者搜索可以出现，点击下载才需要密码~

**Comment by Xhofe** [comment]
> 可以支持类似这样的API 么？
> 
> /root?q=关键字&pw=密码
> 
> 或者搜索可以出现，点击下载才需要密码~

前面的有点奇怪 可以支持后种，下一版本加一个开关吧。。
你如果着急需要这个功能的话，可以fork本仓库然后开启github actions中的工作流，修改这行，删掉其中的` AND password = ''`
https://github.com/Xhofe/alist/blob/76081a81a6864b3a9885b6f53cda5b98b1b2c908/server/models/file.go#L60
提交之后会自动在github actions中构建，或者你也可以clone到本地修改构建。

**Comment by hais1992** [comment]
> > 可以支持类似这样的API 么？
> > /root?q=关键字&pw=密码
> > 或者搜索可以出现，点击下载才需要密码~
> 
> 前面的有点奇怪 可以支持后种，下一版本加一个开关吧。。
> 你如果着急需要这个功能的话，可以fork本仓库然后开启github actions中的工作流，修改这行，删掉其中的` AND password = ''`
> https://github.com/Xhofe/alist/blob/76081a81a6864b3a9885b6f53cda5b98b1b2c908/server/models/file.go#L60
> 
> 
> 提交之后会自动在github actions中构建，或者你也可以clone到本地修改构建。

已解决~效果挺好，谢谢大佬~
