### ISSUE TITLE
jsd现在已经没有国内节点了 可以吧静态文件本地化么

### ISSUE THREAD

**Issue by FeiYuab** [Xhofe/alist#572]
### Description of the feature / 需求描述

jsd现在已经没有国内节点了 可以吧静态文件本地化么

**Comment by Xhofe** [comment]
？？这是什么 https://alist-doc.nn.ci/docs/setting/config#assets

**Comment by FeiYuab** [comment]
> ？？这是什么 https://alist-doc.nn.ci/docs/setting/config#assets

哦 抱歉 是我没有看配置文件 只看了后台配置
