### ISSUE TITLE
移动端网页显示不全

### ISSUE THREAD

**Issue by yikZero** [Xhofe/alist#58]
![image](https://user-images.githubusercontent.com/52102693/112300025-637c2300-8cd3-11eb-9de4-cb14a9a9b36a.png)
![image](https://user-images.githubusercontent.com/52102693/112300209-8d354a00-8cd3-11eb-819c-8a32bb1ce61d.png)
我发现移动端在文件名过长的时候，文件名称以及时间都不能够完全显示。

左右拖动也无法全部显示。

浏览器：夸克
手机型号：小米6

**Comment by Xhofe** [comment]
目前没有安卓的浏览器进行测试。。所以没啥办法。

**Comment by yikZero** [comment]
hello，我发现电脑端 文件名字过长也会有问题~
![image](https://user-images.githubusercontent.com/52102693/112710950-c520d500-8eff-11eb-9861-f7373534303a.png)
