### ISSUE TITLE
来个又拍云存储怎么样

### ISSUE THREAD

**Issue by balh55y** [Xhofe/alist#586]
### Description of the feature / 需求描述

像兰空这里填这几个
![image](https://user-images.githubusercontent.com/85926883/154929644-fce832d2-eda2-4a86-835e-69b52155592e.png)

### Suggested solution / 实现思路

这好像是api文档
https://help.upyun.com/knowledge-base/form_api/

**Comment by Xhofe** [comment]
请测试：https://github.com/Xhofe/alist/actions/runs/1887177844
