### ISSUE TITLE
新版本kkfileview无法自己设置url了?

### ISSUE THREAD

**Issue by huoshenlaile** [Xhofe/alist#59]
新版本的kkfileview那里设置为啥没有url设置了? 请问一下现在用的预览是由什么提供的?

**Comment by Xhofe** [comment]
> 新版本的kkfileview那里设置为啥没有url设置了? 请问一下现在用的预览是由什么提供的?

前端没写kkfileview的部分了，因为感觉没啥必要。之前主要是用来预览文档的，现在是直接使用阿里的接口。

**Comment by CrazyJasonwell** [comment]
现在$url参数都带了参数如：?sign=xxxxxxxx&alist_ts=xxxxxx，使得无法作为参数来传入kkfileview,是否可以使用正则去尾再传递到kkfileview?
