### ISSUE TITLE
无法打开office文件

### ISSUE THREAD

**Issue by zjmazy** [Xhofe/alist#590]
### Alist Version / Alist 版本

v2.0.10-0-gcc62cc9

### Describe the bug / 问题描述

通过alist无法打开office文件，如word等，提示

### Reproduction / 复现链接

![屏幕截图 2022-02-22 113759](https://user-images.githubusercontent.com/43462399/155059099-458d46ac-055a-4576-a189-53913cdc31c8.png)

**Comment by Xhofe** [comment]
...加了密码

**Comment by zjmazy** [comment]
> ...加了密码

https://zjmazy.synology.me:5055/d/docker/%E7%AC%AC%E4%B8%80%E8%BD%AE%E2%80%9C%E5%8F%8C%E4%B8%80%E6%B5%81%E2%80%9D%E5%BB%BA%E8%AE%BE%E5%AD%A6%E7%A7%91%E5%90%8D%E5%8D%95.docx

不好意思哈哈哈哈

**Comment by zjmazy** [comment]
> ...加了密码

https://zjmazy.synology.me:5055/docker/%E7%AC%AC%E4%B8%80%E8%BD%AE%E2%80%9C%E5%8F%8C%E4%B8%80%E6%B5%81%E2%80%9D%E5%BB%BA%E8%AE%BE%E5%AD%A6%E7%A7%91%E5%90%8D%E5%8D%95.docx

不好意思哈哈哈

**Comment by zjmazy** [comment]
> ...加了密码

您好，非常感谢开发了如此方便的应用
现在已知的问题是office和md都无法打开，如：
https://zjmazy.synology.me:5055/docker/intr.md
但是视频文件和图片都可以正常打开
服务基于群晖docker
大大如果有空还烦请解答一下！万分感谢

**Comment by Xhofe** [comment]
office可能是因为office online viewer不支持非标准端口，可以尝试更换为标准端口。

md是因为你这个文件是空的。。

**Comment by zjmazy** [comment]
> 非标准端口

因为是基于家庭公网ip无法使用80端口
所以可能就无解了
非常感谢您的解答！

**Comment by Xhofe** [comment]
下个版本会增加其他的预览 如果你有好的Office在线预览方案也可以提供一下的。

**Comment by zjmazy** [comment]
> 下个版本会增加其他的预览 如果你有好的Office在线预览方案也可以提供一下的。

原来我在自己的设备上用的是nextcloud+onlyoffice，但是在移动端上编辑要付费，所以转投大佬这了

**Comment by tingyue-wu** [comment]
> > 非标准端口
> 
> 因为是基于家庭公网ip无法使用80端口 所以可能就无解了 非常感谢您的解答！

即使是非标准接口，其实也有办法的，把office文档预览功能处理成先转换再预览，https://github.com/Mintimate/OneindexM
这个作者，他的网盘工具挂载onedrive之后，虽然容器部署在局域网，但是打开office文件时链接显示[https://view.officeapps.live.com/op/view.aspx?src=https.....（等号后面是onedrive里的文件直链），并没有出现本地容器的端口，所以可以预览，看图1、图2]
![3f8a855d13c7ab5be95f4f018abc352f_212316634-1ca0cb42-8679-45bd-b893-5b8909c895da](https://user-images.githubusercontent.com/62607946/219230210-74155d8f-3908-47c3-9537-e923a5754640.png)

![5f3c714e7e84b188d3f5e439ea393ee3_212316504-96f537c5-d99e-4846-9da4-bb2523b8d1c7](https://user-images.githubusercontent.com/62607946/219230264-58f0233b-6a59-4567-9514-a58b8a0c65e5.png)
