### ISSUE TITLE
直链下载显示Access Denied

### ISSUE THREAD

**Issue by AnotiaWang** [Xhofe/alist#6]
![Screenshot_20201231-124521792.jpg](https://user-images.githubusercontent.com/62269186/103394884-2128c700-4b66-11eb-92ea-1289cfc7b54e.jpg)

**Comment by Xhofe** [comment]
这是由于加了缓存的原因，我之前不知道他的下载地址是有期限的，你可以在配置文件中设小缓存时间，或者手动换新缓存：访问`后端地址/cache/刷新缓存密码`，将在下个版本中去除对文件请求的缓存。

**Comment by sottboy** [comment]
如何搭建，教程在哪，演示的网址也打不开？

**Comment by Xhofe** [comment]
> 如何搭建，教程在哪，演示的网址也打不开？

？[https://www.nn.ci/archives/alist.html](https://www.nn.ci/archives/alist.html)打得开啊，关闭代理试试。

**Comment by sottboy** [comment]
打得开了，我了一个节点就打得开了，感谢你的技术，现在准备按你方法搭一个试试。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "微凉"<notifications@github.com&gt;; 
发送时间: 2021年1月6日(星期三) 晚上9:15
收件人: "Xhofe/alist"<alist@noreply.github.com&gt;; 
抄送: "sottboy"<sottboy@163.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Xhofe/alist] 直链下载显示Access Denied (#6)





  
如何搭建，教程在哪，演示的网址也打不开？
  
？https://www.nn.ci/archives/alist.html打得开啊，关闭代理试试。

**Comment by Xhofe** [comment]
> 打得开了，我了一个节点就打得开了，感谢你的技术，现在准备按你方法搭一个试试。

感谢支持😀

**Comment by sottboy** [comment]
你好大佬，我搭建好了，我想改列表，默认为根目录我想改为文件夹，在哪获取文件夹ID？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "微凉"<notifications@github.com&gt;; 
发送时间: 2021年1月6日(星期三) 晚上9:59
收件人: "Xhofe/alist"<alist@noreply.github.com&gt;; 
抄送: "sottboy"<sottboy@163.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Xhofe/alist] 直链下载显示Access Denied (#6)





  
打得开了，我了一个节点就打得开了，感谢你的技术，现在准备按你方法搭一个试试。
  
感谢支持😀
 
&mdash;

**Comment by Xhofe** [comment]
> 你好大佬，我搭建好了，我想改列表，默认为根目录我想改为文件夹，在哪获取文件夹ID？

打开搭建好的网站，点进你要设置的文件夹，url最后面就是文件夹的ID，比如`https://alist.nn.ci/5fe01e1830601baf774e4827a9fb8fb2b5bf7940`，文件夹id就是`5fe01e1830601baf774e4827a9fb8fb2b5bf7940`

**Comment by sottboy** [comment]
谢谢收到，有电报群吗，我加一下，邮件效率有点慢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "微凉"<notifications@github.com&gt;; 
发送时间: 2021年1月6日(星期三) 晚上10:54
收件人: "Xhofe/alist"<alist@noreply.github.com&gt;; 
抄送: "sottboy"<sottboy@163.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Xhofe/alist] 直链下载显示Access Denied (#6)





  
你好大佬，我搭建好了，我想改列表，默认为根目录我想改为文件夹，在哪获取文件夹ID？
  
打开搭建好的网站，点进你要设置的文件夹，url最后面就是文件夹的ID，比如https://alist.nn.ci/5fe01e1830601baf774e4827a9fb8fb2b5bf7940，文件夹id就是5fe01e1830601baf774e4827a9fb8fb2b5bf7940
 
&mdash;

**Comment by sottboy** [comment]
alist项目如何显示自述文件的内容。还有可以解决一打开就显示要翻译吗，是要改编码吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "微凉"<notifications@github.com&gt;; 
发送时间: 2021年1月6日(星期三) 晚上10:54
收件人: "Xhofe/alist"<alist@noreply.github.com&gt;; 
抄送: "sottboy"<sottboy@163.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Xhofe/alist] 直链下载显示Access Denied (#6)





  
你好大佬，我搭建好了，我想改列表，默认为根目录我想改为文件夹，在哪获取文件夹ID？
  
打开搭建好的网站，点进你要设置的文件夹，url最后面就是文件夹的ID，比如https://alist.nn.ci/5fe01e1830601baf774e4827a9fb8fb2b5bf7940，文件夹id就是5fe01e1830601baf774e4827a9fb8fb2b5bf7940
 
&mdash;

**Comment by Xhofe** [comment]
> alist项目如何显示自述文件的内容。还有可以解决一打开就显示要翻译吗，是要改编码吗

需要自述文件的在该文件夹下添加一个`Readme.md`即可，因为是写死的，所以大小写都要正确。
关于翻译这个，我忘记改语言了，你可以手动打开解压后的前端文件，有个`index.html`，将最开始的`lang="en"`修改为`lang="zh-cmn-Hans"`即可，之后会解决这个问题。
