### ISSUE TITLE
自动rebuild目录的时间?

### ISSUE THREAD

**Issue by huoshenlaile** [Xhofe/alist#60]
请问新版的Alist现在自动rebuild目录树的时间间隔是多少, 以及这个可以设置吗?
还有一点bug(也有可能是个人情况)就是第一次部署完Alist, 进入页面后path not find, 需要手动点一下rebuild才可以正常显示.

**Comment by Xhofe** [comment]
现在没有自动rebuild了，怕请求的太频繁。。。全部手动请求
所以第一次部署也需要手动rebuild一次。

**Comment by huoshenlaile** [comment]
> 现在没有自动rebuild了，怕请求的太频繁。。。全部手动请求
> 所以第一次部署也需要手动rebuild一次。

我觉得还是最好能加上自动rebuild, 但是时间间隔长一点, 比如默认每天rebuild一次, 这样省的每次更新文件都要手动rebuild

**Comment by zsbai** [comment]
https://后端链接/api/rebuild/盘名称/rebuild密码
通过宝塔定时任务等，每天访问一次此url即可实现自动rebuild

**Comment by zsbai** [comment]
https://后端链接/api/rebuild/盘名称/rebuild密码
使用宝塔或者其他的定时任务，每天访问该url一次即可实现定时自动rebuild

**Comment by huoshenlaile** [comment]
> [https://后端链接/api/rebuild/盘名称/rebuild密码](https://%E5%90%8E%E7%AB%AF%E9%93%BE%E6%8E%A5/api/rebuild/%E7%9B%98%E5%90%8D%E7%A7%B0/rebuild%E5%AF%86%E7%A0%81)
> 通过宝塔定时任务等，每天访问一次此url即可实现自动rebuild

有道理, 确实是个不错的折中方案

**Comment by sihuan** [comment]
> [https://后端链接/api/rebuild/盘名称/rebuild密码](https://%E5%90%8E%E7%AB%AF%E9%93%BE%E6%8E%A5/api/rebuild/%E7%9B%98%E5%90%8D%E7%A7%B0/rebuild%E5%AF%86%E7%A0%81)
> 通过宝塔定时任务等，每天访问一次此url即可实现自动rebuild

可以用以下脚本，通过 `systemd.timer` 或者 `crontab` 执行定时任务。

```shell
#!/bin/bash
curl --request POST \
  --url http://127.0.0.1:5244/api/rebuild \
  --header 'Content-Type: application/json' \
  --data '{
	"path":"drive0",
	"depth":-1,
	"password":"password"
}'
```

**Comment by huoshenlaile** [comment]
> > [https://后端链接/api/rebuild/盘名称/rebuild密码](https://%E5%90%8E%E7%AB%AF%E9%93%BE%E6%8E%A5/api/rebuild/%E7%9B%98%E5%90%8D%E7%A7%B0/rebuild%E5%AF%86%E7%A0%81)
> > 通过宝塔定时任务等，每天访问一次此url即可实现自动rebuild
> 
> 可以用以下脚本，通过 `systemd.timer` 或者 `crontab` 执行定时任务。 ~没用过宝塔(╥_╥)~
> 
> ```shell
> #!/bin/bash
> curl --request POST \
>   --url http://127.0.0.1:5244/api/rebuild \
>   --header 'Content-Type: application/json' \
>   --data '{
> 	"path":"your_drive_name",
> 	"depth":-1,
> 	"password":"your_password"
> }'
> ```

补充一个我自用的python版本, 同样可以添加至 `contab`
替换 `路径` `密码` `深度` 就能使用
``` python
import requests
r = requests.post('http://127.0.0.1:5244/api/rebuild',json={"path":"路径","password":"密码","depth":深度})
```

**Comment by xiaokaixuan** [comment]
> 现在没有自动rebuild了，怕请求的太频繁。。。全部手动请求
> 所以第一次部署也需要手动rebuild一次。

比较赞成不加自动rebuild，大多是无用的操作。

**Comment by hhls** [comment]
不建议自动 reload，开了这个口子很可能造成乱用，引起不必要麻烦
