### ISSUE TITLE
Teambition 网盘创建时虽然填了 cookie 但是一直提示 缺少 access_token

### ISSUE THREAD

**Issue by YinAoXiong** [Xhofe/alist#601]
### Alist Version / Alist 版本

v2.0.10

### Describe the bug / 问题描述

Teambition 网盘创建时虽然填了 cookie 但是一直提示 缺少 access_token，导致网盘账号无法创建成功

部署方式docker最新版本部署

### 日志 / Logs

```shell
alist  | [GIN] 2022/02/23 - 06:08:05 | 200 |  180.424872ms | 125.119.242.135 | POST     "/api/admin/account/save"
alist  | ERRO[2022-02-23 06:08:05] 缺少 access_token
```

**Comment by Xhofe** [comment]
请确认获取的cookie无误。

**Comment by YinAoXiong** [comment]
> 请确认获取的cookie无误。


![图片](https://user-images.githubusercontent.com/23397945/155272714-f9585aa7-4056-4be9-b037-ed55b079bc48.png)

我尝试的是国际版然后是从这个位置获取的cookie，把整个打码的部分复制粘贴填上去了。

填写完之后，发送的请求是这样的
![图片](https://user-images.githubusercontent.com/23397945/155272886-a5ae9430-4626-4266-a08b-f0ab43edcf16.png)

请求的响应是这样的

![图片](https://user-images.githubusercontent.com/23397945/155272949-1e5e0ab4-5cc6-4916-8d67-93269426c26a.png)

**Comment by Xhofe** [comment]
正确的cookie形式如下：
```cookie
_cioanonid=*****;
region=*****;
cna=*****;
sensorsdata2015jssdkcross=*****;
referral=*****;
TB_GTA=*****;
teambition_lang=*****;
xlly_s=*****;
isg=*****;
TEAMBITION_SESSIONID=*****;
TEAMBITION_SESSIONID.sig=*****;
mp_eSpCz4lYpMYgtuhdH0F6Wgtt_mixpanel=*****;
mp_tbpanel__c=0
```

**Comment by YinAoXiong** [comment]
我把浏览器换成edge复制cookie就成功了，用Firefox复制的cookie好像少了点东西 😂
