### ISSUE TITLE
无法播放百度云视频，无法预览pdf文件

### ISSUE THREAD

**Issue by caiwenmin** [Xhofe/alist#604]
### Alist Version / Alist 版本

稳定版

### Describe the bug / 问题描述

报错信息：
PDF.js v2.12.305 (build: d3e1d7090)
信息：network error

**Comment by Xhofe** [comment]
> 由于百度网盘API的限制，下载较大的文件（目测>20M）需要携带header："User-Agent":"pan.baidu.com"，所以在下载大于20M的文件时，需要自行设置请求头，如使用curl：
> ```shell
> curl -L -X GET 'YOUR_LINK' -H 'User-Agent: pan.baidu.com' 
> ```
> 或使用本程序中的代理功能进行中转。

看了吗

**Comment by caiwenmin** [comment]
大佬，你好，我试了一下小的视频是可以在线播放的，是在线播放较大的视频的时候无法加载出来（可能是缓冲的太慢了），但是百度云无法预览pdf文件的问题还是存在，我试了一下阿里云是正常可以预览pdf的

**Comment by caiwenmin** [comment]
使用WebDav连接时，把文件从本地复制到alist/阿里云，，一直提示：不能完成此操作，因为项目“a.txt”正在使用中 ，，但是这些文件并没有被占用

**Comment by Xhofe** [comment]
> 大佬，你好，我试了一下小的视频是可以在线播放的，是在线播放较大的视频的时候无法加载出来（可能是缓冲的太慢了），但是百度云无法预览pdf文件的问题还是存在，我试了一下阿里云是正常可以预览pdf的

预览pdf需要cors支持，百度不支持。

**Comment by caiwenmin** [comment]
哦哦，感谢解释，，百度网盘大于20M的文件，我发现我打开web proxy，不用配置down_proxy_url也可以下载大于20M的文件，不打开web proxy是报错的

**Comment by Xhofe** [comment]
> 哦哦，感谢解释，，百度网盘大于20M的文件，我发现我打开web proxy，不用配置down_proxy_url也可以下载大于20M的文件，不打开web proxy是报错的

文档里不就是这么写的吗。。。。web proxy就是中转。

**Comment by caiwenmin** [comment]
使用WebDav连接时，把文件从本地复制到alist，一直提示：“不能完成此操作，因为项目“a.txt”正在使用中”
但是这些文件并没有被占用，，是不支持吗？

**Comment by Xhofe** [comment]
> 使用WebDav连接时，把文件从本地复制到alist，一直提示：“不能完成此操作，因为项目“a.txt”正在使用中” 但是这些文件并没有被占用，，是不支持吗？

尝试更换其他客户端，部分webdav客户端不适配。

**Comment by dtknight** [comment]
用非官方接口下载百度网盘为啥都是150字节的假文件呀
