### ISSUE TITLE
大佬关于本地文件有个问题想请教

### ISSUE THREAD

**Issue by LiJunXiao** [Xhofe/alist#608]
### Alist Version / Alist 版本

v2.0.10

### Describe the bug / 问题描述

就是现在需求是把一台服务器的文件共享出来，能够让同WiFi下其他设备访问到服务器设备的文件。只需要用到您这个项目的本地存储功能。而且这个服务器本身是纯内网的环境，不通互联网。您这个项目如何去掉阿里云盘等选项，以及如何更换一些cdn的地址啊。很懵逼，呜呜呜呜。大佬救救我。

**Comment by Xhofe** [comment]
> Please go to our [discussion forum](https://github.com/Xhofe/alist/discussions) for general questions, issues are for bug reports and feature request only.

Q&A 请至[Discussions](https://github.com/Xhofe/alist/discussions)
