### ISSUE TITLE
go程序无法在alpine最新容器上运行，提示找不到文件no such file

### ISSUE THREAD

**Issue by hbestm** [Xhofe/alist#61]
查询网络资料，运行在alpine最新版的go程序，涉及到动态编译与静态编译的问题。

在alpine3.6上应该使用网络编译go，即增加 -tags netgo。

希望作者在编译时的时候考虑一下，方便alpine做基础镜像的docker部署

**Comment by Xhofe** [comment]
没有使用过alpine镜像容器
？没有太看懂你的意思

**Comment by hbestm** [comment]
是这样一个过程，我打算在aarch64设备（N1,Armbian),里面通过docker部署alist，基础镜像采用Alpine，但是在这个过程中，因为Alpine本身问题，倒置alist（go编译的二进制文件）不能运行，网络查询资料考虑Alpine本身问题，网络解决办法是go编译文件时添加 -tags netgo，具体是怎么样操作，我也不清楚，我会go。大概问题就是这样，感谢作者回复

**Comment by naicfeng** [comment]
https://github.com/Xhofe/alist/issues/54

alpine要添加glibc才能运行，目前就是在用alpine构建的docker

你不能运行的提示是什么？log发出来看看

`docker logs alist`

**Comment by hbestm** [comment]
我换debian为基础镜像搞定了。哎
