### ISSUE TITLE
无法删除账号数据或者元信息。

### ISSUE THREAD

**Issue by OuOumm** [Xhofe/alist#616]
### Alist Version / Alist 版本

v2.0.10-0-gcc62cc9-dirty

### Describe the bug / 问题描述

点击删除后无法删除，只可以添加数据。报错如下。

index.24615643.js:2          DELETE https://xxx.com/api/admin/account?id=2 403
（匿名） @ index.24615643.js:2
Me @ index.24615643.js:2
Mr @ index.24615643.js:2
Promise.then（异步）
R.request @ index.24615643.js:2
R.<computed> @ index.24615643.js:2
（匿名） @ index.24615643.js:1
onClick @ accounts.52676d00.js:1
X$ @ vendor.442eedbd.js:30
Y$ @ vendor.442eedbd.js:30
q$ @ vendor.442eedbd.js:30
cx @ vendor.442eedbd.js:30
fx @ vendor.442eedbd.js:30
（匿名） @ vendor.442eedbd.js:30
_b @ vendor.442eedbd.js:34
K$ @ vendor.442eedbd.js:30
mx @ vendor.442eedbd.js:30
Qp @ vendor.442eedbd.js:30
Zp @ vendor.442eedbd.js:30
e.unstable_runWithPriority @ vendor.442eedbd.js:19
Ja @ vendor.442eedbd.js:30
wb @ vendor.442eedbd.js:34
cj @ vendor.442eedbd.js:30
index.24615643.js:2 Error: Request failed with status code 403
    at Ee (index.24615643.js:1:4676)
    at Zt (index.24615643.js:1:4800)
    at XMLHttpRequest.U (index.24615643.js:2:1813)
index.24615643.js:1 Uncaught (in promise) Error: Request failed with status code 403
    at Ee (index.24615643.js:1:4676)
    at Zt (index.24615643.js:1:4800)
    at XMLHttpRequest.U (index.24615643.js:2:1813)

**Comment by Xhofe** [comment]
一般问题请不要提issue而是至[discussions](https://github.com/Xhofe/alist/discussions)

请查看你的网站反向代理是否支持delete请求。可能的原因是你的某个保护程序（如防火墙）阻止了delete请求。

**Comment by OuOumm** [comment]
感谢，已获知。请原谅我的无知。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Xhofe/alist"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月25日(星期五) 晚上8:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Xhofe/alist] 无法删除账号数据或者元信息。 (Issue #616)





 
一般问题请不要提issue而是至discussions
 
请查看你的网站反向代理是否支持delete请求。可能的原因是你的某个保护程序（如防火墙）阻止了delete请求。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by OuOumm** [comment]
> 一般问题请不要提问题改为[讨论](https://github.com/Xhofe/alist/discussions)
> 
> 请查看你的网站代理可能是否支持删除请求。

感谢，已获知。这就删除。
