### ISSUE TITLE
建议和问题

### ISSUE THREAD

**Issue by yimouleng** [Xhofe/alist#62]
1. 有些电影，在线观看没有声音，有的还会加载失败，猜测DPlayer识别格式出现问题。
2. 最好可设置每页显示条数，分页显示，内容过多，很难看到README.md所展示的内容（拉很久）
3. 文件名称过长，最好有个最大距离，现在会一直往后延展，导致后面的时间字段和大小字段看不见了

使用两天的感受，以上。

**Comment by Xhofe** [comment]
部分之后会修改。
