### ISSUE TITLE
Google Drive不能移动文件了

### ISSUE THREAD

**Issue by ZhouNLP** [Xhofe/alist#620]
### Alist Version / Alist 版本

v2.1.0

### Describe the bug / 问题描述

提示
A shared drive item must have exactly one parent.: [{global teamDrivesParentLimit A shared drive item must have exactly one parent. }]
我记得上个版本还可以，最新版不行了

**Comment by TwooSix** [comment]
> https://github.com/Xhofe/alist/commits/v2/drivers/google

你好，目前我在使用的版本v3.41.0还是存在这个问题，在对团队盘移动文件时报错，但其他删除，上传，下载等操作都没有问题
