### ISSUE TITLE
希望优化登录过程、无法预览文档

### ISSUE THREAD

**Issue by 521tonysteven** [Xhofe/alist#623]
### Description of the feature / 需求描述

希望能登录后不默认进入后台页面，因为我发现登录后无法直接返回文件列表，只能刷新网页。
无法预览office文档，office控件提示“An error occurred”.
无法预览pdf文档，打开pdf文档直接是白屏。
最后，这个index真的太好看了，很喜欢。

### Additional context / 附件

![image](https://user-images.githubusercontent.com/44032601/155872160-199c2a8b-e037-4cde-8eb2-649234906e21.png)
![image](https://user-images.githubusercontent.com/44032601/155872195-3ca293cb-3dd1-43ed-bd4e-752c047a2df7.png)

**Comment by Xhofe** [comment]
- 在后台右下角有三个按钮，有一个可以回到列表
- office：#594
- pdf：#619

**Comment by 521tonysteven** [comment]
看到了，不知道什么原因没有加载出来那三个按钮。重启服务端解决了。
