### ISSUE TITLE
视频预览格式希望能新增更多格式

### ISSUE THREAD

**Issue by api81244390** [Xhofe/alist#63]
比如ts,mkv，同时还发现个问题，同样都是MP4格式的视频，电脑可以正常预览，手机却不可以，不知何故。
再一个就是重新目录如果文件多速度太慢，有时还会出现前台卡死的情况，就是看数据库里已经重建完成，前台还在显示重建中。

**Comment by Xhofe** [comment]
部分视频格式web端不支持解码，无法预览。
重建的问题之后会解决。

**Comment by Xhofe** [comment]
已经加入转码接口

**Comment by Cathgao** [comment]
> 已经加入转码接口

请问如何能预览TS？TS按理说也就MPEG4或者AVC，应该能播才对
