### ISSUE TITLE
数据文件的路径问题

### ISSUE THREAD

**Issue by sukanka** [Xhofe/alist#631]
### Description of the feature / 需求描述

在指定了 `-conf /var/lib/alist/config.json` 时，仍然会产生 `/usr/bin/data/` 文件夹，并且所有的数据仍然存放在 `/usr/bin/data`

希望的结果是，指定了 `-conf /var/lib/alist/config.json` 以后，数据文件与临时文件也存放在 ` /var/lib/alist/` 下面，而不是与 `alist-xxx` 同级的 `data/`下面。

**Comment by Xhofe** [comment]
-conf只是指定配置目录，临时文件夹和数据库是在配置文件中指定的，如果你需要更改，修改配置文件就可以。

**Comment by sukanka** [comment]
感谢，在配置文件找到了。
