### ISSUE TITLE
可否用java script创建这个项目

### ISSUE THREAD

**Issue by xepo12** [Xhofe/alist#64]
没有钱买服务器。
想用Cloudflare的woker
搭建脚本。
就不用买服务器了

**Comment by Xhofe** [comment]
理论上是可以的，之前还尝试过写了个demo。但是我对wokers的api不是很熟悉，最近也没啥时间学。。

**Comment by naicfeng** [comment]
https://github.com/ukuq/onepoint/issues/21

我简单适配了一下在cfworker下的阿里云盘，用的是onepoint

目前最大的问题就是cf访问阿里云盘的API会超时，不建议在cfworker上部署

**Comment by ukuq** [comment]
https://github.com/ukuq/onepoint/

demo:  https://onepoint.onesrc.workers.dev/alidrive/

新增了阿里云，供参考
