### ISSUE TITLE
度盘refresh token获取

### ISSUE THREAD

**Issue by splinter21** [Xhofe/alist#644]
### Alist Version / Alist 版本

v2.0.0

### Describe the bug / 问题描述

https://alist-doc.nn.ci/docs/driver/baidu/
"点此"获取刷新令牌
这个点此  的链接    原来developer.baidu不能用了（会跳转到百度的登录界面），改成openapi.baidu就可以了

**Comment by Xhofe** [comment]
好奇怪啊，从别的地方点过去是openapi的，但是直接进就变成developer了。
源码里也是openapi：https://github.com/alist-org/alist-doc/blob/main/docs/driver/baidu.md
不知道这个developer哪里来的。

**Comment by Xhofe** [comment]
改成https已经好了。
