### ISSUE TITLE
Bug 反馈

### ISSUE THREAD

**Issue by zsbai** [Xhofe/alist#65]
有时候不知道什么原因网页会白屏，一直刷新一直白屏，除非把此标签页关掉重新打开。后端无报错，手机端出现概率很高，电脑却没出现过几次
手机为iPhone7 Safari浏览器

**Comment by zsbai** [comment]
发现如果链接后带盘符，刷新就会白屏...初步判断还是因为前后端分离的原因？

**Comment by Xhofe** [comment]
因为是spa，所以如果你前端不是用gin的话，需要设置服务端。
