### ISSUE TITLE
增加前端的搜索功能

### ISSUE THREAD

**Issue by f0re1gnKey** [Xhofe/alist#660]
### Description of the feature / 需求描述

可否在前端实现在all(不分页)的情况下的当前目录下的简易筛选/搜索功能

虽然ctrl+f也可以但总觉得不够专业

**Comment by Duan-rax** [comment]
大佬是准备做这个功能了吗？网盘目录程序搜索功能感觉挺有必要的

**Comment by zzzqu** [comment]
需求+1 只要每个网盘单独进行搜索的功能就可以，希望开发者支持一下，谢谢！

**Comment by shaojs321** [comment]
我记得github上有个网盘直链项目有这个功能，很赞，而且搜索速度也蛮快的，大佬可以参考一下

**Comment by Yangtzeus** [comment]
> 我记得github上有个网盘直链项目有这个功能，很赞，而且搜索速度也蛮快的，大佬可以参考一下

是PanIndex吗，那个项目的搜索功能确实赞，求添加!
