### ISSUE TITLE
为啥倒霉的总是我

### ISSUE THREAD

**Issue by dmserver** [Xhofe/alist#67]
https://imgtu.com/i/ciiUjP
下载不了

**Comment by naicfeng** [comment]
`x-oss-additional-headers: referer`

现在需要验证`referer``了？如果这样，就不能直传了……

**Comment by hais1992** [comment]
> `x-oss-additional-headers: referer`
> 
> 现在需要验证`referer``了？如果这样，就不能直传了……

有什么临时解决办法吗

**Comment by naicfeng** [comment]
> > `x-oss-additional-headers: referer`
> > 现在需要验证`referer``了？如果这样，就不能直传了……
> 
> 有什么临时解决办法吗

`/v2/file/get_download_url`返回的下载URL签名把`'Referer: https://www.aliyundrive.com/'`固定签进去了
试了几种方式，目前无解。不能浏览器直传，要伪造Referer才行

**Comment by zhucaidan** [comment]
同样问题。。有解决办法了吗

**Comment by dmserver** [comment]
> 同样问题。。有解决办法了吗

没办法 群里也在等

**Comment by hais1992** [comment]
> > 同样问题。。有解决办法了吗
> 
> 没办法 群里也在等

分享下群号？

**Comment by xtyzhen** [comment]
之前用自己写的代码用了挺久的。正所谓开源必死。
不能用了，过来看看你的，发现大家都一样。~@~！
目前可行的办法应该就是转客户端吧。
或者说最简单的就是结合curl开发。亦或者，用著名的 aria2 。

**Comment by JsonSong89** [comment]
其实可能是你们想多了.
因为阿里云自己的web端也挂了...哈哈

**Comment by xtyzhen** [comment]
> 其实可能是你们想多了.
> 因为阿里云自己的web端也挂了...哈哈

人家web端挺好的呀。。。。

**Comment by JsonSong89** [comment]
> 人家web端挺好的呀。。。。

啊,我刚刚还试了,已经不能预览了.

![image](https://user-images.githubusercontent.com/4394916/112974140-b39c2f00-9184-11eb-8c5b-a56c26544f64.png)

**Comment by xtyzhen** [comment]
> > 人家web端挺好的呀。。。。
> 
> 啊,我刚刚还试了,已经不能预览了.
> 
> ![image](https://user-images.githubusercontent.com/4394916/112974140-b39c2f00-9184-11eb-8c5b-a56c26544f64.png)

通过你的referer来看，官方可能没有考虑到用https://aliyundrive.com/访问的情况。
用https://www.aliyundrive.com/访问就可以了。 少了www.他们自己的网站都不认了。

**Comment by JsonSong89** [comment]
@xtyzhen 有点搞笑,估计是堵漏洞把@域名给忘记了
那看来确实是加了Referer限制了.

话说有没有什么浏览器插件或魔改浏览器可以hack Referer?

**Comment by JsonSong89** [comment]
不对,好像并非Referer有问题,比如

**Comment by JsonSong89** [comment]
同一个图片

alist的地址
https://bj29.cn-beijing.data.alicloudccp.com/604e1577487a796ea19642bbaac70b9d6322e9f5%2F604e157701a21e9bb0d04129947111f09756956b?di=bj29&dr=989001&f=604e1577487a796ea19642bbaac70b9d6322e9f5&response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27timg.jpg&u=385130262d8e4bfe80368e8e6f2d6456&x-oss-access-key-id=LTAIsE5mAn2F493Q&x-oss-additional-headers=referer&x-oss-expires=1617119901&x-oss-signature=eOFKervoSWwfzaC9%2FrFsj2inF8%2ByrFOQZWuxnYqk8BI%3D&x-oss-signature-version=OSS2

阿里云盘web的地址
 https://bj29.cn-beijing.data.alicloudccp.com/604e1577487a796ea19642bbaac70b9d6322e9f5%2F604e157701a21e9bb0d04129947111f09756956b?x-oss-access-key-id=LTAIsE5mAn2F493Q&x-oss-additional-headers=referer&x-oss-expires=1617106273&x-oss-process=image%2Fresize%2Cw_1920%2Fformat%2Cjpeg&x-oss-signature=X5ewqVSSK7UEu8iP4K82IqxyxyFzfrlV1QYt9GXXBvo%3D&x-oss-signature-version=OSS2

**Comment by JsonSong89** [comment]
![image](https://user-images.githubusercontent.com/4394916/112985764-31ffcd80-9193-11eb-860a-e5b85af55a53.png)

**Comment by naicfeng** [comment]
> 同一个图片
> 
> alist的地址
> https://bj29.cn-beijing.data.alicloudccp.com/604e1577487a796ea19642bbaac70b9d6322e9f5%2F604e157701a21e9bb0d04129947111f09756956b?di=bj29&dr=989001&f=604e1577487a796ea19642bbaac70b9d6322e9f5&response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27timg.jpg&u=385130262d8e4bfe80368e8e6f2d6456&x-oss-access-key-id=LTAIsE5mAn2F493Q&x-oss-additional-headers=referer&x-oss-expires=1617119901&x-oss-signature=eOFKervoSWwfzaC9%2FrFsj2inF8%2ByrFOQZWuxnYqk8BI%3D&x-oss-signature-version=OSS2
> 
> 阿里云盘web的地址
> https://bj29.cn-beijing.data.alicloudccp.com/604e1577487a796ea19642bbaac70b9d6322e9f5%2F604e157701a21e9bb0d04129947111f09756956b?x-oss-access-key-id=LTAIsE5mAn2F493Q&x-oss-additional-headers=referer&x-oss-expires=1617106273&x-oss-process=image%2Fresize%2Cw_1920%2Fformat%2Cjpeg&x-oss-signature=X5ewqVSSK7UEu8iP4K82IqxyxyFzfrlV1QYt9GXXBvo%3D&x-oss-signature-version=OSS2

api是一致的，一个是url一个是download_url

只要含有`x-oss-additional-headers=referer`就是签名已经签了`referer`进去,暂时无解

**Comment by zy84338719** [comment]
哎！好难过

**Comment by 122cygf** [comment]
已经解决并PR，等待合并

**Comment by 122cygf** [comment]
Actions里面的新版好使吗

**Comment by naicfeng** [comment]
江山代有才人出

**Comment by zhucaidan** [comment]
可以了，完美使用

**Comment by Xhofe** [comment]
> Actions里面的新版好使吗

大佬👍👍👍
