### ISSUE TITLE
直链地址后面的/d很不方便，希望能够自定义或增加个开关

### ISSUE THREAD

**Issue by shouji123** [Xhofe/alist#678]
### Description of the feature / 需求描述

我有大量已经写死的直链地址，例如 xxxxx.com/ofo/errop.zip，使用该直链系统所生成的链接却变成了xxxxx.com/d/ofo/errop.zip，要改这些写死的直链地址太麻烦，希望能有个解决办法。

**Comment by nitezs** [comment]
可以用正则表达式批量改

**Comment by shouji123** [comment]
是不是太麻烦了😂

**Comment by shouji123** [comment]
> 

因为这些链接有一部分是写死在程序里的，重新打包很麻烦

**Comment by zhujitop** [comment]
插眼，我也是这样...
之前用别的程序是直接的，现在加了个/d，得去处理一大堆。

**Comment by Xhofe** [comment]
可以使用另一个域名反代/d目录实现相同效果：
```nginx
location / {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_redirect off;
    proxy_pass http://127.0.0.1:5244/d/;
    # 上传的最大文件尺寸
    client_max_body_size 20000m;
}
```
在后端中动态判断会极大拖慢网站的响应速度，所以不会单独添加。

**Comment by zhujitop** [comment]
> 可以使用另一个域名反代/d目录实现相同的效果：
> 
> ```nginx
> location  / {
>      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for ;
>     proxy_set_header主机$http_host ;
>     proxy_set_header X-Real-IP $remote_addr ;
>     代理重定向关闭；
>     proxy_pass http://127.0.0.1:5244/d/；
>     # 上传的最大文件尺寸
>     client_max_body_size  20000m ;
> }
> ```
> 
> 在缓慢中动态判断会极大地响应网站的响应速度所以不会单独添加。

加了另外个域名，访问提示：

{"code":500,"message":"not file","data":null}

**Comment by Xhofe** [comment]
> > 可以使用另一个域名反代/d目录实现相同的效果：
> > ```nginx
> > location  / {
> >      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for ;
> >     proxy_set_header主机$http_host ;
> >     proxy_set_header X-Real-IP $remote_addr ;
> >     代理重定向关闭；
> >     proxy_pass http://127.0.0.1:5244/d/；
> >     # 上传的最大文件尺寸
> >     client_max_body_size  20000m ;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 在缓慢中动态判断会极大地响应网站的响应速度所以不会单独添加。
> 
> 加了另外个域名，访问提示：
> 
> {"code":500,"message":"not file","data":null}

用主域名访问，复制直链后用后添加的域名替换，可以去掉/d，如：
https://alist.xhofe.top/d/LocalStorage/bg.svg
对应
https://d_alist.xhofe.top/LocalStorage/bg.svg

**Comment by dmlt** [comment]
> 

工作进度已经加入Done中了，是不是没有走后台添加 这功能走方向代理是吧？？

**Comment by dmlt** [comment]
> > > 可以使用另一个域名反代/d目录实现相同的效果：
> > > ```nginx
> > > location  / {
> > >      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for ;
> > >     proxy_set_header主机$http_host ;
> > >     proxy_set_header X-Real-IP $remote_addr ;
> > >     代理重定向关闭；
> > >     proxy_pass http://127.0.0.1:5244/d/；
> > >     # 上传的最大文件尺寸
> > >     client_max_body_size  20000m ;
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 在缓慢中动态判断会极大地响应网站的响应速度所以不会单独添加。
> > 
> > 
> > 加了另外个域名，访问提示：
> > {"code":500,"message":"not file","data":null}
> 
> 用主域名访问，复制直链后用后添加的域名替换，可以去掉/d，如： https://alist.xhofe.top/d/LocalStorage/bg.svg 对应 https://d_alist.xhofe.top/LocalStorage/bg.svg

工作进度已经加入Done中了，是不是没有走后台添加 这功能走方向代理是吧？？

**Comment by Xhofe** [comment]
> 

额 加错位置了
