### ISSUE TITLE
天翼超过1g的文件报错

### ISSUE THREAD

**Issue by Yicons** [Xhofe/alist#680]
### Alist Version / Alist 版本

v2.1.1

### Describe the bug / 问题描述

测试了下，天翼大于1g的会报错超大，需要在down_proxy_url中添加什么吗？

同设备挂载的OneDrive无此异常。
![GMTum.png](https://s1.328888.xyz/2022/03/05/GMTum.png)

**Comment by Xhofe** [comment]
天翼云盘已不支持从网页端下载大文件，后续需要看客户端下载的实现。

**Comment by Yicons** [comment]
> 天翼云盘已不支持从网页端下载大文件，后续需要看客户端下载的实现。

好吧 了解了
