### ISSUE TITLE
天翼云盘 过大文件无法下载

### ISSUE THREAD

**Issue by naicfeng** [Xhofe/alist#683]
### Alist Version / Alist 版本

2.1.2

### Describe the bug / 问题描述

天翼云盘 过大文件无法下载，会提示
```
{"code":500,"message":"_89.Cloud189Down.ResCode: readUint64: unexpected character: \ufffd, error found in #10 byte of ...|es_code\":\"FileTooLar|..., bigger context ...|{\"res_message\":\"File too large\",\"res_code\":\"FileTooLarge\"}\n|...","data":null}
```

在某些在线解析网站可以正常解析下载，例如
```
189.ly93.cc
```

### Reproduction / 复现链接

不知道具体多大，转存ps后无法下载(2.97GB)

天翼云：http://t.cn/A6IgGNIS 访问码：3aud

**Comment by naicfeng** [comment]
补充一下复现链接 https://alist.xhofe.top/%E5%A4%A9%E7%BF%BC%E4%BA%91%E7%9B%98/upload/AutoCAD%202022.zip

**Comment by gzxiexl** [comment]
我也遇到了
下载一个2g的压缩包
{"code":500,"message":"_89.Cloud189Down.ResCode: readUint64: unexpected character: \ufffd, error found in #10 byte of ...|es_code\":\"FileTooLar|..., bigger context ...|{\"res_message\":\"File too large\",\"res_code\":\"FileTooLarge\"}\n|...","data":null}

**Comment by Lcry** [comment]
演示站天翼云盘同样有此问题，应该是文件过大导致，等待作者修复吧

**Comment by charlesouwen** [comment]
还没有解决吗0 0   @Xhofe

**Comment by wangx2** [comment]
同问，播放视频提示这个故障
