### ISSUE TITLE
浏览器跳转本地播放器时字幕会有找不到的情况

### ISSUE THREAD

**Issue by kangbeicai** [Xhofe/alist#684]
### Alist Version / Alist 版本

v2.1.0-0-gd988f98

### Describe the bug / 问题描述
PC端测试了 potplay，  外挂字幕好像找不到。
移动端测试过mxplayer和nplayer， nplayer也找不到外挂字幕。
mxplayer能找得到同名字幕，但是找不到多一段后缀的字幕。 
即 文件名.mkv + 文件名.ass可以，
文件名.mkv + 文件名.sc.ass 这种类型的找不到。

### Reproduction / 复现链接

无

### 日志 / Logs

```shell
无
```

**Comment by Xhofe** [comment]
……你可以说说解决方法吗

**Comment by kangbeicai** [comment]
> ……你可以说说解决方法吗

目前我试了一下在potplayer中使用打开远程连接访问webdav， 在这里打开文件是会读取到字幕的。
然后选打开链接会出现这个时候实际使用的webdav链接，这个链接和直接网页跳转的是不一样的。

不带字幕的：`http://192.168.50.165:5244/d/NAS/Concrete Revolutio Choujin Gensou S01E01.mkv`
带字幕但是需要用户名密码验证：`http://192.168.50.165:5244/dav/NAS/Concrete%20Revolutio%20Choujin%20Gensou%20S01E01.mkv?WithCaption`

其实这个功能也不是很关键，只是昨晚最开始用的mxplayer测试是有字幕的，以为文件链接和字幕链接都是从网页跳转给到浏览器的，非常抱歉打扰大佬了。
