### ISSUE TITLE
大佬，在阿里云盘新增了一个文件夹，alist无法及时的获取到新的资源

### ISSUE THREAD

**Issue by caiwenmin** [Xhofe/alist#688]
### Alist Version / Alist 版本

稳定版

### Describe the bug / 问题描述

新增了一个文件夹，放入了的文件无法及时刷新出来

**Comment by Xhofe** [comment]
https://alist-doc.nn.ci/docs/common-question#%E4%B8%8A%E4%BC%A0%E7%9A%84%E6%96%87%E4%BB%B6%E4%B8%8D%E6%98%BE%E7%A4%BA%E5%88%A0%E9%99%A4%E7%9A%84%E6%96%87%E4%BB%B6%E8%BF%98%E5%9C%A8%E4%BF%AE%E6%94%B9%E6%A0%B9%E7%9B%AE%E5%BD%95%E4%B8%8D%E7%94%9F%E6%95%88
