### ISSUE TITLE
蓝奏云不能自动翻页

### ISSUE THREAD

**Issue by fengguowudi** [Xhofe/alist#690]
### Alist Version / Alist 版本

v2.1.2

### Describe the bug / 问题描述

源链接：https://www.lanzoui.com/u/yoyodadada
实际效果： https://cloud.feng666.tk/%E4%BC%98%E8%B4%A8%E5%AE%89%E5%8D%93app

源网站的软件数量大与alist，而且alist不能自动检测下一页

### Reproduction / 复现链接

https://cloud.feng666.tk/%E4%BC%98%E8%B4%A8%E5%AE%89%E5%8D%93app

**Comment by Xhofe** [comment]
蓝奏云的api限制了请求的频率，大约为1s一次，已经添加了请求间隔，不建议一个文件夹下放太多文件，会很慢且容易出现请求返回出错。
