### ISSUE TITLE
希望增加Telegram存储支持

### ISSUE THREAD

**Issue by sirliu** [Xhofe/alist#696]
### Telegram可以实现无限存储，希望增加对其的支持。
相关项目：

- [TG-FileStreamBot](https://github.com/EverythingSuckz/TG-FileStreamBot) （Python项目）
- [go-telegram-uploader](https://github.com/techieIsaac/go-telegram-uploader) （Go语言项目）

最后。感谢作者提供这么好的工具，已向多人推荐。

**Comment by Xhofe** [comment]
本程序不存储目录结构信息。tg？好像也没有目录结构
所以不会支持

**Comment by kuilei0926** [comment]
> 本程序不存储目录结构信息。tg？好像也没有目录结构 所以不会支持

可以弄成bot的形式吗？转发文件消息到bot，然后bot提示选择保存路径
