### ISSUE TITLE
用wget 没有办法下载吗

### ISSUE THREAD

**Issue by niu12503** [Xhofe/alist#7]
用wget 提示拒绝连接403

**Comment by Xhofe** [comment]
wget阿里云盘的直链吗？是可以的啊
![image.png](https://img.oez.cc/2020/12/31/df186912de003.png)
直接用直链wget的文件名是错误的，还可以在直链后面加上`/文件名`，也可以直接下载

**Comment by niu12503** [comment]
http://ali.594250.xyz/5fea0ccddf725c1367fa441386a0a4ce2d6bc434

你试试这个能下载吗

**Comment by Xhofe** [comment]
> http://ali.594250.xyz/5fea0ccddf725c1367fa441386a0a4ce2d6bc434
> 
> 你试试这个能下载吗

这个版本太旧了。。当时还没有做文件直链，请更新一下哈

**Comment by niu12503** [comment]
我替换了v0.1.3，并重新开启，还是这样

**Comment by Xhofe** [comment]
前端`dist`与配置文件也需要更新的，除了不用去获取`refresh_token`基本和重新安装一样，请参考部署教程。

**Comment by niu12503** [comment]
谢谢
