### ISSUE TITLE
首页的“复制直链”会复制所有文件的直链

### ISSUE THREAD

**Issue by Hreint** [Xhofe/alist#700]
### Alist Version / Alist 版本

v2.1.3

### Describe the bug / 问题描述

作者您好，

我注意到 alist 的首页也有一个“复制直链”的按键，我点了一下试试，结果发现这是把页面所有文件的直链都加起来了，实际上是个无效的链接。想请问下可否设计成当选中某个文件时，才显示这个按键呢？

另外我想问一下，alist的logo、favicon、音乐封面支不支持本地文件呢？我尝试了一下把前端设置中的目录改成了本地目录，但似乎并不支持。

最后感谢您制作出的优秀作品！

**Comment by Xhofe** [comment]
- 复制直链：非bug，feature
- 支持本地文件，但是需要是链接，你直接填本地路径肯定不行

**Comment by Hreint** [comment]
好的，感谢解答！
