### ISSUE TITLE
请问可以完全隐藏首页吗？

### ISSUE THREAD

**Issue by zhujitop** [Xhofe/alist#708]
### Description of the feature / 需求描述

因为是把网盘里面的文件提供直链给用户下载。
不希望用户可以访问网站首页或者对应文件夹。

就希望访问首页，就显示404或者跳转到别的网站去。
我之前用的隔壁程序可以设置，访问首页就显示404。

或者现在网站首页源代码在哪里，自己改下也行？
看了下文件夹没找到。

现在只能设置隐藏文件夹。

### Suggested solution / 实现思路

就是禁用首页目录类似的功能。

**Comment by shouji123** [comment]
一看就是隔壁来的，这个功能的确很干脆利落，不用一个个设置访问密码，但是本作者好像不是很喜欢这个功能，不知为啥

**Comment by cxkjntm233** [comment]
作者说了这个软件定位就是个人文件列表，估计不会朝那方向做了。但你可以用Nginx给首页路径加上BasicAuth认证，或者禁止其他ip访问首页，location=/{ allow 你的ip;deny all;} ，家宽ip是动态的几天换一次，建议第一种方法。

**Comment by Xhofe** [comment]
禁用首页 你怎么用？

**Comment by shouji123** [comment]
输入管理员密码后，首页就出来了，不输入就是404。。就是这么个操作

**Comment by Xhofe** [comment]
> 输入管理员密码后，首页就出来了，不输入就是404。。就是这么个操作

和直接给`/`加密码有什么区别呢。

**Comment by shouji123** [comment]
断了别人的心思，打开就是404。另外，如果挂载的网盘很多，这样就不用一个个加密码了，不给目录，断掉一切念想

**Comment by Xhofe** [comment]
后台打开`check parent folder`，只给`/`加密码，所有的目录都会被加密。哪里能看到列表

**Comment by zhujitop** [comment]
解决了，谢谢。
用js加了个代码，访问首页就跳转到别的网站去。

我用程序只是为了直链功能，其他用不到。
都还是用官方的去上传管理等。

比如我网盘有个1.zip文件，我只需要把www.abc.com/wj/1.zip链接拿出来给用户下载。

不需要用户访问到www.abc.com、www.abc.com/wj
其他都不需要了，也不想有人去尝试破密码。

**Comment by zhaiwanwang** [comment]
> 

请问如何实现？

**Comment by Acetaol** [comment]
> 解决了，谢谢。用js加了代码，访问首页就跳到其他网站去。
> 
> 我用程序只做直链功能，其他用不了。都还是用官方的去上传管理等。
> 
> 比如我网盘有一个1.zip文件，我只需要把www.abc.com/wj/1.zip链接拿出来给用户下载。
> 
> 不需要用户访问www.abc.com、www.abc.com/wj其他都不需要，也不想有人去尝试破解密码。



> 解决了，谢谢。 用js加了个代码，访问首页就跳转到别的网站去。
> 
> 我用程序只是为了直链功能，其他用不到。 都还是用官方的去上传管理等。
> 
> 比如我网盘有个1.zip文件，我只需要把www.abc.com/wj/1.zip链接拿出来给用户下载。
> 
> 不需要用户访问到www.abc.com、www.abc.com/wj 其他都不需要了，也不想有人去尝试破密码。
怎么解决的，求方法
