### ISSUE TITLE
添加其他的Alist服务时会报错

### ISSUE THREAD

**Issue by 2830514940** [Xhofe/alist#710]
### Alist Version / Alist 版本

v2.1.3

### Describe the bug / 问题描述

添加其他的Alist服务时会报错Invalid token
但实际已经添加完成 只是显示错误

**Comment by Xhofe** [comment]
报错就是你的token 填错了。

**Comment by 2830514940** [comment]
> 报错就是你的token 填错了。

没有填错 实际添加完成了 服务也是正常可用的 只是显示错误

**Comment by Xhofe** [comment]
测试无问题，无报错。
