### ISSUE TITLE
大佬，在阿里网盘APP上传的文件，在alist里一直没有刷新出来，找不到

### ISSUE THREAD

**Issue by caiwenmin** [Xhofe/alist#722]
### Alist Version / Alist 版本

稳定版

### Describe the bug / 问题描述

在阿里网盘APP上传的文件，在alist里一直没有刷新出来，找不到

**Comment by Funny-T** [comment]
进入后台--右上角清除缓存

**Comment by Xhofe** [comment]
1. 有问题应先阅读文档 https://alist-doc.nn.ci/docs/common-question#%E4%B8%8A%E4%BC%A0%E7%9A%84%E6%96%87%E4%BB%B6%E4%B8%8D%E6%98%BE%E7%A4%BA%E5%88%A0%E9%99%A4%E7%9A%84%E6%96%87%E4%BB%B6%E8%BF%98%E5%9C%A8%E4%BF%AE%E6%94%B9%E6%A0%B9%E7%9B%AE%E5%BD%95%E4%B8%8D%E7%94%9F%E6%95%88
> #### 上传的文件不显示/删除的文件还在/修改根目录不生效？
> 程序缓存一小时自动失效，在后台登录之后返回列表，然后到你改动的目录右键刷新即可，不推荐清除所有缓存。

2. 一般问题请到[讨论论坛](https://github.com/Xhofe/alist/discussions) ，issue仅针对错误报告和功能请求
