### ISSUE TITLE
使用非标准端口反代后夸克网盘的文件请求错误

### ISSUE THREAD

**Issue by tpishere** [Xhofe/alist#726]
### Alist Version / Alist 版本

v2.1.3-0-gc63e059

### Describe the bug / 问题描述

在使用nginx反代后夸克网盘的文件请求错误，原因是我使用的是非标准80或443端口，通过f12查看到返回文件链接里的4443端口被删去，导致无法请求文件。
![quark-bug](https://user-images.githubusercontent.com/40019657/157867072-b6c21326-ea91-472e-a642-f0e3eb51a6ae.png)

**Comment by Xhofe** [comment]
反代时请传递正确的host

**Comment by tpishere** [comment]
但是阿里云盘，天翼云盘，本地文件夹都是正常的

> 反代时请传递正确的host

感谢，已解决。问题出在NginxProxyManager配置的反代不会传递host，手动修改配置文件后一切正常。

**Comment by Winyer** [comment]
> > 反代时请传递正确的host
> 
> 感谢，已解决。问题出在NginxProxyManager配置的反代不会传递host，手动修改配置文件后一切正常。

请问该怎么修改呢

**Comment by mlcs-top** [comment]
反代时传递正确的host,复制链接是https://,下载链接确是http://。宝塔开启了端口反代

**Comment by SunRain** [comment]
> > > > 反代时请传递正确的host
> > > 
> > > 
> > > 感谢，已解决。问题出在NginxProxyManager配置的反代不会传递host，手动修改配置文件后一切正常。
> > 
> > 
> > 请问该怎么修改呢
> 
> @Winyer Custom Locations 里面追加 Location：/ 的设定： `proxy_set_header X-Forwarded-Host $http_host;`

目前最新的alist版本,在alist的config.json里面设置site_url的时候,如果不加上上述使用的非标端口,即使按照这个设置配置NginxProxyManager的反代,似乎也不起作用.必须要在alist的config.json里面设置site_url+端口的形式才行(类似site_url": "https://domain.com:port"这样)

**Comment by Simonzhang8** [comment]
> 目前最新的alist版本,在alist的config.json里面设置site_url的时候,如果不加上上述使用的非标端口,即使按照这个设置配置NginxProxyManager的反代,似乎也不起作用.必须要在alist的config.json里面设置site_url+端口的形式才行(类似site_url": "[https://domain.com:port"这样](https://domain.com:port%22%E8%BF%99%E6%A0%B7))

加上这句呢？
`proxy_set_header X-Forwarded-Port $server_port;
`

**Comment by michaelauto** [comment]
> > > > > 反代时请传递正确的host
> > > > 
> > > > 
> > > > 感谢，已解决。问题出在NginxProxyManager配置的反代不会传递host，手动修改配置文件后一切正常。
> > > 
> > > 
> > > 请问该怎么修改呢
> > 
> > 
> > [@Winyer](https://github.com/Winyer) Custom Locations 里面追加 Location：/ 的设定： `proxy_set_header X-Forwarded-Host $http_host;`
> 
> 目前最新的alist版本,在alist的config.json里面设置site_url的时候,如果不加上上述使用的非标端口,即使按照这个设置配置NginxProxyManager的反代,似乎也不起作用.必须要在alist的config.json里面设置site_url+端口的形式才行(类似site_url": "[https://domain.com:port"这样](https://domain.com:port%22%E8%BF%99%E6%A0%B7))

传递host无效,修改site_url有效,如果有多个反代怎么办?
