### ISSUE TITLE
百度网盘下载错误

### ISSUE THREAD

**Issue by 12189108** [Xhofe/alist#731]
### Alist Version / Alist 版本

最新稳定版

### Describe the bug / 问题描述

百度网盘直链会在下载3MB左右后停止下载，速度为0,下载工具:IDM+，User-Agent已修改为规定
![Screenshot_20220312_030117_idm internet download manager plus_edit_2152793892899](https://user-images.githubusercontent.com/24732116/157934601-d6a35c56-65fd-4356-a28e-02fb15215e60.jpg)
![Screenshot_20220312_030135_idm internet download manager plus_edit_2163078060606](https://user-images.githubusercontent.com/24732116/157934628-81675ea6-0cf6-403b-8126-cda3ee6c4eb4.jpg)

**Comment by Xhofe** [comment]
这我也没有办法 取决于百度，使用的是官方api。
