### ISSUE TITLE
onedrive配置后无法访问文件

### ISSUE THREAD

**Issue by likepoems** [Xhofe/alist#736]
### Alist Version / Alist 版本

v2.1.3

### Describe the bug / 问题描述

onedrive按照视频配置后无法访问

### Reproduction / 复现链接

https://pan.likepoems.com/onedrive

### 日志 / Logs

```shell
Get "//%2Fchildren%3F$expand=thumbnails/children?$expand=thumbnails": unsupported protocol scheme ""
```

**Comment by Xhofe** [comment]
#622
