### ISSUE TITLE
停止再启动出现错误

### ISSUE THREAD

**Issue by jing207** [Xhofe/alist#74]
INFO[2021-04-02 04:15:52] 检查更新...                                      
panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
github.com/Xhofe/alist/bootstrap.CheckUpdate()
        /home/runner/work/alist/alist/bootstrap/update.go:39 +0x56c
github.com/Xhofe/alist/bootstrap.start()
        /home/runner/work/alist/alist/bootstrap/cmd.go:53 +0x245
github.com/Xhofe/alist/bootstrap.Run()
        /home/runner/work/alist/alist/bootstrap/cmd.go:31 +0xfe
main.main()
        /home/runner/work/alist/alist/alist.go:7 +0x25
[1]+  Exit 2                  nohup ./alist > log.log 2>&1
[root@www-xxx-cc aliyun.xxx.cc]# chmod +x alist
[root@www-xxx-cc aliyun.xxx.cc]# nohup ./alist > log.log 2>&1 &
[1] 1596517
[root@www-xxx-cc aliyun.xxx.cc]# cat log.log
nohup: ignoring input
INFO[2021-04-02 04:18:34] 
 ________  ___       ___  ________  _________   
|\   __  \|\  \     |\  \|\   ____\|\___   ___\ 
\ \  \|\  \ \  \    \ \  \ \  \___|\|___ \  \_| 
 \ \   __  \ \  \    \ \  \ \_____  \   \ \  \  
  \ \  \ \  \ \  \____\ \  \|____|\  \   \ \  \ 
   \ \__\ \__\ \_______\ \__\____\_\  \   \ \__\
    \|__|\|__|\|_______|\|__|\_________\   \|__|
                            \|_________| 
INFO[2021-04-02 04:18:34] 检查更新...                                      
panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
github.com/Xhofe/alist/bootstrap.CheckUpdate()
        /home/runner/work/alist/alist/bootstrap/update.go:39 +0x56c
github.com/Xhofe/alist/bootstrap.start()
        /home/runner/work/alist/alist/bootstrap/cmd.go:53 +0x245
github.com/Xhofe/alist/bootstrap.Run()
        /home/runner/work/alist/alist/bootstrap/cmd.go:31 +0xfe
main.main()
        /home/runner/work/alist/alist/alist.go:7 +0x25
[1]+  Exit 2                  nohup ./alist > log.log 2>&1
[root@www-xxx-cc aliyun.xxx.cc]# systemctl start alist
[root@www-xxx-cc aliyun.xxx.cc]# systemctl enable alist
[root@www-xxx-cc aliyun.xxx.cc]# systemctl status alist
● alist.service - alist
   Loaded: loaded (/usr/lib/systemd/system/alist.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2021-04-02 04:22:15 CST; 1min 2s ago
 Main PID: 1597267 (code=exited, status=2)

Apr 02 04:22:15 www-xxx-cc systemd[1]: alist.service: Service RestartSec=100ms expired, scheduling restart.
Apr 02 04:22:15 www-xxx-cc systemd[1]: alist.service: Scheduled restart job, restart counter is at 5.
Apr 02 04:22:15 www-xxx-cc systemd[1]: Stopped alist.
Apr 02 04:22:15 www-xxx-cc systemd[1]: alist.service: Start request repeated too quickly.
Apr 02 04:22:15 www-xxx-cc systemd[1]: alist.service: Failed with result 'exit-code'.
Apr 02 04:22:15 www-xxx-cc systemd[1]: Failed to start alist.

**Comment by Xhofe** [comment]
启动的时候加入-skip-update参数。
