### ISSUE TITLE
阿里云盘视频音乐

### ISSUE THREAD

**Issue by dejavua** [Xhofe/alist#746]
### Alist Version / Alist 版本

2.2

### Describe the bug / 问题描述

docker搭建服务端成功以后阿里云盘视频音乐均都无法播放，请问是什么原因
![image](https://user-images.githubusercontent.com/97790577/158121835-324d098e-ab17-4d51-bba4-b9b0c4579b5a.png)

**Comment by dejavua** [comment]
阿里云盘和其他网盘，视频音乐均不能播放

**Comment by FrozenSky7124** [comment]
> 阿里云盘和其他网盘，视频音乐均不能播放

我这里正常播放啊，也是 docker:v2.2 + 阿里云盘。

**Comment by zhuziyi1989** [comment]
手机端 iPhone 不能播放，PC端可以。

**Comment by dejavua** [comment]
音乐无法播放一直转圈，手机电脑都一样

**Comment by ding113** [comment]
> 手机端 iPhone 不能播放，PC端可以。

这个好像是系统自带的QuickTime解码问题
换用一些第三方浏览器就可以解决了

**Comment by zhuziyi1989** [comment]
> 

油猴脚本 DPlayer 是可以的，应该是播放器的问题~ 

可以参考这个脚本  https://greasyfork.org/scripts/425955-%E9%98%BF%E9%87%8C%E4%BA%91%E7%9B%98/code/%E9%98%BF%E9%87%8C%E4%BA%91%E7%9B%98.user.js
