### ISSUE TITLE
阿里云盘删除操作无效

### ISSUE THREAD

**Issue by 12189108** [Xhofe/alist#750]
### Alist Version / Alist 版本

v2.1.3-0-gc63e059-dirty

### Describe the bug / 问题描述

管理员身份进入，选择某一文件，操作-删除，进官网，发现文件仍未删除

**Comment by Xhofe** [comment]
测试正常。无法复现

**Comment by 12189108** [comment]
更新至v2.2.0-0-g15651a4-dirty后问题仍存在

**Comment by 12189108** [comment]
https://download.hamsterrider.top/d/%E9%98%BF%E9%87%8C%E4%BA%91%E7%9B%98/Alist%20-%20Google%20Chrome%202022-03-14%2019-52-54.mp4

**Comment by 12189108** [comment]
上述链接为复现步骤视频

**Comment by Xhofe** [comment]
你的安全策略禁止了delete请求 请自检。
