### ISSUE TITLE
疑似不能使用ssl连接mysql

### ISSUE THREAD

**Issue by Jakob-Boy** [Xhofe/alist#758]
### Alist Version / Alist 版本

v2.2.0

### Describe the bug / 问题描述

hello，希望使用Mysql做数据库，已经修改data/config.json文件，但是mysql必须要用ssl连接方式，我设置了"ssl_mode": "VERIFY_IDENTITY",运行依旧提示”failed to connect database:Error 1105: unknown error: Code: UNAVAILABLE
server does not allow insecure connections, client must use SSL/TLS“，请问是程序本身不支持ssl模式连接mysql吗？还是说我语法错误呢？因为不是很了解go语言的程序，python中是设置为"VERIFY_IDENTITY"，麻烦作者查看下！
+ 运行环境：linux-amd64
+ 运行方式：使用手动部署，下载[Releases]中的文件运行

### Logs / 日志

```shell
INFO[2022-03-15 08:47:57] reading config file: data/config.json        
INFO[2022-03-15 08:47:57] init cron...                                 
INFO[2022-03-15 08:47:57] init model...                                
FATA[2022-03-15 08:47:58] failed to connect database:Error 1105: unknown error: Code: UNAVAILABLE
server does not allow insecure connections, client must use SSL/TLS
```

**Comment by Xhofe** [comment]
请测试 https://github.com/Xhofe/alist/actions/runs/1985673429

**Comment by Jakob-Boy** [comment]
hello，非常感谢你的协助，已测试，数据库连接正常，服务端检测到连接并产生数据，补充一点，对于ssl_mode这个参数，value需要填写true，这点与Python不同哈。
<a href="https://imgtu.com/i/bxf9VP"><img src="https://s1.ax1x.com/2022/03/15/bxf9VP.png" alt="bxf9VP.png" border="0" /></a>
<a href="https://imgtu.com/i/bxfuV0"><img src="https://s1.ax1x.com/2022/03/15/bxfuV0.png" alt="bxfuV0.png" border="0" /></a>
<a href="https://imgtu.com/i/bxflPU"><img src="https://s1.ax1x.com/2022/03/15/bxflPU.png" alt="bxflPU.png" border="0" /></a>

**Comment by Jakob-Boy** [comment]
> 请测试 https://github.com/Xhofe/alist/actions/runs/1985673429

已完成测试，结果如上，感谢！
