### ISSUE TITLE
pikpak下载时候文件名缺失问题

### ISSUE THREAD

**Issue by lnran** [Xhofe/alist#759]
### Alist Version / Alist 版本

v2.2.0

### Describe the bug / 问题描述

网盘文件没有问题，然后第三方下载器IDM复制下载链接也能正常下载，但是点下载让浏览器下载会出现文件名和后缀名缺失问题，例如文件名字为“1.zip”，浏览器下载的是“下载”，而不是原本文件名“1.zip”

**Comment by lnran** [comment]
补充，使用的浏览器为Edge

**Comment by Xhofe** [comment]
在次解释一下原因：是因为pikpak的服务器在`content-disposition`头中没有设置文件名，所以这是pikpak的问题 而不是alist。

**Comment by missuo** [comment]
@Xhofe 目前没有任何办法解决嘛？

**Comment by chengnan049** [comment]
> 因为 pikpak 的服务器在 `content-disposition` 头中没有设置文件名，所以这是 pikpak 的问题 而不是 alist。

这是 PikPak 的问题，暂时没有方案

**Comment by haoges** [comment]
打开wed代理就行看

**Comment by haoges** [comment]
要开web代理才正常
