### ISSUE TITLE
音乐播放器下一首请求参数没有密码

### ISSUE THREAD

**Issue by w311ang** [Xhofe/alist#77]
错误请求
![Screenshot_20210404-160004](https://user-images.githubusercontent.com/30381083/113502439-e5374080-955e-11eb-95dc-0510ad8c659e.jpg)
![Screenshot_20210404-160007](https://user-images.githubusercontent.com/30381083/113502442-e9635e00-955e-11eb-8c69-38c302ed020b.jpg)
正确请求
![Screenshot_20210404-160104_Mosaic_16_1_18](https://user-images.githubusercontent.com/30381083/113502471-19aafc80-955f-11eb-9184-c9a8ff15a81e.jpg)

**Comment by Xhofe** [comment]
https://github.com/Xhofe/alist-web/commit/d899cbfc8d5f2caf6bae1046a8b4768a9a560398
