### ISSUE TITLE
希望增加 aria2 支持

### ISSUE THREAD

**Issue by slarkcoder** [Xhofe/alist#786]
### Description of the feature / 需求描述

有时候需要将文件下载到本地，文件多的时候一个个复制直链下载有点麻烦，如果能增加批量添加到 aria2 下载就好了

**Comment by Xhofe** [comment]
aria2不支持批量添加下载链接吗

**Comment by xixky** [comment]
> aria2不支持批量添加下载链接吗

aria2添加下载链接，进行302重定向，文件名会变成重定向网站的文件名。

**Comment by Xhofe** [comment]
> > aria2不支持批量添加下载链接吗
> 
> aria2添加下载链接，进行302重定向，文件名会变成重定向网站的文件名。

那我也没办法。

**Comment by shaojs321** [comment]
> 

[tele-aria2](https://github.com/HouCoder/tele-aria2)  大佬，这个项目可以一次性在aria添加大量下载链接(包含磁力，直链，种子)，能否整合一下

**Comment by Xhofe** [comment]
> > 
> 
> [tele-aria2](https://github.com/HouCoder/tele-aria2) 大佬，这个项目可以一次性在aria添加大量下载链接(包含磁力，直链，种子)，能否整合一下

你想怎么整合

**Comment by Windman1320** [comment]
@slarkcoder 最近加了一个右键使用aria2下载的功能，可以先看看，还在完善当中，目前仅支持单个文件下载
https://github.com/Windman1320/alist-web
