### ISSUE TITLE
蓝奏云不支持特殊链接格式

### ISSUE THREAD

**Issue by fengguowudi** [Xhofe/alist#788]
### Alist Version / Alist 版本

v2.2.0

### Describe the bug / 问题描述

当使用定制链接时无法获取文件列表

### Reproduction / 复现链接

https://www.lanzoux.com/u/yoyodadada

**Comment by fengguowudi** [comment]
网站：https://cloud.feng666.tk/%E8%B6%85%E5%BC%BA%E7%A0%B4%E8%A7%A3%E5%90%88%E9%9B%86

**Comment by Xhofe** [comment]
这不是好好的吗 有什么问题

**Comment by fengguowudi** [comment]
你能看见文件？？

**Comment by fengguowudi** [comment]
只有圆圈在转啊

**Comment by Xhofe** [comment]
那是因为你的文件太多了。很卡
