### ISSUE TITLE
rebuild一直转圈，无法重建目录

### ISSUE THREAD

**Issue by andrewjr1991** [Xhofe/alist#79]
不知道是不是文件变多的关系还是怎么的，重建目录就一直转圈，无法显示成功，就不停的转，更新前倒是没这个问题，不知道是否是个例啊

**Comment by Xhofe** [comment]
可以看一下后端是否有报错

**Comment by andrewjr1991** [comment]
最近太忙，明天看看后端，后来就是放那里不管，过了很久刷新之后目录出来了。但是确实很慢的。

**Comment by andrewjr1991** [comment]
> 可以看一下后端是否有报错

![微信图片_20210413140001](https://user-images.githubusercontent.com/20033630/114503882-91181480-9c60-11eb-8ffb-6facbefb65b1.png)

后端长这样，有没有问题呢？就是一直转，等个几十分钟刷新后 目录是可以出来的，但是确实不太方便，因为每次都会这样，而且 一旦没刷新成功目录就直接没了
