### ISSUE TITLE
非80端口的站点，视频预览是请求的连接用的是80端口

### ISSUE THREAD

**Issue by tidymoon** [Xhofe/alist#792]
### Alist Version / Alist 版本

v2.2.0-0-g15651a4-dirty

### Describe the bug / 问题描述

![image](https://user-images.githubusercontent.com/73995927/159147021-d6b42316-0446-411f-b456-7b7fdf5fa5bd.png)
如图，旧版本的话不会有这个问题

**Comment by tidymoon** [comment]
您好，翻了一圈，好像没有相关的问题吧？

**Comment by Xhofe** [comment]
#726
