### ISSUE TITLE
多个代理手动选择

### ISSUE THREAD

**Issue by Tasle** [Xhofe/alist#793]
### Description of the feature / 需求描述

高峰期用cf有点卡，想用另外小鸡代理和cf切换着用，可不可以在down_proxy_url填入多条，需要用哪条手动指定下。现在是cf和自己小鸡代理的网址记在本地，需要切换再进后台更改

**Comment by Xhofe** [comment]
你想怎么手动指定。

**Comment by Tasle** [comment]
> 你想怎么手动指定。

后台代理开关旁手动选择哪个代理，或者down_proxy_url可填入多个，默认第一个。其实也不会经常切换，但是每次切都要去记事本找地址比较麻烦
