### ISSUE TITLE
请问未来是否可以部署在轻应用上？

### ISSUE THREAD

**Issue by W4J1e** [Xhofe/alist#794]
### Description of the feature / 需求描述

您好，
很感谢您的付出，以至于Alist可以在众多平台快捷部署。我尝试过部署在服务器（winserver），也尝试过部署在其它的“serverless”平台（除了vercel没有细细研究过这些平台），但觉得都不够好用（速度）。
字节有一款产品叫“轻服务”，对开发者免费开放试用，只有有少数限制。

### Suggested solution / 实现思路

目前该平台支持NodeJS语言和静态页面部署，对于Golang的支持应该也快了。
不知道是否可以等支持以后直接适配还是需要像另外几个平台一样重新弄，所以请问开发者该计划是否可行以及是否会考虑。
谢谢。

**Comment by Xhofe** [comment]
不会支持云函数平台。
