### ISSUE TITLE
可以设置视频文件自动播放吗

### ISSUE THREAD

**Issue by vbskycn** [Xhofe/alist#8]
老大你好，这个程序非常好！
网盘列表程序速度很快
就是那个视频文件能搞成自动播放吗？
还是有txt文件，pdf文件等比较常见的文件可否网页在线打开呢？
oneindex这个方面就挺好的，页面也挺好看，就是onedrive速度慢！

**Comment by vbskycn** [comment]
对了，还有一个小问题
在微信里面打开链接后
页面不会自动适应手机屏幕
左边的文字被挡住，而且不能移动

用手机播放的时候，播放器太高了，有好大的黑边，不知道是不是dplayer的原因

**Comment by Xhofe** [comment]
> 老大你好，这个程序非常好！
> 网盘列表程序速度很快
> 就是那个视频文件能搞成自动播放吗？
> 还是有txt文件，pdf文件等比较常见的文件可否网页在线打开呢？
> oneindex这个方面就挺好的，页面也挺好看，就是onedrive速度慢！

额，视频自动播放可以，但是感觉大部分人可能没有这个需求，下个版本加入配置文件可选自动播放吧。关于更多常见文件的预览，之前试过`office viewer`，但是获取不到文件，目前找到了`kkfileview`这个项目，等部署好之后会加入。

**Comment by Xhofe** [comment]
> 对了，还有一个小问题
> 在微信里面打开链接后
> 页面不会自动适应手机屏幕
> 左边的文字被挡住，而且不能移动
> 
> 用手机播放的时候，播放器太高了，有好大的黑边，不知道是不是dplayer的原因

微信不自动适应手机屏幕的问题，我试了一下，ios端微信好像没有问题啊。。
手机播放视频播放器太高是我的锅，因为css太菜了，使用flex布局之后，好像只试过设置固定的宽度页面才正常。。然后就主要只写了电脑端的高度。之后会寻找一下更好的解决方案，如果不行就给移动端用`@media`重写一下高度。

**Comment by vbskycn** [comment]
感谢大佬回复，静候老大的下一个版本
