### ISSUE TITLE
功能建议： 大佬能否添加个docker镜像方便部署？

### ISSUE THREAD

**Issue by xingkong0113** [Xhofe/alist#80]
当前在更新和升级的过程中，需要从[alist](https://github.com/Xhofe/alist)和[alist-web](https://github.com/Xhofe/alist-web.git)两个仓库下载文件进行替换和更新。
假如有个docker镜像是不是可以减少更新和部署的时间？
有需要的朋友可以在下面发表个人的看法。
感谢作者开发了这个好用的阿里网盘挂在程序。

**Comment by hbestm** [comment]
我鼓捣了一个，可以看看，alist_docker，同步大佬的

**Comment by dingpengyu** [comment]
> 我鼓捣了一个，可以看看，alist_docker，同步大佬的

感谢，搜索看看。

**Comment by sbwml** [comment]
# 使用 Docker 安装（支持 linux/386/amd64/armv7/armv8 架构）

## Docker Hub：https://hub.docker.com/r/sbwml/alist

------

### 创建 Alist 容器
```bash
docker run -d --restart=always -v /etc/alist:/alist/config -p 5244:5244 --name="alist" sbwml/alist:latest
```

### 写入 refresh_token
```bash
vi /etc/alist/conf.yml
```
**refresh_token: xxx**   修改 xxx 为你的 refresh_token。

更多：https://www.nn.ci/archives/alist.html

### 重启 Alist 容器
```bash
docker restart alist
```

### 访问 Alist
现在你可以通过：http://ip地址:5244/  访问到Alist

**Comment by xiaokaixuan** [comment]
<blockquote><details>
<summary>使用 Docker 安装（支持 linux/386/amd64/armv7/armv8 架构）</summary>

> # 使用 Docker 安装（支持 linux/386/amd64/armv7/armv8 架构）
> ## Docker Hub：https://hub.docker.com/r/sbwml/alist
> ### 创建 Alist 容器
> ```shell
> docker run -d --restart=always -v /etc/alist:/alist/config -p 5244:5244 --name="alist" sbwml/alist:latest
> ```
> 
> ### 写入 refresh_token
> ```shell
> vi /etc/alist/conf.yml
> ```
> 
> **refresh_token: xxx** 修改 xxx 为你的 refresh_token。
> 
> 更多：https://www.nn.ci/archives/alist.html
> 
> ### 重启 Alist 容器
> ```shell
> docker restart alist
> ```
> 
> ### 访问 Alist
> 现在你可以通过：[http://ip地址:5244/](http://ip%E5%9C%B0%E5%9D%80:5244/) 访问到Alist
</details></blockquote>

本来想自己做个镜像的。这个已经用上了，很好用，希望持续更新。

**Comment by sbwml** [comment]
> > 使用 Docker 安装（支持 linux/386/amd64/armv7/armv8 架构）
> > > # 使用 Docker 安装（支持 linux/386/amd64/armv7/armv8 架构）
> > > ## Docker Hub：https://hub.docker.com/r/sbwml/alist
> > > ### 创建 Alist 容器
> > > ```shell
> > > docker run -d --restart=always -v /etc/alist:/alist/config -p 5244:5244 --name="alist" sbwml/alist:latest
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ### 写入 refresh_token
> > > ```shell
> > > vi /etc/alist/conf.yml
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > **refresh_token: xxx** 修改 xxx 为你的 refresh_token。
> > > 更多：https://www.nn.ci/archives/alist.html
> > > ### 重启 Alist 容器
> > > ```shell
> > > docker restart alist
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ### 访问 Alist
> > > 现在你可以通过：[http://ip地址:5244/](http://ip%E5%9C%B0%E5%9D%80:5244/) 访问到Alist
> 
> 本来想自己做个镜像的。这个已经用上了，很好用，希望持续更新。

docker镜像已经加入自动化构建，如无意外，只要alist 一直更新，docker 也会同步更新

**Comment by xiaokaixuan** [comment]
我也做了个镜像 https://github.com/xiaokaixuan/rslsync/tree/master/alist
