### ISSUE TITLE
针对网页播放器不支持的格式增加唤起本地播放器功能

### ISSUE THREAD

**Issue by lonzoen** [Xhofe/alist#819]
### Description of the feature / 需求描述

有些格式网页无法播放，希望能在下方添加iina、potplayer打开等选项。

### Suggested solution / 实现思路

对文件扩展名进行监测，视频格式则增加客户端打开。

**Comment by Xhofe** [comment]
。。。你用了吗

**Comment by lonzoen** [comment]
我用了啊，也没找到在哪设置。
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/22364270/160220771-cfe49026-8162-4eb5-9b63-7c27ad434874.png">

**Comment by Xhofe** [comment]
那你直接说后缀就行了，描述不清楚。
