### ISSUE TITLE
WebDAV

### ISSUE THREAD

**Issue by bb2103** [Xhofe/alist#82]
相对于Web，其实WebDAV更加方便，好奇后面有兴趣跟进否？

**Comment by hugoyue** [comment]
[zxbu/webdav-aliyundriver](https://github.com/zxbu/webdav-aliyundriver)

**Comment by coderykw** [comment]
> [zxbu/webdav-aliyundriver](https://github.com/zxbu/webdav-aliyundriver)

这个挂服务器 占用服务器网速的

**Comment by liuluping0106** [comment]
同希望能够集成webdav功能

**Comment by zzy-ac** [comment]
如果同时挂载了一个onedrive一个aliyun怎么webdav到某一个呢
直接输名称会报错

**Comment by bb2103** [comment]
这是来自我的自动回复邮件。

您好，我已经收到您的邮件.我会在我下次登录邮箱时尽快回复你的邮件，谢谢。I have Received your email,I'll reply you asap.

**Comment by coderykw** [comment]
【自动回复】qq邮箱不可交流，请联系网站客服哦！

**Comment by zzy-ac** [comment]
抱歉修改一下问题，刚刚发现在其他webdav客户端应该是好的（至少ES文件浏览器上是好的）。
目前好像只有koreader阅读软件自带的webdav插件是不支持在alist上创建多个账号的，创建了多个账号之后koreader的webdav就无法成功按照目录访问某个网盘里面的文件了。

**Comment by Xhofe** [comment]
已经逐步支持
