### ISSUE TITLE
默认本地 assets 目录下能否放一个默认的 logo 和 favicon.ico

### ISSUE THREAD

**Issue by ihotte** [Xhofe/alist#829]
### Description of the feature / 需求描述

默认本地 assets 目录下能否放一个默认的 logo 和 favicon.ico？

现在需要完全自定义

- 本地托管，需要搭建 web 服务器托管这两个图片资源。
- 使用三方 CDN 经常失效，要不就需要科学上网速度极慢

建议将这两组图片打包进 `alist-web`

https://github.com/alist-org/logo

```
/assets/favicon.{svg,png}
/assets/logo.{svg,png}
```

**Comment by Xhofe** [comment]
alist本身就是一个web服务器，添加本地存储复制直链即可。

**Comment by jinwyp** [comment]
默认设置为什么要直接内置CDN 链接? 直接应该内置在前端代码里面啊

**Comment by ihotte** [comment]
> 默认设置为什么要直接内置CDN 链接? 直接应该内置在前端代码里面啊

不理解出于什么考虑，要把这两张图片单独拿出来
