### ISSUE TITLE
功能建议: 网盘上传功能和丰富前端文档

### ISSUE THREAD

**Issue by Aquaakuma** [Xhofe/alist#83]
1 网盘上传功能，不过要实现这个就得和别的网盘索引一样的管理页面了，不知道大佬是想做一个特色的项目还是做一个通用的。
2 还有希望自定义一些外观，要是能丰富一下文档或者添加一些接口就好了。

**Comment by Xhofe** [comment]
http://alist-doc.nn.ci/
