### ISSUE TITLE
189CloudPC WebDAV 无法上传百兆文件

### ISSUE THREAD

**Issue by ixiumu** [Xhofe/alist#832]
### Alist Version / Alist 版本

v2.2.0

### Describe the bug / 问题描述

小文件正常,大文件每次都会卡99% 然后报错

### Reproduction / 复现链接

网络错误：连接"*.*.*.*"超时。
Could not read status line: connection timed out

**Comment by Xhofe** [comment]
需要错误日志。

**Comment by ixiumu** [comment]
修改了 DefaultTimeout 之后正常了, 不知我是不是个例
