### ISSUE TITLE
建议加个账号【禁用/启用】功能

### ISSUE THREAD

**Issue by OJZen** [Xhofe/alist#833]
### Description of the feature / 需求描述

当我想暂时移除某个网盘账号的时候就进行删除操作，但如果我仅仅只是临时移除，待其他事做完之后就重新启用时，又要重新添加。

复制粘贴的功能很好用，但不是很合适。

希望有个按钮能够实现账号的**启用**或者**禁用**。

### Suggested solution / 实现思路

无

### Additional context / 附件

无

**Comment by Xhofe** [comment]
禁用不就是另一种隐藏吗 隐藏就好了。

**Comment by OJZen** [comment]
> 禁用不就是另一种隐藏吗 隐藏就好了。


好的，已知晓。感谢回复。
