### ISSUE TITLE
文件夹和文件排序问题

### ISSUE THREAD

**Issue by Lizh6** [Xhofe/alist#837]
### Description of the feature / 需求描述

文件夹默认在文件上面，现在文件夹和文件是混着的

### Suggested solution / 实现思路

文件夹在上面，按首字母排列，文件全在文件夹下面

### Additional context / 附件

无

**Comment by Xhofe** [comment]
提issue前请阅读文档 https://alist-doc.nn.ci/docs/driver/base#extract_folder
