### ISSUE TITLE
webdav下载本地失败，提示S-1-1-0权限错误

### ISSUE THREAD

**Issue by 404gods** [Xhofe/alist#847]
### Alist Version / Alist 版本

7126873

### Describe the bug / 问题描述

讨论区没人回只好发这里了
我用raidrive 挂载了Alist上的天翼云盘做测试，上传基本正常了，下载如果：
1、proxy开、webdav_proxy开、webdav direct关 ，下载报错，需要S-1-1-0权限。
2、proxy关、webdav_proxy关、webdav direct关 ，下载报错，需要S-1-1-0权限。
3、proxy关、webdav_proxy关、webdav direct开 ，下载成功，但是下载速度超级慢，只有几百KB/秒。

夸克云也测试了，不开webdav direct 就下载失败，开了会成功，但是速度同样超级慢。
![photo_2022-03-29_13-31-50](https://user-images.githubusercontent.com/50573302/160566724-2aafcc9a-3296-49f0-b452-046fe8710dbf.jpg)

### Reproduction / 复现链接

无

### Logs / 日志

```shell
无
```

**Comment by michealhansun** [comment]
天翼云盘同样问题，无法下载，提升s-1-1-0 权限问题，哥们，你已经解决了吗

**Comment by ahdev713** [comment]
我的问题是百度中的解压文件复制不出来 报没权限s-1-1-0
见图设置生效
![image](https://user-images.githubusercontent.com/91399172/231107756-319df2f4-41f1-4605-9275-45e7e6502748.png)
