### ISSUE TITLE
 certificate signed by unknown authority

### ISSUE THREAD

**Issue by keac** [Xhofe/alist#85]
certificate signed by unknown authority

{"meta":{"code":500,"msg":"Post \"https://api.aliyundrive.com/v2/file/get_download_url\": x509: certificate signed by unknown authority"}}

**Comment by yanhan-dev** [comment]
same error

**Comment by guokes** [comment]
ERRO[2021-04-09 10:25:23] 请求阿里云盘api时出错:Post "https://auth.aliyundrive.com/v2/account/token": x509: certificate signed by unknown authority
