### ISSUE TITLE
curl 无法下载合彩云直链

### ISSUE THREAD

**Issue by OPPO9008** [Xhofe/alist#851]
### Alist Version / Alist 版本

v2.2.0-0-g15651a4-dirty

### Describe the bug / 问题描述

curl 无法下载 合彩云网盘的链接 
估计是无法302跳转

### Reproduction / 复现链接

https://alist.xhofe.top/139/rename/Screenrecorder-2021-12-31-23-58-20-945.mp4

### Logs / 日志

```shell
<a href="https://download.mcloud.139.com:443/storageWeb/servlet
/downloadServlet?code=S0EwVzExblZwU3c1UEYwODcxN3JhWDNQaS1V&amp;
un=63F1F5B2C1D4F50B88755E8797723233F263A6E6F562812E71E49504AECB
C202&amp;dom=D961&amp;rate=0&amp;txType=0">Found</a>.
```

**Comment by Xhofe** [comment]
curl怎么用也要我教吗？
