### ISSUE TITLE
阿里网盘refresh_token（刷新令牌）获取不到token 

### ISSUE THREAD

**Issue by 21945764** [Xhofe/alist#860]
### Alist Version / Alist 版本

v2.2.0-0-g15651a4

### Describe the bug / 问题描述

![屏幕截图 2022-03-30 212437](https://user-images.githubusercontent.com/69493877/160844979-dd3c5f0a-d7ab-46f3-b149-9244f12fdc9b.png)

### Reproduction / 复现链接

https://alist-doc.nn.ci/docs/driver/aliyundrive/

**Comment by Xhofe** [comment]
我测试正常，
<img width="2083" alt="image" src="https://user-images.githubusercontent.com/36558727/160859168-2a907765-5091-4e76-b02f-3a08e8c9693a.png">
用不了就自己[抓包](https://github.com/Xhofe/alist/issues/88)或者用安卓的手机找日志。
