### ISSUE TITLE
增加ReBuild 指定位置

### ISSUE THREAD

**Issue by hais1992** [Xhofe/alist#87]
由于网盘中会经常上传文件，每次ReBuild会全盘不可用， 能不能在Rebuild的时候增加个路径参数，单独更新那个位置的缓存？

**Comment by Xhofe** [comment]
之后会增加路径与深度。

**Comment by hais1992** [comment]
> 之后会增加路径与深度。

看了下大佬最近上传的'指定path和深度build',自己编译已经使用上了~ 只是感觉大佬还需要增加一个传入路径后假如上级不存在的话就从上级开始Build

**Comment by yang9w** [comment]
> > 之后会增加路径与深度。
> 
> 看了下大佬最近上传的'指定路径和深度构建'，自己编译已经使用上了〜只是感觉大佬还需要增加一个位移路径后假设上级不存在的话就从上级开始Build

指定路径的这个怎么弄？求解。

**Comment by hais1992** [comment]
> > > 之后会增加路径与深度。
> > 
> > 
> > 看了下大佬最近上传的'指定路径和深度构建'，自己编译已经使用上了〜只是感觉大佬还需要增加一个位移路径后假设上级不存在的话就从上级开始Build
> 
> 指定路径的这个怎么弄？求解。

目前作者没更新，所以需要自己下载代码来编译，【注：前端也未适配rebuild,我是直接拿第三方工具更新缓存】
