### ISSUE TITLE
window server2012 密码初始化显示错误

### ISSUE THREAD

**Issue by jy1989** [Xhofe/alist#876]
### Alist Version / Alist 版本

v2.3.0

### Describe the bug / 问题描述

![image](https://user-images.githubusercontent.com/1291756/161181030-0bf2784d-97fc-429f-9f43-111db927dca4.png)

### Reproduction / 复现链接

![image](https://user-images.githubusercontent.com/1291756/161181109-8a490a5d-093b-4bb8-b512-a8a69498cc56.png)

**Comment by Xhofe** [comment]
#868
