### ISSUE TITLE
关于隐藏功能优化的需求

### ISSUE THREAD

**Issue by ben-august** [Xhofe/alist#879]
### Description of the feature / 需求描述

两个需求：
1、例如阿里云盘文件夹结构是a/b/c/...，a/d/e/...，想实现把子目录文件夹例如e/开放给访客使用。
目前实现的方法是：同一个阿里云账户在alist里添加两次，第一个账号为了自己使用所以“根目录file_id”为root（所有文件均可访问），第二个账号为了只暴露e目录，所以根目录file_id为e对应的file_id。然后在元信息里设置第二个账号的访问密码即可，这样访客输入密码访问主页直接就是显示的e目录下的内容，而不是a/d/e这种结构了（如果只添加一个账号通过隐藏功能实现的话）。
缺点：因为同个账户同时添加了两次，所以管理员访问主页的时候会出现两个文件夹，而且文件夹是是包含的关系，感觉很杂乱而且没必要。所以希望能支持访客输入密码访问主页的时候“直接”显示对应的目录（主要是子目录）。
2、隐藏功能目前只是在web前端不显示而已，如果访客能猜到目录结构，例如开放的是“阿里云盘”这个文件夹，访客很容易的就猜到可能还有“百度云盘”文件夹，于是通过“https://example.com/百度云盘”实现了访问。希望后续能优化！

### Additional context / 附件

<img width="1019" alt="截屏2022-04-01 上午11 56 09" src="https://user-images.githubusercontent.com/36500518/161192305-e8aa251c-286b-41cf-befa-69df3c0912e9.png">
<img width="1044" alt="截屏2022-04-01 上午11 56 25" src="https://user-images.githubusercontent.com/36500518/161192308-0fc87c2e-78b7-4931-9e94-be136f20a26c.png">
<img width="1064" alt="截屏2022-04-01 上午11 57 01" src="https://user-images.githubusercontent.com/36500518/161192333-b448fed5-1977-47d5-be1d-c64125b2378b.png">
<img width="1063" alt="截屏2022-04-01 上午11 56 51" src="https://user-images.githubusercontent.com/36500518/161192334-3243b2a1-3ecb-41f9-b3b0-e4339c101b19.png">

**Comment by Xhofe** [comment]
1. 会让逻辑变得很复杂，不会添加
2. 觉得不安全可以根目录全盘加密
