### ISSUE TITLE
无法在线打开pdf文件，以及打开pdf所使用的静态能否自己托管

### ISSUE THREAD

**Issue by yn68** [Xhofe/alist#887]
### Alist Version / Alist 版本

v2.2.0

### Describe the bug / 问题描述

无法在线打开pdf文件
载入 PDF 时发生错误。 
PDF.js v2.12.305 (build: d3e1d7090)
信息：Failed to fetch

还有是否能自己托管打开pdf所用的静态文件，我看目前是用的jsdelivr

### Reproduction / 复现链接

[pdf](https://p.yn68.cn/acp/%E9%98%BF%E9%87%8C%E4%BA%91%E4%BA%91%E8%AE%A1%E7%AE%97ACP%E8%AE%A4%E8%AF%81%E5%9F%B9%E8%AE%AD%E8%AF%BE%E7%A8%8B.pdf)

**Comment by Xhofe** [comment]
你需要更新。pdf暂不考虑自托管。
