### ISSUE TITLE
使用ES文件管理器挂载WebDAV无法对文件进行任何操作

### ISSUE THREAD

**Issue by ChirmyRam** [Xhofe/alist#893]
### Alist Version / Alist 版本

v2.3.2

### Describe the bug / 问题描述

使用的ES版本：
https://www.coolapk.com/apk/com.estrongs.android.pop
挂载WebDAV无法对文件进行任何操作，比如打开、复制，无论无论使用管理账号还是访客账号。
![Screenshot_2022-04-03-13-01-59-82_846b44643ec609f507828878741e1f9a](https://user-images.githubusercontent.com/34760505/161413071-3325edfc-9741-4294-86d7-29194d2d6ded.jpg)

### Reproduction / 复现链接

https://www.coolapk.com/apk/com.estrongs.android.pop

**Comment by Xhofe** [comment]
onedrive?
es文件浏览器会默认将webdav的验证加在所有请求上，部分网盘带上Authorization头之后就会返回失败。

这只能通过中转解决。

**Comment by ChirmyRam** [comment]
明白了，感谢。
