### ISSUE TITLE
使用rclone挂载alist的webdav失败

### ISSUE THREAD

**Issue by mm7657** [Xhofe/alist#895]
### Alist Version / Alist 版本

v2.3.2-0-g3427291-dirty

### Describe the bug / 问题描述

使用rclone的挂载webdav功能挂载alist中的网盘，rclone日志提示如下错误：
2022/04/03 05:04:11 ERROR : /: Dir.Stat error: couldn't list files: XML syntax error on line 12: attribute name without = in element
2022/04/03 05:08:41 ERROR : webdav root '': Statfs failed: about call failed: XML syntax error on line 12: attribute name without = in element

rclone添加webdav具体步骤如下：
[caiyun]
type = webdav
url = http://xxxx:5244/onedrive
vendor = other
user = admin
pass = kOE0OJ7rexxxxjPipxObA

### Reproduction / 复现链接

网页正常

**Comment by Xhofe** [comment]
能不能看文档。

**Comment by LordHumphrey** [comment]
你解决了吗

**Comment by githubfzq** [comment]
同样的问题，在Mac上挂载。
