### ISSUE TITLE
Windows11点击potplayer按钮报错

### ISSUE THREAD

**Issue by aliuq** [Xhofe/alist#898]
### Alist Version / Alist 版本

v2.3.2-0-g3427291

### Describe the bug / 问题描述

使用的 docker 部署，浏览器提示以下错误信息

`Failed to launch 'potplayer://http://192.168.2.122:5244/d/aliyun/XXXXX' because the scheme does not have a registered handler.`

![image](https://user-images.githubusercontent.com/11707934/161440746-12b55de2-3f22-4904-8b38-a3603494848b.png)

### Reproduction / 复现链接

Windows 11 上 阿里云盘 任意视频

**Comment by Xhofe** [comment]
你不安装怎么可能打开？？？

**Comment by aliuq** [comment]
> 你不安装怎么可能打开？？？

如果没有安装，我怎么可能提出这样的问题😭😭

我是通过包管理工具安装的

**Comment by Xhofe** [comment]
> > 你不安装怎么可能打开？？？
> 
> 如果没有安装，我怎么可能提出这样的问题😭😭
> 
> 我是通过包管理工具安装的

此处的安装 特指包含了`在注册表中注册了关联URI协议`这一步骤的，使用官方安装是会注册的，我不知道包管理工具是否会注册。

**Comment by aliuq** [comment]
> > > 你不安装怎么可能打开？？？
> > 
> > 如果没有安装，我怎么可能提出这样的问题😭😭
> > 
> > 我是通过包管理工具安装的
> 
> 此处的安装 特指包含了`在注册表中注册了关联URI协议`这一步骤的，使用官方安装是会注册的，我不知道包管理工具是否会注册。

这个怕是没有，我去看看

**Comment by aliuq** [comment]
确实是因为没有注册到注册表，提供一个注册表文件，修改为自己文件路径即可

potplayer.reg

```reg
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\potplayer]
@="URL:potplayer protocol"
"URL Protocol"=""

[HKEY_CLASSES_ROOT\potplayer\shell]

[HKEY_CLASSES_ROOT\potplayer\shell\open]

[HKEY_CLASSES_ROOT\potplayer\shell\open\command]
@="\"C:\\Program Files\\PotPlayer\\PotPlayerMini64.exe\" %1"
```
