### ISSUE TITLE
直链地址不能解析播放了?

### ISSUE THREAD

**Issue by jing207** [Xhofe/alist#90]
新版1.0.3 的视频直链地址,播放失败,有没有解决方法,谢谢

**Comment by Aquaakuma** [comment]
#88 
[https://github.com/Xhofe/alist/issues/88#issuecomment-816815655](url)
参考这个解决了

**Comment by Xhofe** [comment]
https://github.com/Xhofe/alist/issues/88#issuecomment-817047630
正解

**Comment by Taylorkaki** [comment]
#88 (comment)Thanks 已解决。
