### ISSUE TITLE
cf-workers反代错误

### ISSUE THREAD

**Issue by QAQ5555** [Xhofe/alist#900]
### Alist Version / Alist 版本

v2.3.1

### Describe the bug / 问题描述

onedrive使用cf-workers反代
网站图片无法显示，先是302 Found
然后就502 Bad Gateway
打开图片的时候反复请求了一个链接
最开始是请求这个302 Found
https://alist.域名/d/456/%E5%88%86%E4%BA%AB%E6%B5%8B%E8%AF%95/%E5%8A%A0%E5%B7%9E%E6%9D%A5%E7%94%B5.jpg?sign=********************
最后请求到502 Bad Gateway
https://alist.域名/d/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/CF反代.域名/456/%e5%88%86%e4%ba%ab%e6%b5%8b%e8%af%95/%e5%8a%a0%e5%b7%9e%e6%9d%a5%e7%94%b5.jpg?sign=********************

关闭代理后图片加载、下载正常
能不能支持使用普通的onedrive workers js 进行下载，alist反代有点不明白
或者仅下载反代，网站本身不用反代

### Reproduction / 复现链接

两个账号均复现
使用onedrive挂载加alist workers反代即可复现

### Logs / 日志

```shell
302 GET      "/d/456/分享测试/加州来电.jpg?sign=********************"
302 GET      "/d/456/分享测试/加州来电.jpg?sign=********************"
302 GET      "/d/456/分享测试/CF反代.域名/456/分享测试/加州来电.jpg?sign=********************"
302 GET      "/d/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/加州来电.jpg?sign=********************"
302 GET      "/d/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/加州来电.jpg?sign=********************"

GET      "/d/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/加州来电.jpg?sign=********************"

GET      "/d/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/CF反代.域名/456/分享测试/加州来电.jpg?sign=********************"
```

**Comment by Xhofe** [comment]
对于一个URL来说，协议头是必须的。

**Comment by milebye** [comment]
workers 用官方域名是正常的，但使用自定义路由，会出现多次跳转，导致无法访问和下载。 日志报错 too many redirects

**Comment by zzy-ac** [comment]
那就直接用cf的域名，反正只是拿来反代的而已~又不影响啥

**Comment by milebye** [comment]
> 

用自定义是为了可以自选IP，优化访问速度.

**Comment by Xhofe** [comment]
链接：https://alist.xhofe.top/p/Onedrive/README.md?sign=329fa32237381754
1. 是cf-workers中转OneDrive
2. 使用了自定义域名
3. 没有任何问题
