### ISSUE TITLE
Loading stuck at white nothing showing

### ISSUE THREAD

**Issue by adarsh-goel** [Xhofe/alist#902]
### Alist Version / Alist 版本

v2.3.0

### Describe the bug / 问题描述

whenever you run website in google chrome / explorer it is stuck at loading with white backgroud.
vps has 24 gb ram and 4 cpu internet is 4 gbps.

### Reproduction / 复现链接

https://cloud.adarsh.eu.org

**Comment by Xhofe** [comment]
I can open it without any problem either chrome or firefox.

![image](https://user-images.githubusercontent.com/36558727/161731681-def67803-7ed3-4d1b-a79c-291f52cbdf1a.png)
Please check your own causes.
In addition, it is not supported for `IE`.

**Comment by adarsh-goel** [comment]
add support for IE then

**Comment by Xhofe** [comment]
> add support for IE then

There is clearly stated in the documentation: https://alist-doc.nn.ci/en/docs/common-question#about-browser-support
