### ISSUE TITLE
登录显示Invalid token，并且通过./alist -password查询是正确的密码

### ISSUE THREAD

**Issue by yn68** [Xhofe/alist#907]
### Alist Version / Alist 版本

v2.3.2

### Describe the bug / 问题描述

查询的密码是正确的，也无法登录后台，显示Invalid token
### Reproduction / 复现链接

查询的密码是正确的，也无法登录后台，显示Invalid token

**Comment by Xhofe** [comment]
检查你的运行路径。

**Comment by yn68** [comment]
运行路径正确的，
![image](https://user-images.githubusercontent.com/78069636/161894559-fa012680-761c-4361-a066-cacafef1145f.png)

**Comment by Xhofe** [comment]
启动路径呢

**Comment by yn68** [comment]
用的一键脚本 curl -fsSL "https://nn.ci/alist.sh" | bash -s install

**Comment by Xhofe** [comment]
进程杀了 重起。

**Comment by yn68** [comment]
![image](https://user-images.githubusercontent.com/78069636/161897246-6b6ae828-7035-4684-8725-e32222649aec.png)
还是不行

**Comment by Xhofe** [comment]
网址和密码发给我，

**Comment by yn68** [comment]
![image](https://user-images.githubusercontent.com/78069636/161898712-b103b869-8eb8-40e0-99af-b6ac85c595ce.png)
这是什么情况

**Comment by Xhofe** [comment]
...有什么问题 我点了你以前issue里的链接而已

**Comment by yn68** [comment]
为啥有个武汉教育网的ip登录我的后台？

**Comment by yn68** [comment]
哦哦哦

**Comment by yn68** [comment]
这里发密码不会泄露吧？

**Comment by Xhofe** [comment]
[mail](mailto:i@nn.ci)

**Comment by yn68** [comment]
已发，请查收！

**Comment by Xhofe** [comment]
...你自己修改过前端

**Comment by yn68** [comment]
没有修改过

**Comment by yn68** [comment]
不能直接修改后台密码吗？

**Comment by Xhofe** [comment]
密码hash的方法都被你改了 还没改过？？

**Comment by yn68** [comment]
真没，我好像把以前的文件打包了，重新覆盖了一下

**Comment by yn68** [comment]
我卸载重装了，-。-

**Comment by Xhofe** [comment]
你把 密码hash里面的盐 https://github.com/Xhofe/alist 改成了 www.yn68.cn 不是吗，导致密码的hash与后端不对应。

**Comment by yn68** [comment]
这个有影响阿，真不知道，不好意思。

**Comment by yn68** [comment]
不懂源码。。。。。。
