### ISSUE TITLE
希望能够自动合并同名文件夹

### ISSUE THREAD

**Issue by SwQQQ** [Xhofe/alist#909]
### Alist Version / Alist 版本

v2.3.2

### Describe the bug / 问题描述

已知一云盘的文件夹a，a1是a的子文件夹，其中有一些内容；另一云盘的文件夹b，其中也有一些内容(假设与a1的内容完全不重复，因为没有测试重复的情况)。

此时希望能够在a1中展示b的内容，便通过虚拟路径功能进行映射，就会出现两个同名文件夹，并且跳转的内容一致。这十分反直觉，建议改进。
![033D930B-C4E0-4B39-9514-176290FDAAB9](https://user-images.githubusercontent.com/51252864/161938620-ac493cbc-275d-4495-99dc-dc9a60cd5baa.jpeg)
![6DFBF762-6BB3-4F28-B01A-853FBD0858A7](https://user-images.githubusercontent.com/51252864/161938638-46249c06-5a08-4238-a7d2-0fa728f18ebf.jpeg)

### Reproduction / 复现链接

暂无

**Comment by Xhofe** [comment]
不支持，同一路径下最多只能展示一个账号内的文件和其他附加的虚拟文件夹。在获取账号时按照最长匹配，如果需要合并这会极大增加账号复杂度，将不会实现。
