### ISSUE TITLE
请求加入VLC电脑版调用播放

### ISSUE THREAD

**Issue by wangzhilin777** [Xhofe/alist#911]
### Description of the feature / 需求描述

现有VLC移动端调用，可以正常使用。但是电脑端只有potplayer调用播放。potplaer有个问题就是，一旦播放网络地址，就会一直缓存，直到缓存完成。有时候想看一部分就关闭potplayer就满足不了。而且每次写入缓存也偏多。VLC电脑版不会这样，只会提前缓存一部分后，保证流程观察就暂时停止缓存，这种比较符合使用习惯，也接入磁盘写入量。现在只能提取直连然后复制到VLC电脑版播放器中，希望能够加入一键调用播放，像potplayer一样那种。谢谢开发者。

### Suggested solution / 实现思路

chrome插件参考，https://add0n.com/send-to.html?from=vlc，

**Comment by Xhofe** [comment]
chrome插件可以调用本地程序，网页没有这个能力，只能通过`关联URI协议`去调用播放器。
VLC for desktop似乎并没有注册一个通用的`关联URI协议`，当然可能是我没有找到，如果它有注册，你可以告诉我。如果没有，请参照这个discussion自行为VLC注册一个`关联URI协议`，注册之后，你将可以通过原有的`VLC`按钮来调起它。

**Comment by mcnk328** [comment]
用这个看看
https://chrome.google.com/webstore/detail/open-in-vlc-media-player/ihpiinojhnfhpdmmacgmpoonphhimkaj

**Comment by wangzhilin777** [comment]
> 

我测试了阿里云盘的不能自动识别媒体，天翼云的可以。阿里云只能刷新页面的快速右击播放器调用，天翼云不需要。

**Comment by wangzhilin777** [comment]
> 我测试了阿里云盘的不能自动识别媒体，天翼云的可以。阿里云只能刷新页面的快速右击播放器调用，天翼云不需要。



> 用这个看看 https://chrome.google.com/webstore/detail/open-in-vlc-media-player/ihpiinojhnfhpdmmacgmpoonphhimkaj

我测试了阿里云盘的不能自动识别媒体，天翼云的可以。阿里云只能刷新页面的快速右击播放器调用，天翼云不需要。
