### ISSUE TITLE
当一个目录下的文件或文件夹太多会报错

### ISSUE THREAD

**Issue by Wang-KH** [Xhofe/alist#912]
### Alist Version / Alist 版本

v2.3.2-0-g3427291-dirty

### Describe the bug / 问题描述

我在使用谷歌云的时候遇到的问题 当一个目录下的项目太多会出现报错：

Rate Limit Exceeded: [{usageLimits rateLimitExceeded Rate Limit Exceeded }]

<img width="788" alt="image" src="https://user-images.githubusercontent.com/12857702/162037348-27e51ccc-a0ab-4ce4-af57-a1d2748076f4.png">

我的谷歌网盘内有个文件夹装有67tb的电影 文件夹内每个电影又是一个文件夹 初步该路径估计有上万个文件夹，导致alist打开该路径100%出现错误
其他同样有很多项目的路径打开时概率出现错误

目前我用的是cloudflare的代理地址

### Reproduction / 复现链接

https://wkhod.ml/GoogleDrive/%E7%94%B5%E5%BD%B1(%E5%A4%A7%E5%8C%85,67TB)

**Comment by Xhofe** [comment]
这是Google对api的限制策略，似乎没有一个很好的方法解决。。我能想到的也只能时重试与加延时，但是：
重试会导致api调用更加频繁，延时对于一个文件超级多的文件夹会导致api响应极慢。所以最好的解决办法还是：
**自己给文件进行分类**。

**Comment by Wang-KH** [comment]
可以像谷歌云盘官网一样 10个文件10个文件的请求吗

**Comment by Xhofe** [comment]
> 可以像谷歌云盘官网一样 10个文件10个文件的请求吗

本来就是分次请求的，只是一个目录下文件太多就会请求过于频繁。

**Comment by Wang-KH** [comment]
请求好一组就暂停 当往下滑到尽头时再进行下次请求 这样行吗

**Comment by Xhofe** [comment]
不行，要兼容webdav webdav不支持分页 必须一次行请求整个目录。
