### ISSUE TITLE
OD无法读取其他用户分享的文件

### ISSUE THREAD

**Issue by kingkongchow** [Xhofe/alist#915]
### Description of the feature / 需求描述

其他用户分享的文件夹链接在自己帐号下生成快捷方式后，在OD网页端或者客户端均可播放或者操作文件，Alist则读取不到这些文件甚至这些文件夹快捷方式都读取不到。

**Comment by Xhofe** [comment]
不要拿onedrive自己的网页端和客户端来比 他用的又不是开放API。

**Comment by Xhofe** [comment]
官方开放API支持这个？
