### ISSUE TITLE
WebDav 强制只读功能

### ISSUE THREAD

**Issue by moesnow** [Xhofe/alist#918]
### Description of the feature / 需求描述

macOS下Finder总是会自动在WebDav中创建.DS_Store等文件:(
![](https://s3.bmp.ovh/imgs/2022/04/08/27d7b2c46f19c05a.png)

**Comment by Xhofe** [comment]
![image](https://user-images.githubusercontent.com/36558727/162352737-db5ded01-a6a7-4bdd-821b-9c702c131fdc.png)
