### ISSUE TITLE
看图

### ISSUE THREAD

**Issue by 122cygf** [Xhofe/alist#92]
![1](https://user-images.githubusercontent.com/55302758/114397248-0cca8080-9bd1-11eb-9ced-30d8ecb6c4b5.jpg)
![2](https://user-images.githubusercontent.com/55302758/114397265-13f18e80-9bd1-11eb-8220-411707ba3362.png)
![3](https://user-images.githubusercontent.com/55302758/114397296-1ce26000-9bd1-11eb-806f-43f42ad5c8b7.jpg)
![4](https://user-images.githubusercontent.com/55302758/114397349-2e2b6c80-9bd1-11eb-9310-d0b0baa29a8c.jpg)
![5](https://user-images.githubusercontent.com/55302758/114397384-3aafc500-9bd1-11eb-83dd-aa963525ecce.jpg)
![6](https://user-images.githubusercontent.com/55302758/114397423-44d1c380-9bd1-11eb-9292-92723b5a1233.jpg)
![7](https://user-images.githubusercontent.com/55302758/114397461-4d29fe80-9bd1-11eb-81ba-64e44a284668.jpg)

**Comment by Xhofe** [comment]
❓🤔️

**Comment by 122cygf** [comment]
> ❓🤔️

可以绕过阿里云盘分享的客户端限制

**Comment by Xhofe** [comment]
哦哦 这样啊🐂
