### ISSUE TITLE
功能需求：增加静态资源可用位置，到vercel和netlify

### ISSUE THREAD

**Issue by aiyou9** [Xhofe/alist#922]
### Description of the feature / 需求描述

assets​ 使用的静态资源位置，期望能添加vercel和netlify，尤其时vercel，官方说是，增加CDN了，国内打开，速度还行

### Suggested solution / 实现思路

只要在vercel中拉取一下alist的assest仓库，就可访问，参考大佬的教程如下：
https://www.geekyes.com/490.htm
vercel拉取git库，然后绑定到vercel或netlify就可以获得二级网址，然后就可以访问其中的静态资源

### Additional context / 附件

图片网址就是vercel.的给的网址
https://photo-three.vercel.app/1.jpg

**Comment by Xhofe** [comment]
自己添加不行吗，个人免费只有100G流量。我怎么可能当作公共cdn用。。。

**Comment by aiyou9** [comment]
> 那你自己添加啊，个人免费只有100G流量。我自己用都嫌不够，怎么可能当作公共cdn用。。。

抱歉，我忘了这茬了，手动狗头🤣

**Comment by woshichenghaibo** [comment]
> 特别需要部署在vercel上面，请教方法，测试了怎么安装都不行
