### ISSUE TITLE
用Cloudflare worker优选IP反代Onedrive

### ISSUE THREAD

**Issue by foxdodo** [Xhofe/alist#923]
### Description of the feature / 需求描述

没开梯子用的heroku机器中转流量, 晚上看alist在线视频很卡, 换成CF中转也卡, 多线程下载倒影响不大. 逛了一圈试了Cloudflare worker优选IP的方法能改善在线视频流畅度. 这应该是除了搭梯子和自建反代服务器以外能流畅看视频的白嫖方法了, 大佬有办法集成到以后的版本里吗?最好是一键搭好那种😁本人纯小白不会代码

### Suggested solution / 实现思路

准备工作:
- 用[CloudflareSpeedTest](https://github.com/XIU2/CloudflareSpeedTest)筛选出一个优选IP,例如`104.24.213.225`
- 手里有一个经过Cloudflare解析的域名例如`example.com`

开始设置
1.[按教程设置好worker](https://alist-doc.nn.ci/docs/driver/base/#cloudflare-workers), 这里假设设置好的worker名字是`alistworker`
2.在Cloudflare用自己的域名建一个A记录, 解析到优选IP, 关闭小云朵. 例如把二级域名`boostalist.example.com`解析到`104.24.213.225` 
3.点Cloudflare主页左侧`网站`按钮, 找到自己的域名`example.com`点击进入, 在左侧点`worker`然后点`添加路由`按钮, 路由填`boostalist.example.com/*`,服务下拉菜单选刚建好的`alistworker`然后保存.
4.在alist管理面板编辑onedrive账号, 在`down_proxy_url`填入`https://boostalist.example.com`保存并刷新缓存
[思路来源](https://github.com/XIU2/CloudflareSpeedTest/issues/189)

**Comment by Xhofe** [comment]
这全是cf上的操作，和alist有任何关系？
