### ISSUE TITLE
为OneDrive添加直接代理模式

### ISSUE THREAD

**Issue by SerendipityR2022** [Xhofe/alist#924]
### Description of the feature / 需求描述

现有使用下载反代的需求，但发现接入cf worker后速度变得更慢
计划使用CDN自选azure cdn ip反代sharepoint域名实现加速。
但下载时只会请求到 CDN_URL/path?sign=sign_value 造成404错误

### Suggested solution / 实现思路

增加direct_proxy配置部分，此模式下将下载及文件预览链接中的sharepoint域名部分替换为cdn加速域名

**Comment by Xhofe** [comment]
这并不通用，不会添加。如果你有刚需，你可以参照https://alist-doc.nn.ci/docs/driver/base#%E9%80%9A%E7%94%A8%E4%BA%8C%E8%BF%9B%E5%88%B6 自己实现代理程序，只需要在最后一步将请求下载链接改为替换域名返回重定向即可。

**Comment by SerendipityR2022** [comment]
好的 功能已实现 感谢解答
