### ISSUE TITLE
can't create multiple users and passwords

### ISSUE THREAD

**Issue by kanekabkz** [Xhofe/alist#928]
### Alist Version / Alist 版本

v2.3.2

### Describe the bug / 问题描述

When I try to put a password on the same file path from the meta section, I get the error I mentioned in the photo.
![photo_2022-04-10_16-08-14](https://user-images.githubusercontent.com/79414108/162619727-f501826c-13ab-4de7-87f9-90cd70621f9a.jpg)

### Reproduction / 复现链接

https://github.com/Xhofe/alist

**Comment by Xhofe** [comment]
Adding multiple meta records to the same path is not supported.
