### ISSUE TITLE
本地文件排序bug

### ISSUE THREAD

**Issue by 253551464** [Xhofe/alist#929]
### Alist Version / Alist 版本

v2.3.2-0-g3427291-dirty

### Describe the bug / 问题描述

本地文件选择文件夹在前面时排序混乱

### Reproduction / 复现链接

本地文件
排序：名称
排序方向：升序
extract_folder：back
文件排序没问题，跟在文件管理器的基本无差
![IMG_20220411_162128](https://user-images.githubusercontent.com/36783515/162695723-5dda7caa-3b93-4eba-ac19-708d99d3029f.jpg)
修改extract_folder为front后，文件排序就乱了
![IMG_20220411_162705](https://user-images.githubusercontent.com/36783515/162696136-9f7014c6-5f0e-4e4b-aab7-9f1e60a3bcb6.jpg)

**Comment by Xhofe** [comment]
似乎无法复现。

**Comment by 253551464** [comment]
> ~似乎无法复现。~
> 
> 加了中文复现了

大佬辛苦了
