### ISSUE TITLE
当一个文件夹内文件过多，加载完成后，显示文件出现卡顿

### ISSUE THREAD

**Issue by Latticect** [Xhofe/alist#930]
### Alist Version / Alist 版本

v2.3.2

### Describe the bug / 问题描述

加载一个大量文件的文件夹，转圈转完之后，显示文件会出现很长时间卡顿（无法点击），在手机端尤其不友好，并如果刚显示出来快速下滑，会出现空白，还容易出现未响应。
因看到作者在 https://github.com/Xhofe/alist/issues/912 提出无法在后端进行分页
我有两个想法：
1、可以尝试在前端做给分页
2、在后端做分页，在webdav用虚拟目录实现分页
[![LZOd4P.md.jpg](https://s1.ax1x.com/2022/04/12/LZOd4P.md.jpg)](https://imgtu.com/i/LZOd4P)
[![LZOaNt.md.jpg](https://s1.ax1x.com/2022/04/12/LZOaNt.md.jpg)](https://imgtu.com/i/LZOaNt)
[![LZOUAI.md.jpg](https://s1.ax1x.com/2022/04/12/LZOUAI.md.jpg)](https://imgtu.com/i/LZOUAI)

### Reproduction / 复现链接

https://yun.ltt.zone/%E5%8A%A8%E6%BC%AB/bangumi-sync

**Comment by Xhofe** [comment]
提issue之前请查看文档和搜索之前的issue有无重复。

**Comment by Latticect** [comment]
有类似issue，但那个issue是出现报错，我这边是能加载出来，但过出现卡顿或者未响应的情况，应该是一次性加入的元素过多导致的

**Comment by Latticect** [comment]
在显示出文件项目过程中，不是转圈加载中，CPU和内存也会保持在一个较高的占用
[![LZxiVJ.jpg](https://s1.ax1x.com/2022/04/12/LZxiVJ.jpg)](https://imgtu.com/i/LZxiVJ)
