### ISSUE TITLE
后台账号配置里的虚拟路径能否选填？

### ISSUE THREAD

**Issue by XiaoPika** [Xhofe/alist#936]
### Alist Version / Alist 版本

2.3.2

### Describe the bug / 问题描述

我只配置了一个网盘账号，从2.0.9更新到2.3.2以后之前所有的链接都失效了
原来的路径是` /首页/xxx1`，直链是`https://xxx.com/xxx1`
更新以后，首页是`/首页/阿里云盘/xxx1`，直链是`https://xxx.com/阿里云盘/xxx1`
我看了大佬的更新日志，只提了增加虚拟路径，但是没提怎么保持原来版本默认展示网盘的配置项，希望大佬解惑

### Reproduction / 复现链接

　.

**Comment by Xhofe** [comment]
虚拟路径 填 /

另外，这不是bug。
