### ISSUE TITLE
希望文件名能显示全

### ISSUE THREAD

**Issue by ttwzxk** [Xhofe/alist#937]
### Description of the feature / 需求描述

对于文件名/文件夹名比较长的情况下，列表预览中无法全部显示，希望考虑一下能全部显示

### Suggested solution / 实现思路

增加一种详细显示方式，文件名过长多行显示

**Comment by Xhofe** [comment]
怎么显示呢？详细说清楚。
最好给出原型设计图。

**Comment by Xhofe** [comment]
且简单的换行完全可以自己通过css实现。
```html
<style>
.list-item-name>p{
  white-space: normal !important;
}
</style>
```
