### ISSUE TITLE
请求增加直链下载时需输入文件夹密码（如有）功能

### ISSUE THREAD

**Issue by judiw** [Xhofe/alist#940]
### Description of the feature / 需求描述

使用直链下载时，如果对应文件的父文件夹存在密码，则需要输入密码才能访问，以此减少被防盗链的几率（OnedriveCN的API限制实在是伤不起），或者增加可以关闭直链按钮的功能，谢谢

### Suggested solution / 实现思路

使用直链下载时，如果对应文件的父文件夹存在密码，则需要输入密码才能访问（目前隔壁OneManager是支持这个功能的，但是alist的UI真的很赞，所以希望这边也能实现这个功能）

**Comment by Xhofe** [comment]
打开https://alist-doc.nn.ci/docs/setting/backend#%E6%A3%80%E6%9F%A5%E7%88%B6%E6%96%87%E4%BB%B6%E5%A4%B9%E5%AF%86%E7%A0%81
和
https://alist-doc.nn.ci/docs/setting/backend#check-down-link
 。

**Comment by judiw** [comment]
打开之后复制的直链里面包含密码，但是和父文件夹的密码并没有关系

**Comment by Xhofe** [comment]
是根据父文件夹密码计算的。

**Comment by Xhofe** [comment]
或者你需要输入密码下载的话，不要复制直链。直接复制浏览器页面地址。

**Comment by judiw** [comment]
好的，谢谢解答
