### ISSUE TITLE
Google Drive 通过代理方式不能上传文件

### ISSUE THREAD

**Issue by usufu** [Xhofe/alist#943]
### Alist Version / Alist 版本

v2.3.2-0-g3427291

### Describe the bug / 问题描述

通过alist-proxy搭建了一个代理，用来代理OneDrive和Google drive。
通过Google drive上传文件时，经常报错，报错日志如下：其中xxx.com为自己搭建的代理地址。

ERRO[2022-04-15 06:43:31] upload error: Put "https://xxx.com/https://www.googleapis.com/upload/drive/v3/files?supportsAllDrives=true&uploadType=resumable&upload_id=ADPycdv7YB-WHGQh9Op7pvjfrkqwzyRlEwz7kEToQ2PhDGa1lMYlNmAKnPyfAvRLJnoAraEhQpUFBU0IMm0l_RpSIrY8MQ&includeItemsFromAllDrives=true&supportsAllDrives=true": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
ERRO[2022-04-15 06:43:31] Put "https://xxx.com/https://www.googleapis.com/upload/drive/v3/files?supportsAllDrives=true&uploadType=resumable&upload_id=ADPycdv7YB-WHGQh9Op7pvjfrkqwzyRlEwz7kEToQ2PhDGa1lMYlNmAKnPyfAvRLJnoAraEhQpUFBU0IMm0l_RpSIrY8MQ&includeItemsFromAllDrives=true&supportsAllDrives=true": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### Reproduction / 复现链接

暂无

### Logs / 日志

```shell
见问题描述。
```

**Comment by Xhofe** [comment]
Googledrive上传的方式是redirect 暂不支持中转。

**Comment by usufu** [comment]
那就Google 不支持代理方式上传文件？alist在国内服务器的话，只能下载和浏览是吧？

Xhofe ***@***.***> 于2022年4月15日周五 14:54写道：

**Comment by Xhofe** [comment]
> 

是的

**Comment by usufu** [comment]
但我发现，如果上传的文件比较小，是可以上传成功的。这是怎么回事呢？

Xhofe ***@***.***> 于2022年4月15日周五 16:11写道：
