### ISSUE TITLE
这边有百度云盘 不限速 不需要vip 不限制大小 ua 方法

### ISSUE THREAD

**Issue by alizyw** [Xhofe/alist#945]
### Description of the feature / 需求描述

这边有百度云盘 不限速 不需要vip 不限制大小 ua 方法

群里联系你了 qq2894642

测试链接https://d.pcs.baidu.com/file/5cfef9208k461d6be4ab79742db9d2a0?fid=71537345-250528-838407038616124&rt=pr&sign=FDtAERK-DCb740ccc5511e5e8fedcff06b081203-JHDkbYUebKwfGyWggLJ%2fjTIgZmI%3d&expires=8h&chkbd=0&chkv=0&dp-logid=126658655974879257&dp-callid=0&dstime=1650028175&r=994802375&vuk=71537345&origin=dlna

### Additional context / 附件

https://d.pcs.baidu.com/file/5cfef9208k461d6be4ab79742db9d2a0?fid=71537345-250528-838407038616124&rt=pr&sign=FDtAERK-DCb740ccc5511e5e8fedcff06b081203-JHDkbYUebKwfGyWggLJ%2fjTIgZmI%3d&expires=8h&chkbd=0&chkv=0&dp-logid=126658655974879257&dp-callid=0&dstime=1650028175&r=994802375&vuk=71537345&origin=dlna

**Comment by Xhofe** [comment]
可以直接在这里发文档
