### ISSUE TITLE
可越过密码访问文件

### ISSUE THREAD

**Issue by admin-set** [Xhofe/alist#959]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.0.0

### Describe the bug / 问题描述

[问题反馈.pdf](https://github.com/Xhofe/alist/files/8501330/default.pdf)

** 具体详细信息查看问题反馈pdf**

例如： http://alist.xxx.com/阿里网盘 需要密码 
但是直接通过 url 访问 http://alist.xxx.com/阿里网盘 /alist 不需要密码可访问

![image-20220417175207630](https://raw.githubusercontent.com/beitso-admin/img/master/202204171753226.png)

![image-20220417175243666](https://raw.githubusercontent.com/beitso-admin/img/master/202204171753631.png)

后端设置的密码

![image-20220417175507009](https://raw.githubusercontent.com/beitso-admin/img/master/202204171758897.png)

后端设置的账号

![image-20220417175811295](https://raw.githubusercontent.com/beitso-admin/img/master/202204171758672.png)

### Reproduction / 复现链接

例如： http://alist.xxx.com/阿里网盘 需要密码 
但是直接通过 url 访问 http://alist.xxx.com/阿里网盘 /alist 不需要密码可访问

![image-20220417175207630](https://raw.githubusercontent.com/beitso-admin/img/master/202204171753226.png)

![image-20220417175243666](https://raw.githubusercontent.com/beitso-admin/img/master/202204171753631.png)

后端设置的密码

![image-20220417175507009](https://raw.githubusercontent.com/beitso-admin/img/master/202204171758897.png)

后端设置的账号

![image-20220417175811295](https://raw.githubusercontent.com/beitso-admin/img/master/202204171758672.png)

### Logs / 日志

```shell
例如： http://alist.xxx.com/阿里网盘 需要密码 
但是直接通过 url 访问 http://alist.xxx.com/阿里网盘 /alist 不需要密码可访问

![image-20220417175207630](https://raw.githubusercontent.com/beitso-admin/img/master/202204171753226.png)

![image-20220417175243666](https://raw.githubusercontent.com/beitso-admin/img/master/202204171753631.png)

后端设置的密码

![image-20220417175507009](https://raw.githubusercontent.com/beitso-admin/img/master/202204171758897.png)

后端设置的账号

![image-20220417175811295](https://raw.githubusercontent.com/beitso-admin/img/master/202204171758672.png)
```

**Comment by lsjcx** [comment]
可以设置引用到子文件夹
