### ISSUE TITLE
搜索安全问题

### ISSUE THREAD

**Issue by 12189108** [Xhofe/alist#962]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.4.1-0-g82a5c43-dirty

### Describe the bug / 问题描述

当我开启搜索功能后，不管文件夹是否被设置密码，都能搜索到对应文件（即使我没有对应文件夹的密码），例如我只需搜索文件类型，如txt、pdf等就可以出现对应文件及其链接

### Reproduction / 复现链接

任意安装Alist并启用搜索功能的网站

**Comment by Xhofe** [comment]
## v2.4.0

- 全局README.md
- 添加账号时按钮增加loading
- 前端添加legacy support
- 修复阿里云盘删除文件夹状态判断 [#886](https://github.com/Xhofe/alist/issues/886)
- 新的存储支持：SFTP
- 增加是否开启秒传的选项
- 代理webdav时移除非必要的header：authorization [#893](https://github.com/Xhofe/alist/issues/893)
- 支持通过webdav方式挂载OneDrive/SharePoint，没有API也可以挂载(比如某些学校无管理员的账号) [#460](https://github.com/Xhofe/alist/issues/460)
- 修复夸克代理Referer
- 支持在meta中对特定路径添加readme
- ~~修复本地文件夹大小~~
- 修复多级虚拟路径错误 [#904](https://github.com/Xhofe/alist/issues/904)
- 修复天翼云盘PC修改时间错误 [#910](https://github.com/Xhofe/alist/issues/910)
- 修复分离文件夹时破坏文件排序 [#929](https://github.com/Xhofe/alist/issues/929)
- 百度网盘添加了一个非官方下载接口(crack)，无需修改UA [#945](https://github.com/Xhofe/alist/issues/945)
- 修复虚拟路径导致的重复文件 [#941](https://github.com/Xhofe/alist/issues/941)
- 修复夸克网盘文件数量大于100文件丢失的问题 [#947](https://github.com/Xhofe/alist/issues/947)
- 增加搜索（**实验性功能，开发中不推荐使用**）
