### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by yuehun** [Xhofe/alist#964]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.4

### Describe the bug / 问题描述

无法启动
![微信截图_20220418105856](https://user-images.githubusercontent.com/24507941/163747540-36d1bb57-bbf3-4dc1-b265-b2a3b0dd319a.png)

### Reproduction / 复现链接

![微信截图_20220418105856](https://user-images.githubusercontent.com/24507941/163747547-2af69885-90f2-4e79-9111-a83da0164fbd.png)

**Comment by Xhofe** [comment]
真的有阅读文档？

> 其中的xxxx是指不同系统/架构对应的名称，一般Linux-x86/64是alist-linux-amd64，**如果你的glibc版本过低，建议下载musl版本**
> -- https://alist-doc.nn.ci/docs/install/manual#linux

**Comment by yuehun** [comment]
> 真的有阅读文档吗？
> 
> > 其中的xxxx是指不同系统/架构的名称，一般Linux-x86/64是alist-linux-amd64，**如果你的glibc版本过低，建议下载musl版本**
> > -- [https://alist-doc.nn。 ci/docs/install/manual#linux](https://alist-doc.nn.ci/docs/install/manual#linux)

我的，对不起，哈哈哈哈
