### ISSUE TITLE
onedrive添加流程建议

### ISSUE THREAD

**Issue by ddaodan** [Xhofe/alist#967]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

感觉onedrive的添加有点麻烦，而且存在一定不稳定性
建议：

- 重定向uri处直接填好
- 刷新令牌可以直接根据填写的客户端ID和机密获取
- 国际版是可以一键创建客户端id和机密的，可以参考onindex

### Suggested solution / 实现思路

- 现在uri必须添加https://tool.nn.ci/onedrive/callback，那不如直接默认填好
- 将https://tool.nn.ci/onedrive/request这个功能加在程序里，前面的client_id和client_secret填好后点击按钮获取token，然后直接填好
- 下面的图是我的onlaindex添加帐号的页面，可以参考一下这个申请功能

### Additional context / 附件

![Screenshot_2022-04-18-21-24-32-200_com android chrome](https://user-images.githubusercontent.com/40017293/163814662-2fa77055-efb3-4397-be9e-a8fab4bf13ad.jpg)

**Comment by Xhofe** [comment]
1. 可以添加
2. 现有架构不支持这样做
3. 没有用过

**Comment by ddaodan** [comment]
> 2. 现有架构不支持这样做
可以将获取的方法开源吗，万一哪天打不开了还能自行搭建

> 3. 没有用过
onlaindex项目地址 https://github.com/wangningkai/olaindex
可以参考一下

**Comment by Xhofe** [comment]
> > 2. 现有架构不支持这样做
> 
> 可以将获取的方法开源吗，万一哪天打不开了还能自行搭建

https://docs.microsoft.com/zh-cn/onedrive/developer/rest-api/getting-started/graph-oauth?view=odsp-graph-online
> > 3. 没有用过
> 
> onlaindex项目地址 https://github.com/wangningkai/olaindex 可以参考一下 需要测试的话可以提供空白帐号

创建应用并不是什么难事，也不是常用操作。
