### ISSUE TITLE
webDAV忽略大小为0文件可能导致部分程序的出错

### ISSUE THREAD

**Issue by OldTaoge** [Xhofe/alist#974]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.4.1

### Describe the bug / 问题描述

同#701,Hyper backup会创建空文件当作锁，但是会被忽略[webadv/file.go](https://github.com/Xhofe/alist/blob/v2/server/webdav/file.go#L193),导致出错

### Reproduction / 复现链接

在#701的[reply](https://github.com/Xhofe/alist/issues/701#issuecomment-1102672614)

**Comment by Xhofe** [comment]
特意这样做的，部分存储不支持上传大小为0的文件。
还有一部分支持空文件，但是上传正常文件时会先创建一个空文件却不支持覆盖上传，导致上传之后的文件名与原文件不一样。

**Comment by OldTaoge** [comment]
如果是这样，我在测试的时候发现通过Web可以上传上传大小为0的文件，也许应该把标题改成这个bug

不过还是建议能增加一个选项是否上传空文件

**Comment by Xhofe** [comment]
> 如果是这样，我在测试的时候发现通过Web可以上传上传大小为0的文件，也许应该把标题改成这个bug
> 
> 不过还是建议能增加一个选项是否上传空文件

我测试过 你可以尝试这样做 允许WebDAV上传空文件，但是对那些需要预创建空文件的客户端来说 多数情况都会失败。

**Comment by shallowzzz** [comment]
> 如果是这样，我在测试的时候发现通过Web可以上传上传大小为0的文件，也许应该把标题改成这个bug
> 
> 不过还是建议能增加一个选项是否上传空文件

大佬你最后解决了吗，我用hyper backup也遇到了创建了文件夹但是备份失败的问题

**Comment by OldTaoge** [comment]
> > 如果是这样，我在测试的时候发现通过Web可以上传上传大小为0的文件，也许应该把标题改成这个bug
> > 不过还是建议能增加一个选项是否上传空文件
> 
> 大佬你最后解决了吗，我用hyper backup也遇到了创建了文件夹但是备份失败的问题

这个问题目前看来是无解的，除非云服务厂商都能支持空文件上传或者自己改源码把空文件存数据库
