### ISSUE TITLE
OneDrive proxy开 下载速度变慢

### ISSUE THREAD

**Issue by weizai408** [Xhofe/alist#975]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist-doc.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

最新版

### Describe the bug / 问题描述

添加的OneDrive，proxy开 使用的vps本身流量，最近发现下载速度慢很多，只能到3MB/S；而下载vps本地硬盘的速度能到30MB/S。
使用其他程序挂载同一OneDrive，也走vps流量，速度正常。
希望看看哪里出问题了。

### Reproduction / 复现链接

NA

**Comment by hushanjushi** [comment]
但是，重复的问题在哪。。。。没找到啊
