### ISSUE TITLE
百度网盘刷新令牌

### ISSUE THREAD

**Issue by yqchilde** [Xhofe/alist#979]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.0.0

### Describe the bug / 问题描述

根据文档获取了令牌后，页面报错，查到该报错是访问密码错误

```shell
errno: -9, refer to https://pan.baidu.com/union/doc/
```

![image](https://user-images.githubusercontent.com/36953759/164202784-ded31603-73c7-4e7f-a017-ad9019cea745.png)

### Reproduction / 复现链接

暂无

### Logs / 日志

```shell
ERRO[2022-04-20 09:53:04] errno: -9, refer to https://pan.baidu.com/union/doc/
```

**Comment by Xhofe** [comment]
目录不存在。请填写正确的目录

**Comment by yqchilde** [comment]
> 目录不存在。请填写正确的目录

抱歉，根目录路径以为是要挂载到本地的，👌🏻

**Comment by aogg** [comment]
这根目录名字就不对，我一个新人就理解错了，或者文档写清楚点也好啊
