### ISSUE TITLE
个人Onddrive添加成功  但是无法获取site_id 无法挂载 sharepoint站点

### ISSUE THREAD

**Issue by DifferentSparkler** [Xhofe/alist#980]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.4.1-0-g82a5c43-dirty

### Describe the bug / 问题描述

个人Onddrive添加成功  但是无法获取site_id  无法挂载sharepoint站点

### Reproduction / 复现链接

![image](https://user-images.githubusercontent.com/38945550/164214743-7136ebee-3bc5-4087-9d97-b432836a2944.png)
![image](https://user-images.githubusercontent.com/38945550/164214837-fd8f5f3b-1cc8-4d9c-b4d0-3f880cb5ed2b.png)

**Comment by Xhofe** [comment]
看清楚site_url的格式。
