### ISSUE TITLE
无法启动，报错

### ISSUE THREAD

**Issue by 5536086** [Xhofe/alist#982]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist-doc.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).

### Alist Version / Alist 版本

v2.4.1

### Describe the bug / 问题描述

无法启动，报错

### Reproduction / 复现链接

./alist: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by ./alist)

### Logs / 日志

```shell
无
```

**Comment by isSuperman** [comment]
我也遇到同样问题，百度一下就可解决，

**Comment by 5536086** [comment]
> 我也遇到同样问题，百度一下就可解决，

centos7 应该是GLIBC版本太老了导致的，想办法更新GLIBC到2.28，centos支持库太旧了，还要更新make和gcc，好麻烦的说
