### ISSUE TITLE
添加"Motrix"文件下载选项 --- 分流打包下载错误频率较高的问题

### ISSUE THREAD

**Issue by anwen-anyi** [Xhofe/alist#983]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist-doc.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

现在打包下载经常失败,还比较麻烦, **文件要是比较多和比较大 到时候解压还比较麻烦**
前阵子导出了空间数据 用到了 "Motrix" ，
就想着添加一个 用Motrix批量下载的按钮.

如果是一个文件的话还是用现在已经提供的单个选项进行下载,
如果选择 >2 个的时候使用 先选择自己想要下载文件(批量文件) 然后点击一个按钮唤醒 Motrix, 然后自动推送到下载任务当中[监控到粘贴板信息](前提是得开启Motrix才行..不然没法推送)

现有的 网盘直链下载助手(浏览器插件),就是可以使用Motrix进行任务下载推送...

### Suggested solution / 实现思路

1. -先选择自己的文件
2. -点击唤醒软件自己随便加了个按钮用来唤醒软件 **如果没有提前打开软件就点击一次把软件先唤醒**,唤醒后再自己点一下按钮把复制的链接推送到下载任务,   
   1. -如果提前打开了直接推送到Motrix下载任务

### Additional context / 附件

模拟下载视频

视频中进行了简单模拟下载, 
1. - 先选择自己的文件
2. - 点击唤醒软件[自己随便加了个按钮用来唤醒软件](如果没有提前打开软件就点击一次把软件先唤醒),唤醒后再自己点一下按钮把复制的链接推送到下载任务,   
  2.1 - 如果提前打开了直接推送到Motrix下载任务

  
  Motrix需要使用 16800端口(启动软件就会开启)
  

模拟推送下载视频(比较粗糙...,不晓得能不能理解我的意思 哈哈哈)：「Motrix模拟下载.mp4」https://www.aliyundrive.com/s/KWEi5UVRnkw
插件演示推送图 ： https://vkceyugu.cdn.bspapp.com/VKCEYUGU-0d8c17ea-3b18-45d5-bf2f-64e5c812dfc9/128b3903-3e1a-47cd-afdc-557a4415949a.gif
那个下载插件地址 ： https://www.baiduyun.wiki/zh-cn/motrix.html

**Comment by Xhofe** [comment]
我不认为在Motrix中点一下`➕`是一件多困难的事。

**Comment by anwen-anyi** [comment]
> 我不认为在 Motrix 中点一下`➕`是一件多困难的事情。

哈哈哈 嗝,确实...只是想着更加懒一步,或者告知一下.修改侧边栏的内容在具体在哪个界面呢我自己改自己加一个唤醒趴~ QAQ..
翻了一下看不太懂..

**Comment by Xhofe** [comment]
> > 我不认为在 Motrix 中点一下`➕`是一件多困难的事情。
> 
> 哈哈哈 嗝,确实...只是想着更加懒一步,或者告知一下.修改侧边栏的内容在具体在哪个界面呢我自己改自己加一个唤醒趴~ QAQ.. 翻了一下看不太懂..

https://github.com/alist-org/alist-web/tree/v2/src/components/overlay/site-settings

**Comment by anwen-anyi** [comment]
> > 我不认为在 Motrix 中点一下`➕`是一件多困难的事情。
> 
> 哈哈哈 嗝,确实...只是想着更加懒一步,或者告知一下.修改侧边栏的内容在具体在哪个界面呢我自己改自己加一个唤醒趴~ QAQ.. 翻了一下看不太懂..

还有就是侧边栏使用的SVG图标是哪里的库呢? 之前用 审查元素方法添加了一个(fontawesome图标不太一样，增加的比较大),想着到时候一个库的样式图标 比较整齐点儿..

**Comment by Xhofe** [comment]
> > > 我不认为在 Motrix 中点一下`➕`是一件多困难的事情。
> > 
> > 
> > 哈哈哈 嗝,确实...只是想着更加懒一步,或者告知一下.修改侧边栏的内容在具体在哪个界面呢我自己改自己加一个唤醒趴~ QAQ.. 翻了一下看不太懂..
> 
> 还有就是侧边栏使用的SVG图标是哪里的库呢? 之前用 审查元素方法添加了一个(fontawesome图标不太一样，增加的比较大),想着到时候一个库的样式图标 比较整齐点儿..

https://github.com/alist-org/alist-web/blob/524e80879a61a97ffbf6025a47460c565705eba2/package.json#L45

**Comment by anwen-anyi** [comment]
> > > > 我不认为在 Motrix 中点一下`➕`是一件多困难的事情。
> > > 
> > > 
> > > 哈哈哈 嗝,确实...只是想着更加懒一步,或者告知一下.修改侧边栏的内容在具体在哪个界面呢我自己改自己加一个唤醒趴~ QAQ.. 翻了一下看不太懂..
> > 
> > 
> > 还有就是侧边栏使用的SVG图标是哪里的库呢? 之前用 审查元素方法添加了一个(fontawesome图标不太一样，增加的比较大),想着到时候一个库的样式图标 比较整齐点儿..
> 
> https://github.com/alist-org/alist-web/blob/524e80879a61a97ffbf6025a47460c565705eba2/package.json#L45
(╥﹏╥)  好吧,尝试了增加一张Go单页 没用一点儿Go语法表示给难住了...先搁置一边去了... QAQ...
